### ISSUE TITLE
Can't download  MAPS Database in model Onsets and Frames?

### ISSUE THREAD

**Issue by Calvin-Shen** [tensorflow/magenta#1006]
I want to run the modle locally.Firstly,you need to download MAPS Database but,it need to log in the website.However, I can't find the entry point  of the register. Anyone can provide the solution? Thanks a lot?

**Comment by cghawthorne** [comment]
On the [MAPS page](http://www.tsi.telecom-paristech.fr/aao/en/2010/07/08/maps-database-a-piano-database-for-multipitch-estimation-and-automatic-transcription-of-music/), there's a [download link](http://service.tsi.telecom-paristech.fr/cgi-bin/user-service/subscribe.cgi?ident=maps&form=&license=1). If it asks for a login/password, I think you can just hit cancel and it will work anyway.

**Comment by wrannaman** [comment]
Took about 30 minutes but after registering they emailed me an ftp url to use to download.

**Comment by jefemagril** [comment]
At first I thought the database was taken down from the ftp server, but I was wrong. It's tricky. Here's how I got it to work:
`ftp -p ftps.tsi.telecom-paristech.fr`
then enter your credentials. Now, if you try `ls` you won't get anything, but if you type `cd maps` it puts you in the right place and then `ls` does work. If you want to download all the files in the database you should first type `prompt` to turn off interactive mode (so it doesn't prompt you for every file), then `mget *`. Hope this helps other lost souls.

**Comment by rainbowjack** [comment]
here's how you download it : first you registering,then wait for the email that they open the permissions for you.
then you download FileZilla,just the most basic one would work,then you Type in the url he gave you,your email when you registeringed and the password you set,wait a sec ,you can download

**Comment by Wiggle8** [comment]
use lftp+ftp url
