### ISSUE TITLE
Polyphony rnn tracks discarded if too long

### ISSUE THREAD

**Issue by iantheconway** [tensorflow/magenta#1016]
Hey there, I'm trying to train a custom polyphony_rnn model using recordings of myself improvising on a midi instrument. 
I'm following the instructions at: https://github.com/tensorflow/magenta/blob/master/magenta/models/polyphony_rnn/README.md
including the tutorial on building a dataset at:
https://github.com/tensorflow/magenta/blob/master/magenta/scripts/README.md
The problem I keep running into is that after creating my note sequence, when I try to call `polyphony_rnn_create_dataset `
after creating my notesequences.tfrecord file, the midi tracks are discarded for being too long. I took my 20 minute file and chopped into 20 files, about 1 minute each, and this still seemed to be the case.
I want to know:

- Is there a parameter which will let me increase the maximum length before there files are discarded?
- what is said maximum length?
- Is there a tool recommended for automatically segmenting midi files?

On a related note, before I noticed that the files were discarded, I tried to continue with training, pointed at an empty (0 bytes) training_poly_tracks.tfrecord. This resulted in the following output:
```INFO:tensorflow:hparams = {'rnn_layer_sizes': [64, 64], 'learning_rate': 0.001, 'clip_norm': 5, 'batch_size': 64, 'dropout_keep_prob': 0.5}
INFO:tensorflow:Train dir: logdir/run1/train
INFO:tensorflow:Counting records in polyphony_rnn/sequence_examples/training_poly_tracks.tfrecord.
INFO:tensorflow:Total records: 0
INFO:tensorflow:[<tf.Tensor 'random_shuffle_queue_Dequeue:0' shape=(?, 259) dtype=float32>, <tf.Tensor 'random_shuffle_queue_Dequeue:1' shape=(?,) dtype=int64>, <tf.Tensor 'random_shuffle_queue_Dequeue:2' shape=() dtype=int32>]
WARNING:tensorflow:From /Users/ianconway/anaconda/envs/magenta_2/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py:412: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
2018-01-15 15:12:40.736113: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
```

And the program seems to hang indefinitely while using a lot of CPU.
I see that there is an INFO level statement about 0 total records, but a sanity check for an empty tfrecord might be a nice feature.

**Comment by iantheconway** [comment]
Update: I noticed that in magenta/magenta/models/polyphony_rnn/polyphony_rnn_create_dataset.py
the pipline instance hardcodes the max steps to 512:
`pipeline_instance = get_pipeline(
      min_steps=80,  # 5 measures
      max_steps=512,
      eval_ratio=FLAGS.eval_ratio,
      config=polyphony_model.default_configs['polyphony'])`
It would be useful if instead the min and max could be evaluated from the flags, unless there's some reason not to due this that I'm unaware of.

**Comment by iantheconway** [comment]
I made a script to split up my midi file into a bunch of small files, each only a few notes. Now when I run `polyphony_rnn_create_dataset` I recieve the following output: `INFO:tensorflow:Processed 500 inputs so far. Produced 432 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [20,30): 36
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 387
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 27
  [10,20): 81
  [20,30): 288
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 3645
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 49
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 451
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 441
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 4059
INFO:tensorflow:Processed 1000 inputs so far. Produced 873 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 711
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 63
  [10,20): 81
  [20,30): 585
  [30,40): 81
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 7380
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 88
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 912
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 792
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 8208

INFO:tensorflow:Processed 1500 inputs so far. Produced 945 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 1035
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 108
  [10,20): 81
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 11475
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 27
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 124
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 1376
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 1116
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 12384
INFO:tensorflow:Processed 2000 inputs so far. Produced 981 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [1,10): 18
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 1458
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 126
  [10,20): 81
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 15516
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 27
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 173
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 1827
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 1557
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 16443
INFO:tensorflow:Processed 2500 inputs so far. Produced 1026 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [1,10): 27
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 1935
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 162
  [10,20): 81
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 19485
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 36
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 227
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 2273
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 2043
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 20457
INFO:tensorflow:Processed 3000 inputs so far. Produced 1062 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [1,10): 27
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 2439
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 198
  [10,20): 81
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 23445
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 36
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 283
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 2717
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 2547
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 24453
INFO:tensorflow:Processed 3500 inputs so far. Produced 1107 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [1,10): 27
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 2826
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 18
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 234
  [10,20): 90
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 27504
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 45
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 326
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 3174
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 2934
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 28566
INFO:tensorflow:Processed 4000 inputs so far. Produced 1431 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [1,10): 27
  [10,20): 27
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 3294
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 36
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 234
  [10,20): 387
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 31185
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 54
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 383
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 3617
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 3447
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 32553
INFO:tensorflow:

Completed.

INFO:tensorflow:Processed 4245 inputs total. Produced 1629 outputs.
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_track_lengths_in_bars:
  [1,10): 27
  [10,20): 45
  [20,30): 63
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_long: 3537
INFO:tensorflow:DAGPipeline_PolyExtractor_eval_polyphonic_tracks_discarded_too_short: 36
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_track_lengths_in_bars:
  [1,10): 234
  [10,20): 567
  [20,30): 585
  [30,40): 108
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_more_than_1_program: 0
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_long: 32931
INFO:tensorflow:DAGPipeline_PolyExtractor_training_polyphonic_tracks_discarded_too_short: 72
INFO:tensorflow:DAGPipeline_RandomPartition_eval_poly_tracks_count: 412
INFO:tensorflow:DAGPipeline_RandomPartition_training_poly_tracks_count: 3833
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_eval_transpositions_generated: 3708
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_skipped_due_to_range_exceeded: 0
INFO:tensorflow:DAGPipeline_TranspositionPipeline_training_transpositions_generated: 34497`

But the resulting training_poly_tracks.tfrecord and eval_poly_tracks.tfrecord are zero bytes.

It appears as if this is not functioning as documented, unless I'm missing something.

**Comment by peatear-anthony** [comment]
Thanks, I was having the same issue. Splitting my midi files also seemed to work
