### ISSUE TITLE
basic_rnn_train: No module named lib

### ISSUE THREAD

**Issue by afuhrtrumpet** [tensorflow/magenta#102]
Getting this error when I try to run basic_rnn_train:
`Traceback (most recent call last):
  File "/home/alex/magenta/bazel-bin/magenta/models/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 36, in <module>
    import basic_rnn_encoder_decoder
  File "/home/alex/magenta/magenta/models/basic_rnn/basic_rnn_encoder_decoder.py", line 17, in <module>
    from magenta.lib import melodies_lib
ImportError: No module named lib
`

**Comment by elliotwaite** [comment]
Alex, I'm having trouble reproducing this error. Can you make sure you're synced to the latest updates. And if that doesn't help, what OS and Python version are you using?

**Comment by afuhrtrumpet** [comment]
Turns out I upgraded to the newest magenta and still had an old build under models:basic_rnn that I was trying to run.

**Comment by elliotwaite** [comment]
Ah, that's happened to me too before.
