### ISSUE TITLE
What is the role of "abc_parser" here?

### ISSUE THREAD

**Issue by shoguncao** [tensorflow/magenta#1037]
According to what I know, on Oct 30, 2017, in GIT version #927, cghawthorne add an "abc_parser" to music API.
So what I want to know is that is the "abc" is a kind of music, or some else?
Are there any README related to it ?

**Comment by superMDguy** [comment]
It looks like it's a parser for [abc notation](http://abcnotation.com/), which is kind of like MIDI, but simpler and more readable.

**Comment by cghawthorne** [comment]
That's correct, it adds support for ABC files to the NoteSequence converter. I'll update the README to mention this.

**Comment by shoguncao** [comment]
Yeah, thanks very much for your kindly reply. @superMDguy @cghawthorne
