### ISSUE TITLE
Midi decoding error: Bad header in MIDI file

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/magenta#104]
By following the tutorial, when converting midi files to note sequences, it encounters following error

`ERROR:tensorflow:Midi decoding error <type 'exceptions.TypeError'>: Bad header in MIDI file`

when running

```
bazel run //magenta/scripts:convert_midi_dir_to_note_sequences -- \
--midi_dir=$MIDI_DIRECTORY \
--output_file=$SEQUENCES_TFRECORD \
--recursive
```

No tfrecord file generated. 

I've tried many different midi files from midiworld website, the same error remains. So I guess it might not be the problem with midi files. 

Environment: 
Bazel 0.30
TensorFlow 0.9 under virtual environment

**Comment by douglaseck** [comment]
Can you attach the MIDI file?

**Comment by zuoxingdong** [comment]
[1.mid.zip](https://github.com/tensorflow/magenta/files/372681/1.mid.zip)

It can be imported and played with [onlinesequencer.net](onlinesequencer.net)

**Comment by douglaseck** [comment]
I'm not able to reproduce this.

I copied that 1.mid into /tmp/tester and ran this:

bazel run //magenta/scripts:convert_midi_dir_to_note_sequences --
--midi_dir=/tmp/tester --output_file=/tmp/test.file2
INFO: Running command line:
bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences
'--midi_dir=/tmp/tester' '--output_file=/tmp/test.file2'
/usr/local/google/home/deck/.cache/bazel/_bazel_deck/57b4fd5929bc61a3e836ee5f75cccde4/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences.runfiles/pretty_midi/pretty_midi.py:87:
RuntimeWarning: Tempo, Key or Time signature change events found on
non-zero tracks.  This is not a valid type 0 or type 1 MIDI file. Tempo,
Key or Time Signature may be wrong.
  RuntimeWarning)

I get a RuntimeWarning about the MIDI file, but that's not a problem. The
output file is stil created

ls -l /tmp/test.file2
-rw-r--r-- 1 deck eng 31414 Jul 19 18:01 /tmp/test.file2

What versions of pretty_midi and py_midi are you running?

import pretty_midi
pretty_midi.__version__
Out[9]: '0.2-pre'

What version of py_midi are you running:
import midi
midi.__file__
Out[8]:
'/usr/local/lib/python2.7/dist-packages/midi-0.2.3-py2.7.egg/midi/__init__.pyc'

**Comment by zuoxingdong** [comment]
@douglaseck 

When I enter IPython terminal under virtual environment of TensorFlow and run `import pretty_midi` and `import midi`
 
It returns `No module named pretty_midi/midi`

Does it mean that I should install these packages independently, since I am using Anaconda and when run `conda install pretty_midi` it does not find such a package to install.

**Comment by cghawthorne** [comment]
I just tried the same commands as @douglaseck above and got the same results (a populated tfrecord file). Have you done a 'git pull' recently?

The pretty_midi and midi modules are downloaded by bazel at compilation time, and bazel takes care of setting up the python import paths to be able to reference them when you run bazel targets. So you should be using the same versions as we are.

**Comment by hpssjellis** [comment]
I am having similar issues but did not see this thread until after starting my new thread at https://github.com/tensorflow/magenta/issues/107

I have a fresh installation and can't run any new mid files. The only file that runs is the example_complex.mid

**Comment by hpssjellis** [comment]
I think I have my train path incorrect I will check that out.

**Comment by rhuairahrighairidh** [comment]
I am having the same issue as @zuoxingdong.

My setup:
 - OS X 10.11
 - Python and bazel installed via homebrew
 - Tensor flow installed inside a virtualenv (named "all")
 - up to date magenta (commit d9bd761)

Here I activate the virtualenv and run the convert midi script using the midi file posted above:

    $ source ~/all/bin/activate

    (all)$ ./bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences \
    --midi_dir=/tmp/tester \
    --output_file=/tmp/tester/noteSequences.tfrecord

    /Users/ruaridh/dev/music/magenta/bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences.runfiles/pretty_midi/pretty_midi.py:87: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file. Tempo, Key or Time Signature may be wrong.
    RuntimeWarning)
    ERROR:tensorflow:Midi decoding error <type 'exceptions.TypeError'>: Bad header in MIDI file.

    (all)$ 

I'm having this error for every midi file I've tried.
The output file does seem to be generated, however it doesn't work in the next stage of creating the dataset. Apparently it can't be read (`IOError: Could not open /tmp/tester/noteSequences.tfrecord.`).

Also importing pretty_midi doesn't seem to work:

    >>> import pretty_midi
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named pretty_midi

**Comment by cghawthorne** [comment]
I just added some better logging to our midi conversion code in #112. Can the folks in this thread that were having import errors do a git pull and try again? I'd like to see what kind of error messages you're getting.

**Comment by hpssjellis** [comment]
Still getting similar errors in the basic_rnn_create_dataset everything else seems to be fine. If I run Magenta from a few commits back everything is fine on my machine.


> 
> 
> INFO: Running command line: bazel-bin/magenta/models/basic_rnn/basic_rnn_create_dataset '--input=/tmp/notesequences.tfrecord' '--train_output=/tmp/basic_rnn/sequence_examples/training_melodies.tfrecord' '--eval_output=/tmp/basic_rnn/sequence_examples/eval_melodies.tfrecord' '--eval_ratio=0'
> Traceback (most recent call last):
>   File "/home/ben/.cache/bazel/_bazel_ben/8c0953a859c6a7cebfcbd426d9e6c4a2/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_create_dataset.py", line 41, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv))
>   File "/home/ben/.cache/bazel/_bazel_ben/8c0953a859c6a7cebfcbd426d9e6c4a2/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_create_dataset.py", line 37, in main
>     basic_rnn_encoder_decoder.MelodyEncoderDecoder())
>   File "/home/ben/.cache/bazel/_bazel_ben/8c0953a859c6a7cebfcbd426d9e6c4a2/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/models/shared/melody_rnn_create_dataset.py", line 121, in run_from_flags
>     FLAGS.output_dir)
>   File "/home/ben/.cache/bazel/_bazel_ben/8c0953a859c6a7cebfcbd426d9e6c4a2/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/pipelines/pipeline.py", line 196, in run_pipeline_serial
>     if not tf.gfile.Exists(output_dir):
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 252, in Exists
>     return os.path.exists(path)
>   File "/home/ben/virtual-tf/lib/python2.7/genericpath.py", line 26, in exists
>     os.stat(path)
> TypeError: coercing to Unicode: need string or buffer, NoneType found
> ERROR: Non-zero return code '1' from command: Process exited with status 1.

**Comment by cghawthorne** [comment]
Glad to hear things are working for you now, @hpssjellis. We'll try to do better with sending out announcements when we change data generation instructions.

@zuoxingdong are you still having problems?

**Comment by zuoxingdong** [comment]
@cghawthorne  Sorry for the late reply. I've re-clone the latest repo and try again, got the following message

```
INFO: Found 1 target...
Target //magenta/scripts:convert_midi_dir_to_note_sequences up-to-date:
  bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences
INFO: Elapsed time: 0.157s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences '--midi_dir=midi_data/midis' '--output_file=midi_data/midis/notesequences.tfrecord' --recursive
INFO:tensorflow:Converting MIDI files in 'midi_data/midis/'.
WARNING:tensorflow:Could not parse MIDI file midi_data/midis/notesequences.tfrecord. It will be skipped. Error was: Midi decoding error <type 'exceptions.TypeError'>: Bad header in MIDI file.
INFO:tensorflow:Converted 0 MIDI files in 'midi_data/midis/'.
INFO:tensorflow:Could not parse 1 MIDI files.
INFO:tensorflow:Wrote 0 NoteSequence protos to 'midi_data/midis/notesequences.tfrecord'

```

Unfortunately no file is created. But I found if running commend `bazel build` first and then run `./bazel-bin/............` would be successfully generating TFRecord file.

**Comment by cghawthorne** [comment]
@zuoxingdong it looks like the only file in that directory is notesequences.tfrecord. The convert_midi_dir_to_note_sequences is meant to take in a directory of midi files and produce a tfrecord file that contains notesequences representing the data in the midi files. If you try again with a directory that contains midi files, it should work. Let me know if you have any other problems!
