### ISSUE TITLE
What kind of data is magenta/magenta/testdata/notesequences.tfrecord?

### ISSUE THREAD

**Issue by RxOxHaru** [tensorflow/magenta#1042]
I have already learned the basic model of magenta using magenta/magenta/testdata/notesequences.tfrecord. So,I want to know the contents of it.
Are there any README related to it?

Please tell me.

**Comment by cghawthorne** [comment]
It contains a test notesequence that used to be used in a unit test. It looks like it's no longer used anywhere, so we should probably just delete it.
