### ISSUE TITLE
Help wanted: Error loading notebook RL-Tuner.ipynb

### ISSUE THREAD

**Issue by hany-tawfik** [tensorflow/magenta#1072]
I am trying to run RL-Tuner.ipynb on mac and windows machines but I am getting this error message: "Unreadable Notebook: /magenta-demos/jupyter-notebooks/RL_Tuner.ipynb NotJSONError('Notebook does not appear to be JSON: u\'{\\n "cells": [\\n {\\n "cell_type": "...',) ".

I tried to run all the other jupyter notebooks and they all worked fine, except the RL-tuner which I need to use.

Kindly advice.

**Comment by adarob** [comment]
Fixed by https://github.com/tensorflow/magenta-demos/pull/38
Thanks for bringing the issue to our attention!
