### ISSUE TITLE
Error in running Onsets and Frames Colab Notebook

### ISSUE THREAD

**Issue by bardiadoosti** [tensorflow/magenta#1076]
Hi @cghawthorne
I am using your [Colab notebook](https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/magenta/onsets_frames_transcription/onsets_frames_transcription.ipynb) to test your model but it stopped working a week ago.

Error on the inference section:
UnknownError: exceptions.AttributeError: 'module' object has no attribute 'logamplitude'
	 [[Node: wav_to_spec = PyFunc[Tin=[DT_STRING], Tout=[DT_FLOAT], token="pyfunc_1"](transform_wav_data_op)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?,?,88], [?,?,88], [?], [?], [?,?,88], [?,?,229,1]], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

Thanks,
Bardia

**Comment by cghawthorne** [comment]
Thanks, should be fixed now!

**Comment by bardiadoosti** [comment]
Yeah thank you very much!
