### ISSUE TITLE
sketch-rnn preprocessing new dataset

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [tensorflow/magenta#1088]
Could you please point to appropriate references for converting new collection of svgs into the format that sketch rnn expects. That is, conversion of any new svg into desired format by following the simplified line drawings procedure mentioned here (https://github.com/googlecreativelab/quickdraw-dataset)

Thanks,
Akilesh

**Comment by hardmaru** [comment]
There’s some code I wrote in the distant past, used to convert simple SVG
paths to stroke-3 format. It uses the “svg” python library.

https://github.com/hardmaru/sketch-rnn/blob/master/utils.py

Please note that this code snippet is written just for your reference, to
give you as a starting point, and I don’t support it anymore in any
capacity whatsoever.

**Comment by akileshbadrinaaraayanan** [comment]
Thanks for this reference!

**Comment by akileshbadrinaaraayanan** [comment]
Just a quick question @hardmaru : does it also do the necessary pre-processing that is mentioned https://github.com/googlecreativelab/quickdraw-dataset

1.  Align the drawing to the top-left corner, to have minimum values of 0.
2. Uniformly scale the drawing, to have a maximum value of 255.
3. Resample all strokes with a 1 pixel spacing.
4. Simplify all strokes using the Ramer–Douglas–Peucker algorithm with an epsilon value of 2.0.

Thank you very much in advance.
