### ISSUE TITLE
Are small monophonic midi files being ignored?

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/magenta#110]
My Magneta works fine, but ignores many monophonic midi files (possibly because of mal-formed headers). I recently found out that my Magenta also ignores the magenta/testdata/example.mid file, while working fine with the complex_example.mid file. 

If I delete the complex_example.mid file leaving only the example.mid file then no melodies are found. This behaviour did not happen a few weeks ago.

Here is a text equivalent of the example.mid file

> MFile 1 2 220
> MTrk
> 0 TimeSig 4/4 24 8
> 0 Tempo 250000
> 0 KeySig 0 major
> 1 Meta TrkEnd
> TrkEnd
> MTrk
> 0 PrCh ch=1 p=0
> 0 On ch=1 n=60 v=100
> 209 On ch=1 n=60 v=0
> 220 On ch=1 n=62 v=100
> 429 On ch=1 n=62 v=0
> 440 On ch=1 n=64 v=100
> 649 On ch=1 n=64 v=0
> 660 On ch=1 n=65 v=100
> 869 On ch=1 n=65 v=0
> 880 On ch=1 n=67 v=100
> 1089 On ch=1 n=67 v=0
> 1100 On ch=1 n=69 v=100
> 1309 On ch=1 n=69 v=0
> 1320 On ch=1 n=71 v=100
> 1529 On ch=1 n=71 v=0
> 1540 On ch=1 n=72 v=100
> 1749 On ch=1 n=72 v=0
> 1750 Meta TrkEnd
> TrkEnd

Here is the text equivalent of a working monophonic midi files

> MFile 0 1 480
> MTrk
> 0 Tempo 400000
> 0 KeySig 2 major
> 0 TimeSig 4/4 48 8
> 0 Meta TrkName "Astleys Ride"
> 0 Meta Text "C:Trad"
> 0 On ch=1 n=81 v=105
> 239 Off ch=1 n=81 v=0
> 240 On ch=1 n=78 v=80
> 479 Off ch=1 n=78 v=0
> 480 On ch=1 n=74 v=105
> 959 Off ch=1 n=74 v=0
> 960 On ch=1 n=74 v=80
> 1439 Off ch=1 n=74 v=0
> 1440 On ch=1 n=74 v=95.
> .
> .
> .
> lots of note on off's (col1.mid)
> .
> .
> .
> 59999 Off ch=1 n=73 v=0
> 60000 On ch=1 n=74 v=105
> 60959 Off ch=1 n=74 v=0
> 60960 On ch=1 n=74 v=95
> 61439 Off ch=1 n=74 v=0
> 61920 Meta TrkEnd
>

**Comment by danabo** [comment]
We do filter out short melodies and melodies with few pitches.

There is not currently a command line flag to modify these settings, but you can change them in the code:
https://github.com/tensorflow/magenta/blob/master/magenta/models/shared/melody_rnn_create_dataset.py#L96

Try setting min_bars=0 and min_unique_pitches=0

**Comment by hpssjellis** [comment]
Thanks. I will try that.

**Comment by hpssjellis** [comment]
hey @danabo how do we get magenta/tensorflow to show debug errors. Is it something we request in the command line?

I want to see this output

tf.logging.debug( 'MonophonicMelody was discarded because it is too short.')

**Comment by hpssjellis** [comment]
You were right. Changing min_bars and min_unique_pitches solved the problem of the "example.mid" not getting loaded. Zero's however caused an error but ones worked. still not able to load my midi files but I think the headers are that problem.

> def extract_melodies(sequence, steps_per_beat=4, min_bars=1, min_unique_pitches=1):

P.S. I had to use yesterdays Magenta, the present repository has some issues that don't work on my computer.

**Comment by hpssjellis** [comment]
The problem was the create dataset instructions have changed AGAIN!

**Comment by danabo** [comment]
Yes the flags changed again. Sorry for breaking things. We are in the middle of making some changes to how datasets are created.
