### ISSUE TITLE
Can not download the MAPS dataset

### ISSUE THREAD

**Issue by wanghoppe** [tensorflow/magenta#1139]
Every time I tried, it had

`The webpage at ftp://ftps.tsi.telecom-paristech.fr/share/maps/ might be temporarily down or it may have moved permanently to a new web address.`

Another Question: what role does the MAPS datasets play in here? If it is used for training, then why should we have it when sampling?

**Comment by cghawthorne** [comment]
I'm not sure what the current state of the MAPS dataset is, but if you're just interested in using the model for inference, you can use our pre-trained checkpoint as described here: https://github.com/tensorflow/magenta/tree/master/magenta/models/onsets_frames_transcription#pre-trained

**Comment by conanjgz** [comment]
Hello, I was wondering if you have fixed the model without creating the full training dataset? We want to run the model locally but now we still can't do it due to lack of MAPS dataset.
Hope to hear from you soon. Thank you.
