### ISSUE TITLE
cuDNN library error after loading pre-trained model weights

### ISSUE THREAD

**Issue by firatbey** [tensorflow/magenta#1147]
I am trying to load NSynth weights and I am using tf version 1.7.0

`
from magenta.models.nsynth import utils
from magenta.models.nsynth.wavenet import fastgen

def wavenet_encode(file_path):

 # Load the model weights.
 checkpoint_path = './wavenet-ckpt/model.ckpt-200000'

 # Load and downsample the audio.
 neural_sample_rate = 16000
 audio = utils.load_audio(file_path, 
                          sample_length=400000, 
                          sr=neural_sample_rate)

 encoding = fastgen.encode(audio, checkpoint_path, len(audio))

 # Reshape to a single sound.
 return encoding.reshape((-1, 16))

# An array of n * 16 frames. 
wavenet_z_data = wavenet_encode(file_path)
`

I get the following error: "E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7103 (compatibility version 7100) but source was compiled with 7005 (compatibility version 7000). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration."

What should I do and which version of tf should I install and exactly which CUDA version do I need.

**Comment by pdagger** [comment]
I was having the same issue. I uninstalled libcudnn 7.1 (cuDNN 7.1) and installed the latest 7.0 version and it worked for me.

I am using cuda 9.0 and tensorflow-gpu 1.7.

You can download libcudnn packages from here but first you need to register as a developer:
https://developer.nvidia.com/rdp/cudnn-archive
Installation instructions here:
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html

**Comment by oscarriddle** [comment]
I have the same issue.
CentOS 7
tensorflow-gpu==1.7.0
CUDA9.0
cuDNN7.0.5

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
```
$ python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib() + "/python/_pywrap_tensorflow_internal.so")' | xargs ldd
/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
	linux-vdso.so.1 =>  (0x00007ffd3b9f7000)
	libtensorflow_framework.so => /home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so (0x00007f5927b53000)
	libcublas.so.9.0 => /home/web_server/xiaolun/cuda-9.0/lib64/libcublas.so.9.0 (0x00007f592440e000)
	libcusolver.so.9.0 => /home/web_server/xiaolun/cuda-9.0/lib64/libcusolver.so.9.0 (0x00007f591f812000)
	libcudart.so.9.0 => /home/web_server/xiaolun/cuda-9.0/lib64/libcudart.so.9.0 (0x00007f591f5a5000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f591f392000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f591f175000)
	libgomp.so.1 => /home/web_server/gcc-5.3/lib64/libgomp.so.1 (0x00007f591ef56000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f591ed4e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f591ea4b000)
	libstdc++.so.6 => /home/web_server/gcc-5.3/lib64/libstdc++.so.6 (0x00007f591e6bd000)
	libgcc_s.so.1 => /home/web_server/gcc-5.3/lib64/libgcc_s.so.1 (0x00007f591e4a7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f591e0e3000)
	/lib64/ld-linux-x86-64.so.2 (0x000055944f876000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f591d265000)
	libcudnn.so.7 => /home/web_server/xiaolun/cuda-9.0/lib64/libcudnn.so.7 (0x00007f59093f9000)
	libcufft.so.9.0 => /home/web_server/xiaolun/cuda-9.0/lib64/libcufft.so.9.0 (0x00007f5901358000)
	libcurand.so.9.0 => /home/web_server/xiaolun/cuda-9.0/lib64/libcurand.so.9.0 (0x00007f58fd3f3000)
	libnvidia-fatbinaryloader.so.384.90 => /lib64/libnvidia-fatbinaryloader.so.384.90 (0x00007f58fd1a1000)
```
