### ISSUE TITLE
No output about sequenced midi files

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/magenta#115]
Anyone else having this issue?

Everything seems to work fine except my output used to give me some indication about the midi files that have been processed, 

I used to see something like:

INFO: found 9 melodies in 3 sequences.

**Comment by hpssjellis** [comment]
Just looked at Tensorboard and I must still have something wrong. The loss is a straight line.

**Comment by danabo** [comment]
The melody info logging went away in monday's change as well. We will bring
it back soon. Sit tight.

**Comment by hpssjellis** [comment]
Last week my starting loss was about 40,000 this week my loss values are about 1.6 ?

**Comment by danabo** [comment]
I don't think we changed anything about the model architectures themselves.
Its possible that the melody dataset being created is different.

**Comment by danabo** [comment]
Regarding the original issue, the *_create_dataset.py scripts will now log how many melodies they extract from how many inputs. Additionally extra information is logged such as why melodies were discarded and statistics about melody lengths.
