### ISSUE TITLE
 ERROR: no such target '//magenta:convert_midi_dir_to_note_sequences'

### ISSUE THREAD

**Issue by oatmeal3000** [tensorflow/magenta#118]
$ sh createSequence.sh 
ERROR: no such target '//magenta:convert_midi_dir_to_note_sequences': target 'convert_midi_dir_to_note_sequences' not declared in package 'magenta' defined by /home/oatmeal/HiMusic/magenta/magenta/BUILD.
INFO: Elapsed time: 0.154s
ERROR: Build failed. Not running target.

oatmeal@oatmeal-ThinkPad-X240:~/HiMusic/magenta$ cat createSequence.sh 
MIDI_DIRECTORY=/home/oatmeal/HiMusic/MIDI/Dance 
SEQUENCES_TFRECORD=/tmp/Dance_sequences.tfrecord

bazel run //magenta:convert_midi_dir_to_note_sequences -- \
--midi_dir=$MIDI_DIRECTORY \
--output_file=$SEQUENCES_TFRECORD \
--recursive

**Comment by cghawthorne** [comment]
Hi @oatmeal3000, I think you're using an outdated set of instructions. We've changed the locations of some of our build targets recently. Please sync your git repo and try again. The up to date instructions can be seen here: https://github.com/tensorflow/magenta
