### ISSUE TITLE
How to make the initial state of RNN fixed when generate

### ISSUE THREAD

**Issue by merfii** [tensorflow/magenta#1180]
I'm doing some analysis work to evaluate and measure the creativity of Magenta drum model. I want a configuration, in which for one given primer sequence, the drum_rnn model will generate a fixed paired output sequence. I must exclude all random factors.
Is there any way to achieve such random-excluding configuration for drum-rnn model ?

**Comment by adarob** [comment]
If I understand correctly what you're asking, reducing the temperature to a very low number (e.g, 0.0001) will return the argmax. However, I think it's likely you'll find the outputs are quite boring without some randomness.
