### ISSUE TITLE
Windows 10 Ananconda Install - Bazel fails

### ISSUE THREAD

**Issue by sonicviz** [tensorflow/magenta#1183]
Hi,
I'm following the instructions on https://github.com/tensorflow/magenta for setting up a development environment. 

I've installed Bazel aok.
I've installed Anaconda aok.
I've created a tensorflow env and installed it.

But when running bazel test //magenta/...
I get 

ERROR: E:/music/magenta/magenta/magenta/models/arbitrary_image_stylization/BUILD:48:1: PythonZipper magenta/models/arbitrary_image_stylization/arbitrary_image_stylization_with_weights.zip failed (Exit -1)

INFO: Elapsed time: 1.734s, Critical Path: 0.15s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//magenta/common:beam_search_test                                     NO STATUS
//magenta/common:concurrency_test                                     NO STATUS
//magenta/common:nade_test                                            NO STATUS
etc etc 

Any clues?

**Comment by sonicviz** [comment]
Anybody?

**Comment by sh95119** [comment]
please wait a moment I'll try it on virtual machine

**Comment by sonicviz** [comment]
ty! I was looking forward to having a play with Magenta development but it's a bit of a showstopper at the moment.

**Comment by sh95119** [comment]
I'm sorry, I don't know well....
It's too irresponsible to answer that please delete and install it again.

**Comment by sonicviz** [comment]
I don't think that's the solution, If you browse the issue list other people seem to have issue with the same thing, but slightly different.

**Comment by smurthy1996** [comment]
Maybe try Docker with a preconfigured magenta image

**Comment by sonicviz** [comment]
I did that and it works but I want to do some development, so need to do a windows install afaik from the docs. Which is what I've been trying to do.

>>Did you do auto install and do you have Linux/Mac or windows?

-> Title of issue is Windows 10 Ananconda Install - Bazel fails 
I'm following the instructions on https://github.com/tensorflow/magenta for setting up a development environment.

Using Windows 10 x64 pro latest update

**Comment by sonicviz** [comment]
Nobody uses windows? Seriously?

**Comment by sonicviz** [comment]
Is there a resolution to this, or does anyone know anything about it?

Seems to be the same error as 
https://github.com/bazelbuild/bazel/issues/3803 and https://github.com/tensorflow/magenta/issues/901 but both are redirected to look at other possible solutions with no errors and are unresolved but still get closed.

**Comment by adarob** [comment]
It looks like #895 may be the fix, but it was never pulled. Looking now.

**Comment by adarob** [comment]
I just pulled in #895. Please give it a shot and re-open if it doesn't work.
