### ISSUE TITLE
Music-VAE checkpoint NotFoundError bias

### ISSUE THREAD

**Issue by Phision** [tensorflow/magenta#1188]
### What I'm trying to do
I am trying to run the code from the [music-vae colab notebook](https://colab.research.google.com/notebooks/magenta/music_vae/music_vae.ipynb) on my own machine.

### What I did
First I setup the Magenta environment as mentioned [here](https://github.com/tensorflow/magenta/blob/master/README.md). 

I copied the code from the colab notebook for the setup environment and '16-bar trio models' section to a .py file on my machine. (I commented the first few lines in the ' setup environment' part as this contains bash code. I also commented the `from google.colab import files` line as my IDE indicates this package does not exist and I could not find it anywhere to be installed either). 

I downloaded the checkpoints via a link in the colab notebook and changed the paths in the code accordingly so all files could be found (I have verified that these paths are correct).

Lastly, I have changed the `checkpoint_path_to_dir` value in the `TrainedModel` function (from `magenta.models.music_vae.trained_model`). There was no file with the name *trio_16bar_hierdec* among the checkpoints I downloaded and so I changed the path to contain *hiercat_trio_16bar_big* as this file is present among the checkpoints.

### What went wrong
After running the code I get the error:
`tensorflow.python.framework.errors_impl.NotFoundError: Key core_decoder/core_decoder_0/decoder/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]`

`NotFoundError (see above for traceback): Key core_decoder/core_decoder_0/decoder/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]`

I'm new to working with tensorflow checkpoints and so I have no idea how to resolve this *key not found* error. Could someone tell me how to resolve this issue?

### Solution
The original `checkpoint_path_to_dir` value is correct, but the correct checkpoint files cannot be obtained from the link in the colab notebook. In order to run the code, the checkpoint files mentioned in the conversation below should be added and the path set accordingly.

**Comment by Phision** [comment]
Yes, this checkpoint seems to work. Now I get an error a few lines down this is the same error, but this time for the *flat-trio_16bar* model. Could you provide the correct checkpoint for this model too?

Otherwise I would consider this issue solved. Thank you so much Adam. Perhaps this file should be added to the colab notebook.

**Comment by adarob** [comment]
Yes, it seems that the checkpoint tarball is out of date. I'll update it and then resolve this issue.

**Comment by adarob** [comment]
I've updated the tarball linked from the colab. Please reopen if you still have issues. Thanks for pointing this out!
