### ISSUE TITLE
music_vae checkpoints download

### ISSUE THREAD

**Issue by RoyLiuYihong** [tensorflow/magenta#1194]
Hi there!
When I'm playing with [music_vae](https://github.com/tensorflow/magenta/tree/master/magenta/models/music_vae), I found that the checkpoints files are only on the [Colab ](https://g.co/magenta/musicvae-colab)environment, not like other model with mag file download links. But I want to retrain the model based on existed checkpoints files, I'm just wondering if there's any chance to have a checkpoint file download link of music_vae?

**Comment by adarob** [comment]
Hi Liu!

The checkpoint downloads are linked from the top of the Colab. Let me know
if you have any issues!

-Adam
