### ISSUE TITLE
Non-zero return code '245'

### ISSUE THREAD

**Issue by oatmeal3000** [tensorflow/magenta#120]
$ sh createSequence.sh 
WARNING: /home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/external/protobuf/WORKSPACE:1: Workspace name in /home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 1 target...
Target //magenta/scripts:convert_midi_dir_to_note_sequences up-to-date:
  bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences
INFO: Elapsed time: 0.185s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences '--midi_dir=/home/oatmeal/HiMusic/MIDI/Dance' '--output_file=/home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord' --recursive
ERROR: Non-zero return code '245' from command: Process exited with status 245.

**Comment by danabo** [comment]
What is in createSequence.sh  ?

**Comment by oatmeal3000** [comment]
$ cat createSequence.sh 
MIDI_DIRECTORY=/home/oatmeal/HiMusic/MIDI/Dance 
SEQUENCES_TFRECORD=/home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord

bazel run //magenta/scripts:convert_midi_dir_to_note_sequences -- \
--midi_dir=$MIDI_DIRECTORY \
--output_file=$SEQUENCES_TFRECORD \
--recursive

**Comment by danabo** [comment]
Can you run with the --alsologtostderr flag and share the output?

So it would be
bazel run //magenta/scripts:convert_midi_dir_to_note_sequences -- \
--midi_dir=$MIDI_DIRECTORY \
--output_file=$SEQUENCES_TFRECORD \
--recursive \
--alsologtostderr

**Comment by oatmeal3000** [comment]
Outputs are the same after adding the flag.

WARNING: /home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/external/protobuf/WORKSPACE:1: Workspace name in /home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 1 target...
Target //magenta/scripts:convert_midi_dir_to_note_sequences up-to-date:
  bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences
INFO: Elapsed time: 0.264s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences '--midi_dir=/home/oatmeal/HiMusic/MIDI/Dance' '--output_file=/home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord' --recursive --alsologtostderr
ERROR: Non-zero return code '245' from command: Process exited with status 245.

**Comment by danabo** [comment]
Hmm I am still not sure what is producing the error code.

Can you do two things?
Run the binary without bazel (just run the command that bazel prints in the INFO statement). Just to be sure this is not related to bazel.

bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences '--midi_dir=/home/oatmeal/HiMusic/MIDI/Dance' '--output_file=/home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord' --recursive --alsologtostderr

Second thing is to see if importing tensorflow works. From doing a bit of googling this sounds like an issue with your tensorflow install. You can just delete everything in convert_midi_dir_to_note_sequences.py and replace it with one line: "import tensorflow as tf"
Build and run the binary again.

**Comment by oatmeal3000** [comment]
It turned out that it is due to the corruption of tensorflow installation.  Previously it had been successfully installed, but somehow it cannot work any more, then I reinstalled tensorflow and the problem just disappear.
Thanks very much!!
