### ISSUE TITLE
Image_Stylization training issue: no imagenet-2012-tfrecord

### ISSUE THREAD

**Issue by SimpleXP** [tensorflow/magenta#1203]
Hi,
I'm new to tensorflow and my question might sounds silly. But I do hope someone here can help with this issue.

I follow the instruction in "image_stylization" and prepare my style data, everything is OK so far. When I try to train on my own style data, I use "image_stylization_train" with "--imagenet_data_dir" parameter. The question is I don't have "imagenet-2012-tfrecord"

I follow the instruction here https://github.com/tensorflow/models/tree/master/research/inception#getting-started
to download imagenet dataset and build the tfrecord, but what I got is something like this: train-0XXXX-of_01024. There is no file named imagenet-2012-tfrecord.
In the instruction, it says that the train-0XXXX-of-01024 file is of tfrecord format, but when I use this as input of "--imagenet_data_dir" and run the train script, it said: /tmp/imagenet-2012-tfrecord does not exist!

I'm a little bit confuse.
Could anyone help me with this? Thanks in advance!

**Comment by brunoaibanez** [comment]
Hey @SimpleXP, were you able to solve the problem? I was trying to convert Imagenet Raw Data to TF-Record but I am struggling with it. Let me know!
