### ISSUE TITLE
[Android - image_stylization ]There is no Input_node in pb files

### ISSUE THREAD

**Issue by JangminSon** [tensorflow/magenta#1209]
I'm trying to make my own custom models with image-stylization for Android application.
I've made my Models with

```
$ image_stylization_train \
      --train_dir=/tmp/image_stylization/run1/train
      --style_dataset_file=/tmp/image_stylization/style_images.tfrecord \
      --num_styles=<NUMBER_OF_STYLES> \
      --vgg_checkpoint=/path/to/vgg_16.ckpt \
      --imagenet_data_dir=/path/to/imagenet-2012-tfrecord
```

And model was working fine with transform code
```
image_stylization_transform \
      --num_styles=10 \
      --checkpoint=multistyle-pastiche-generator-monet.ckpt \
      --input_image=photo.jpg \
      --which_styles="{0:0.1,1:0.1,2:0.1,3:0.1,4:0.1,5:0.1,6:0.1,7:0.1,8:0.1,9:0.1}" \
      --output_dir=/tmp/image_stylization/output \
      --output_basename="all_monet_styles"
```

So I made pb files via Tensorflow-freeze_graph.py

at first, i used following code for test 

> ...
> private static final String INPUT_NODE = "input";
> ...

but it occurs error like
> java.lang.IllegalArgumentException: No Operation named [input_image] in the Graph

So I thought I would done something wrong and trying to find out what is name for input_node with 

> tensorflow/tools/graph_transforms:summarize_graph

and it shows 
```
No inputs spotted.
No variables spotted.
Found 1 possible outputs: (name=transformer/expand/conv3/conv/Sigmoid, op=Sigmoid) 
Found 1703624 (1.70M) const parameters, 0 (0) variable parameters, and 0 control_edges
```
Did I doing something wrong?
Or does this code (image_stylization_train) doesn't gave any input_node or something

Please Help me out with this problem

Thanks.

**Comment by JangminSon** [comment]
I solve This Errors

**Comment by aurelhubert** [comment]
@JangminSon Do you have any details about how you solved it? It could help, thank you!

**Comment by shekargoud26** [comment]
> I solve This Errors

@JangminSon Can you please tell how you solved the error? 
I'm facing the same issue and would like your help.
Thanks :)
