### ISSUE TITLE
No random single note output when primer_midi or primer_melody not supplied

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/magenta#121]
Latest change only works if either a primer_midi or primer_melody is supplied

Give this error if neither are supplied, instead of starting the melody with a random note

 

>    bpm = (primer_sequence.tempos[0].bpm if primer_sequence.tempos
> AttributeError: 'NoneType' object has no attribute 'tempos'
>

**Comment by danabo** [comment]
I didn't know that we allowed no primer to be given previously, but you are right. This is the code that picked a random primer:
https://github.com/tensorflow/magenta/blob/4c0050aee5f2bac3f95041a42074cfb6054071c2/magenta/models/shared/melody_rnn_generate.py#L101

We can add this option back in.

**Comment by hpssjellis** [comment]
Sounds good. Any idea of your time frame for the fix?

**Comment by danabo** [comment]
Should be a small change, so early next week seems reasonable.

**Comment by hpssjellis** [comment]
@danabo I am testing a solution to this.

**Comment by danabo** [comment]
I created a PR that will fix both issues - bpm flag and no primer is allowed. This was a bit more complicated than I was anticipated, so I thought it would be easier if I fix both in one PR.

**Comment by hpssjellis** [comment]
Sounds great Daniel. I will close my PR.

**Comment by hpssjellis** [comment]
Solved by @danabo PR 

https://github.com/tensorflow/magenta/pull/128
