### ISSUE TITLE
Docker image with GPU

### ISSUE THREAD

**Issue by angad9** [tensorflow/magenta#1218]
Is there a way to use the tensorflow/magenta docker image with nvidia GPUs? Once I run the image, I can run various magenta commands like nsynth_generate, but none of them seem to be finding / using the GPUs. Is there some configuration that I'm missing? Or is it not possible to use GPUs via docker?

**Comment by cghawthorne** [comment]
See discussion in #775. It should be possible, but I haven't tried it myself. Let us know if you get it working!

**Comment by xamuel** [comment]
I tried to modify the DockerFile line 1  FROM tensorflow/tensorflow:latest-devel to FROM tensorflow/tensorflow:latest-devel-gpu but it still running on CPU
