### ISSUE TITLE
Enhancement Request: Conversion from old training runs to new training runs when possible

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/magenta#122]
When a major change is made to [melody_rnn_train.py](https://github.com/tensorflow/magenta/blob/master/magenta/models/shared/melody_rnn_train.py) which makes previous saved training data broken, a conversion program is made to convert (if possible) old data to the new format.

Example: I have several saved training runs from about a month ago which are now broken. I thought it was just the changed directory in the checkpoint file but there must be more to it. An example zipped file is at 

https://github.com/hpssjellis/magenta-music-layer-research/blob/master/beauty-and-beats-all-keys/midi12-layer25-train200.zip

or

https://github.com/hpssjellis/magenta-music-layer-research/blob/master/re-train-tests/many-layer50-train8000.zip

Not a big deal while Magenta is so young (My files were very quick to make) but something to keep in mind for future changes to training and evaluation data. Could be very frustrating with saved and broken 50000 loop training runs.

**Comment by cghawthorne** [comment]
Agreed that this will become more important as Magenta develops more complex models. We'll definitely keep it in mind!
