### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hwH5Ne/IPython/

### ISSUE THREAD

**Issue by pchao6** [tensorflow/magenta#1231]
Hello, the problem appears while I use "pip install magenta-gpu":
The detailed problem:
Complete output from command python setup.py egg_info:
    
    IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Beginning with IPython 6.0, Python 3.3 and above is required.
    
    See IPython `README.rst` file for more information:
    
        https://github.com/ipython/ipython/blob/master/README.rst
    
    Python sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0) detected.
    
    
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hwH5Ne/IPython/
    ----------------------------------------

**Comment by Togemon** [comment]
How did you solve it?

**Comment by kmylavar25** [comment]
Hey! Could you share your solution as to how you got this error resolved?
