### ISSUE TITLE
Training on the NSynth Dataset

### ISSUE THREAD

**Issue by angad9** [tensorflow/magenta#1234]
1) I think the command given on the nsynth model readme has a typo. It should be wavenet:train rather than wavenet/train. 

2) When I try training the model, I get the following error:
```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.FailedPreconditionError'>, ../../train/records/nsynth-train.tfrecord; Not a directory
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](TFRecordReaderV2, input_producer/FIFOQueueV2)]]
```
Any ideas why? The .tfrecord file is definitely present. Do I need to extract it or process it in someway? 

3) Is there a way to continue training from a checkpoint? I want to potentially fine-tune the model on some new data. 

I would be really appreciate any help here!

**Comment by adarob** [comment]
Have you tried to use the full path instead of the relative path?

**Comment by angad9** [comment]
Full path worked. There were other issues though.. As pointed out in https://github.com/tensorflow/magenta/issues/853
