### ISSUE TITLE
Pip installation fails due to librosa dependency

### ISSUE THREAD

**Issue by Navinprashath** [tensorflow/magenta#1252]
Hi,

I'm trying to install the magenta-gpu but when I did a pip install magenta-gpu:

**librosa 0.6.2 has requirement joblib>=0.12, but you'll have joblib 0.11 which is incompatible.**

**Comment by ho9science** [comment]
It helps me for my windows env

**Comment by cghawthorne** [comment]
This is addressed by #1251, but we still need to create a new version of the pip package.

**Comment by cghawthorne** [comment]
Pip package for release 0.3.11 is now available.

**Comment by Navinprashath** [comment]
Pip package 0.3.12 resolves this problem

**Comment by cghawthorne** [comment]
Yeah, we had a pypi issue with 0.3.11, so I've deleted it and published again as 0.3.12. It should all be working now!
