### ISSUE TITLE
Is there any pre-trained models for Multi-track VAE?

### ISSUE THREAD

**Issue by howardlau1999** [tensorflow/magenta#1262]
Could anyone please provide pre-trained models for hier-multiperf_vel_1bar_big_chords and hier-multiperf_vel_1bar_mel_chords which we can continue training?

**Comment by iansimon** [comment]
There's no "big" model available at this time, but there is a hier-multiperf_vel_1bar_med_chords model that's used by the Multitrack MusicVAE notebook: https://colab.research.google.com/notebooks/magenta/music_vae/multitrack.ipynb

The checkpoint files are here:
https://storage.cloud.google.com/download.magenta.tensorflow.org/models/music_vae/multitrack/model_chords_fb64.ckpt.data-00000-of-00001
https://storage.cloud.google.com/download.magenta.tensorflow.org/models/music_vae/multitrack/model_chords_fb64.ckpt.index
https://storage.cloud.google.com/download.magenta.tensorflow.org/models/music_vae/multitrack/model_chords_fb64.ckpt.meta
