### ISSUE TITLE
pip install magenta-gpu in Centos

### ISSUE THREAD

**Issue by lisiping0817** [tensorflow/magenta#1266]
![image](https://user-images.githubusercontent.com/41105367/44523124-670a3080-a70b-11e8-988b-b54e9745cf33.png)

**Comment by lisiping0817** [comment]
how can i slove this problem  thank you

**Comment by cghawthorne** [comment]
That looks like an issue with your Python distribution. I'd recommend going through the manual installation steps in our main README and installing a separate conda environment: https://github.com/tensorflow/magenta#manual-install

**Comment by lisiping0817** [comment]
thank you i slove this problem  but there is new problem
