### ISSUE TITLE
Problem with cost computation

### ISSUE THREAD

**Issue by HomaDa** [tensorflow/magenta#1267]
I have some problem in understanding what is actually happening in cost computation, in MusicVAE._compute_model_loss() (in base_model.py):
The cost, as expected, consists of two part: kl_cost and reconstruction_loss.  The kl-cost is computed by computing kl-divergence  between prior(p_z) and posterior(q_z), posterior being the output of encoder after passing input_sequence through it:
q_z = self.encode(input_sequence, x_length, control_sequence) 

reconstruction_loss should also be computed by comparing input and output, as done in this way:
self.decoder.reconstruction_loss( x_input, x_target, x_length, z, control_sequence)

Sum of these two terms are the total cost.
The confusing part is that the input used in computing these two terms are different: kl_cost is computed by using "input_sequence" as the input, while the reconstruction_loss is computed by feeding the network with  "x_input", which is defined in line 238 as:

x_input = tf.pad(output_sequence[:, :max_seq_len - 1], [(0, 0), (1, 0), (0, 0)])

which uses the output.

-----
If this is a variational autoencoder, I expected the input and output to be the same. However, it might be designed this way to be applicable in other cases. but when I was just trying to run the code, I had some problem figuring out what is going there...

**Comment by adarob** [comment]
Sorry for the confusion. 

The purpose of the different `input_sequence` and `output_sequence` is to allow this to be used effectively as a Seq2Seq model instead of a VAE. The `input_sequence` is what is encoded and the `output_sequence` is what is decoded. In all of the current configs, these are identical.
