### ISSUE TITLE
magenta/magenta/models/image_stylization/

### ISSUE THREAD

**Issue by lisiping0817** [tensorflow/magenta#1279]
![image](https://user-images.githubusercontent.com/41105367/44827987-6a8c4300-ac48-11e8-92dc-f8878f1ee00f.png)
  

i think this code maybe have mistake   so we cannot  import name console_entry_point.
so  i want to know the truth   thank you

**Comment by lisiping0817** [comment]
![image](https://user-images.githubusercontent.com/41105367/44828095-dbcbf600-ac48-11e8-9e64-fd7873ca3b62.png)

**Comment by lisiping0817** [comment]
code in the image stylization create dataset

**Comment by cghawthorne** [comment]
Yes, it looks like it should have a `console_entry_point` method similar to the other commands in that directory. Can you try adding that and send a pull request?

**Comment by lisiping0817** [comment]
thank you
