### ISSUE TITLE
The reconstruction from sequence_proto_to_midi_file is not accurate?

### ISSUE THREAD

**Issue by Carbonil** [tensorflow/magenta#1287]
I am doing something like this:
`encoded=midi_file_to_sequence_proto('input.mid')`
`decoded=sequece_proto_to_midi_file(a,'output.mid')`

But the reconstruction is not 100% accurate. what i am missing?
The input file size was 18.1 KB but the output file  is 13.9 KB. What this conversation is missing actually?

I will be grateful for any kind of help.Thanks

**Comment by cghawthorne** [comment]
It could be metadata in the MIDI, we don't support all of that. Are there errors in reconstruction that you see other than the file size changing?

**Comment by Carbonil** [comment]
Oh.That's great.I thought that too.Out of 20, i got a bit of error reconstruction in 1 MIDI file.
But can you please guide me to solve this problem,
"How could i vectorize the NoteSequence TFRecord file for feeding into my own neural network and again reconstruct  the midi from the vectorized form. I am using a Variational Autoencoder to train my MIDI file. "

I will be grateful if you just guide me on this issue.

**Comment by cghawthorne** [comment]
You might want to take a look at our Performance RNN encoding: https://g.co/magenta/performance-rnn
