### ISSUE TITLE
UnicodeDecodeError  in  MusicVAE 

### ISSUE THREAD

**Issue by ericosmic** [tensorflow/magenta#1330]
I try to run the interpolate mode in music_ave model to generate example,  but it is always produce unicodedecode error 
![2018-11-01 18-26-39](https://user-images.githubusercontent.com/35327931/47846950-ae482800-de04-11e8-8358-f0a8f3c0b446.png)
Is it about the my midi example wrong.  I selected two midi exmaple played with three tracks(piano, bass, and drum) and 4 bars long. who know what is wrong about it?

**Comment by adarob** [comment]
It seems like it's having trouble reading your MIDI file. If you are
willing to send it over, I can have a look.

**Comment by adarob** [comment]
@ericosmic did you solve this problem? Unfortunately your attachments weren't included.

**Comment by mapleee** [comment]
I came across the same problem. I also got the two midi file from generating model, and as I fed them into the interpolate model, it started to produce UnicodeDecodeError

**Comment by eps696** [comment]
@mapleee UnicodeDecodeError seems to be generic message for any kind of wrong/missing data. check the Traceback messages above it for the details of problem.

**Comment by adarob** [comment]
This is an incompatibility issue with Python3. I have a solution and I will patch this later today.
