### ISSUE TITLE
MAESTRO midi only dataset incomplete?

### ISSUE THREAD

**Issue by maxisawesome** [tensorflow/magenta#1342]
When I download maestro-v1.0.0-midi.zip from [here](https://magenta.tensorflow.org/datasets/maestro), the only data is from 2009. The other years have files but they are empty. This isn't intentional, is it?

**Comment by cghawthorne** [comment]
Oops, sorry about that. Will fix shortly!

**Comment by cghawthorne** [comment]
Updated the [zip file](https://storage.googleapis.com/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0-midi.zip). Correct sha256 is `f620f9e1eceaab8beea10617599add2e9c83234199b550382a2f603098ae7135`. Will update the website with that info in a bit.

**Comment by maxisawesome** [comment]
Awesome - thanks a lot!
