### ISSUE TITLE
How to control piano genie with a novation launchpad mini

### ISSUE THREAD

**Issue by JBX028** [tensorflow/magenta#1343]
Hi,

Is there a way to generate live music with a device like this : https://novationmusic.com/launch/launchpad-mini

I would like to buy such device and similarly to the 8 pads keyboard visible in the [video](https://www.youtube.com/watch?v=_QlzbodchAc), control the music but I would like first know if this is possible without too much complexity.

Thanks in advance

**Comment by chrisdonahue** [comment]
Thank you for your interest. This should be possible through software such as [OSCulator](https://osculator.net/) and [MidiStroke](http://charlie-roberts.com/midiStroke/), which can both be used to bind MIDI events from the launchpad to virtual keyboard strokes on your computer.

You can map the MIDI events for a row of your launchpad controller to keyboard keys [1-8] and then use them to control our [web demo](https://tensorflow.github.io/magenta-demos/piano-genie/).

If you have a MIDI keyboard lying around, you might want to test this setup before purchasing a launchpad.

Let me know if you need any additional help.

**Comment by JBX028** [comment]
Hi,
Thanks a lot. I will explore these options and see if I will invest or not.

Regards,
