### ISSUE TITLE
onset and frames: help creating dataset

### ISSUE THREAD

**Issue by kiddungy** [tensorflow/magenta#1355]
Im trying to create my own dataset/ tfrecord i have finally downloaded the MAPS database but I keep getting errors when trying to create the tfrecord no matter how much i tweek it right now Im getting the "UnicodeDecodeError: 'utf-8' code cant decode byte 0xff in position 12: start byte"

if i can just manage to create the dataset i have ideas for the rest of my project.

**Comment by adarob** [comment]
This should now be fixed in v0.3.18
