### ISSUE TITLE
Modify MIDI/NoteSequence objects

### ISSUE THREAD

**Issue by RootofalleviI** [tensorflow/magenta#1359]
I'm experiencing many exceptions when running Melody RNN, such as MultipleTimeSignatureException and ImplicitTempoChangeException. Is there a way to fix this from code? If not, how can I modify MIDI/NoteSequence objects to get rid of the tempo change or signature change?

Here is a sample NoteSequence segment that results in MultipleTimeSignatureException:

ticks_per_quarter: 256
time_signatures {
  numerator: 4
  denominator: 4
}
time_signatures {
  numerator: 2
  denominator: 4
}
key_signatures {
}
key_signatures {
  time: 151.0
  key: A
}
tempos {
  qpm: 120.0
}
notes {
  pitch: 69
  velocity: 56
  start_time: 2.0
  end_time: 2.248046875
  program: 40
}
notes {
  pitch: 69
  velocity: 43
  start_time: 2.375
  end_time: 2.443359375
  program: 40
}
notes {
  pitch: 69
  velocity: 51
  start_time: 2.5
  end_time: 2.625
  program: 40
}
notes {
  pitch: 72
  velocity: 50
  start_time: 2.625
  end_time: 2.75
  program: 40
}
notes {
  pitch: 71
  velocity: 46
  start_time: 2.75
  end_time: 2.875
  program: 40
}
notes {
  pitch: 69
  velocity: 44
  start_time: 2.875
  end_time: 3.0
  program: 40
}
notes {
  pitch: 76
  velocity: 61
  start_time: 3.0
  end_time: 3.49609375
  program: 40
}
notes {
  pitch: 64
  velocity: 37
  start_time: 3.5
  end_time: 3.748046875
  program: 40
}
notes {
  pitch: 81
  velocity: 54
  start_time: 4.0
  end_time: 4.248046875
  program: 40
}
notes {
  pitch: 81
  velocity: 44
  start_time: 4.375
  end_time: 4.443359375
  program: 40
}
notes {
  pitch: 81
  velocity: 48
  start_time: 4.5
  end_time: 4.625
  program: 40
}
notes {
  pitch: 82
  velocity: 49
  start_time: 4.625
  end_time: 4.75
  program: 40
}
notes {
  pitch: 81
  velocity: 48
  start_time: 4.75
  end_time: 4.875
  program: 40
}
notes {
  pitch: 79
  velocity: 45
  start_time: 4.875
  end_time: 5.0
  program: 40
}
total_time: 5.0
control_changes {
  control_number: 91
  control_value: 49
  program: 40
}
control_changes {
  control_number: 10
  control_value: 38
  program: 40
}
control_changes {
  program: 40
}
control_changes {
  control_number: 32
  program: 40
}
source_info {
  encoding_type: MIDI
  parser: PRETTY_MIDI
}

**Comment by RootofalleviI** [comment]
Oops I figured it out.
Try this:
```
from magenta.music import sequences_lib
splitted = sequences_lib.split_note_sequence_on_time_changes(<seq>) # a list of node seqs
```

**Comment by hedonistrh** [comment]
Hey @RootofalleviI, I would like to ask that how we can see details of _NoteSequence segment_ :) Thanks for help ^^
