### ISSUE TITLE
Error in Onsets and Frames Colab Notebook

### ISSUE THREAD

**Issue by LegendFC** [tensorflow/magenta#1366]
Hi @cghawthorne
I am using your Colab notebook to test your model but it stopped working.

Error on the model initialization section:
NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.

Thanks

**Comment by adarob** [comment]
Sorry about this. The fix should be pushed by end of day tomorrow. Please reopen if it is still broken on Friday.
