### ISSUE TITLE
Where to get model.ckpt?

### ISSUE THREAD

**Issue by ljvmiranda921** [tensorflow/magenta#1369]
I'm trying to follow the instructions for arbitrary style transfer [here](https://github.com/tensorflow/magenta/tree/master/magenta/models/arbitrary_image_stylization#stylizing-an-image-using-a-pre-trained-model), and it says that I need to download a pretrained model from this [link](https://storage.googleapis.com/download.magenta.tensorflow.org/models/arbitrary_style_transfer.tar.gz). However, what I get is a `tar.gz` file and whenever I extract it, I only get the following files:

```
$ tar xvzf arbitrary_style_transfer.tar.gz
$ ls arbitrary_style_transfer
model.ckpt-data-00000-of-000001 model.ckpt.index model.ckpt.meta
```

Which one here should I use?

**Comment by ljvmiranda921** [comment]
Okay, solved. So  you don't really need to have a `model.ckpt` file. What I do is that I passed the argument `arbitrary_style_transfer/model.ckpt` into `--checkpoint` and it works. No need to have the `ckpt` file

**Comment by nimblenitin** [comment]
Pppp

Regards,
Nitin Naidu

**Comment by pjmartorell** [comment]
Hi, for me it's not working,it's not doing anything. You have to load the pre-trained model somehow. Any clue on how to load the pre-trained model?

Thanks

**Comment by ljvmiranda921** [comment]
@pjmartorell do you have the `arbitrary_style_transfer.tar.gz` file?

**Comment by pjmartorell** [comment]
yes, but it's not ckpt file, it's an index, a meta and data. How do you pass the .ckpt?

**Comment by ljvmiranda921** [comment]
Yes, same thing with me, if your directory structure looks like this:

I suggest you untar it inside a `checkpoint` directory such that (note, I forgot the actual file names):

```
arbitrary_style_transfer_with_weights.py
checkpoint/model.ckpt.data-00000-of-00001
checkpoint/model.meta
checkpoint/model.index
```

Then pass `--checkpoint=checkpoint/model.ckpt` to the arguments. As far as I know it should already load your model automatically

**Comment by pjmartorell** [comment]
Thanks! seems that now it actually loads the model. Anyway, it's not producing any output given the styles and contents directories. Did it work for you?

**Comment by pjmartorell** [comment]
This is my output:
```
2018-12-01 15:52:01.205088: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /home/pjmartorell/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/arbitrary_image_stylization/arbitrary_image_stylization_build_model.py:158: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:loading latest checkpoint file: checkpoint/model.ckpt
INFO:tensorflow:Restoring parameters from checkpoint/model.ckpt
```

**Comment by ljvmiranda921** [comment]
Hi @pjmartorell ,

I usually include the actual file in `content_images_paths` and `style_images_paths`. So what I'd probably do is:

```shell
arbitrary_image_stylization_with_weights \
  --maximum_styles_to_evaluate=1000 --checkpoint=checkpoint/model.ckpt \
  --output_dir=images/output/  \
  --style_images_paths=images/style_images/my_style.jpg \  # Put actual style
  --content_images_paths=images/content_images/my_content.jpg \ # Put actual image
  --image_size=256 \
  --content_square_crop=False \
  --style_image_size=256 \
  --style_square_crop=False \
  --logtostderr
```

If you wish to style transfer multiple contents or styles, just use `*.jpg`

**Comment by pjmartorell** [comment]
Thanks for your help! it works when when you set an specific content and style image path. The example command in the README is misleading and not working. Looking at the implementation and the name of the parameters (`style_images_paths` and `content_images_paths`) I understood it was accepting multiple paths or a directory. There are some things to improve, definitely. Thanks!

**Comment by ljvmiranda921** [comment]
I wonder why @vdumoulin was assigned in this Issue, shall I reopen this one again? cc: @adarob

**Comment by padmareddy21** [comment]
> Okay, solved. So you don't really need to have a `model.ckpt` file. What I do is that I passed the argument `arbitrary_style_transfer/model.ckpt` into `--checkpoint` and it works. No need to have the `ckpt` file
Hoe to pass arbitrary_style_transfer/model.ckpt to checkpoint
