### ISSUE TITLE
MusicVAE: Can't load my own checkpoint files

### ISSUE THREAD

**Issue by mapleee** [tensorflow/magenta#1371]
I just use my own midi dataset to train the model, and get the checkpoint files. I put three files into a file folder as the picture showing below, and then zip them into the format of .tar.
![image](https://user-images.githubusercontent.com/24646295/49325435-46107180-f57d-11e8-842e-4a9774a98223.png)
However, when I start to use this file to generate clips, I encounter the Data loss bug:
![image](https://user-images.githubusercontent.com/24646295/49325466-bf0fc900-f57d-11e8-8b68-bcffb76eb4fd.png)

**Comment by aletote** [comment]
How did you solve this? I dont even know how to .tar without tar.gz those files?

**Comment by adarob** [comment]
You do not need to tar them. You can just point to the path of the checkpoint without the suffix (e.g., model.ckpt-1683).
