### ISSUE TITLE
arbitrary_image_stylization code for distillation

### ISSUE THREAD

**Issue by reiinakano** [tensorflow/magenta#1373]
Would you be interested in adding the scripts I used for distillation (stylenet inceptionv3->mobilenet) + another thing i'm working on where i replace the transformnet conv2d layers with separable_conv2d?

Right now i haven't uploaded them publicly since they're in pretty messy colab notebooks but I could clean it up and have something like `distill_arbitrary_image_stylization_to_mobilenet.py`. This way, other people with more resources than me could run them (I can only do around 80K training steps in a few days with Google Colab) and probably get better models. If not, then I'll probably just dump the notebooks as is in my repo.

**Comment by adarob** [comment]
This would be great to have, thanks!
