### ISSUE TITLE
Onsets and Frames in local jupyter notebook: Tensor Key not in MAESTRO Checkpoint

### ISSUE THREAD

**Issue by MRGLabs** [tensorflow/magenta#1375]
When restoring a local copy of 'model.ckpt-maestro' (downloaded from https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/maestro_checkpoint.zip) I encounter the following error:

```
with tf.Graph().as_default():
  examples = tf.placeholder(tf.string, [None])

  num_dims = constants.MIDI_PITCHES

  batch, iterator = data.provide_batch(
      batch_size=1,
      examples=examples,
      hparams=hparams,
      is_training=False,
      truncated_length=0)

  model.get_model(batch, hparams, is_training=False)

  session = tf.Session()
  saver = tf.train.Saver()
  saver.restore(session, acoustic_checkpoint)
```

> NotFoundError: Key frame/bidirectional_rnn/bw/lstm_cell/bias not found in checkpoint

A quick read of the checkpoint variables yields the following list of tensor names (numbers on left are pandas dataframe index):

> 93                                  beta1_power
> 15                                  beta2_power
> 85                frame/activation_probs/biases
> 89           frame/activation_probs/biases/Adam
> 95         frame/activation_probs/biases/Adam_1
> 67               frame/activation_probs/weights
> 101         frame/activation_probs/weights/Adam
> 71        frame/activation_probs/weights/Adam_1
> 34                   frame/conv0/BatchNorm/beta
> 114             frame/conv0/BatchNorm/beta/Adam
> 45            frame/conv0/BatchNorm/beta/Adam_1
> 5             frame/conv0/BatchNorm/moving_mean
> 97        frame/conv0/BatchNorm/moving_variance
> 46                          frame/conv0/weights
> 125                    frame/conv0/weights/Adam
> 16                   frame/conv0/weights/Adam_1
> 37                   frame/conv1/BatchNorm/beta
> 68              frame/conv1/BatchNorm/beta/Adam
> 22            frame/conv1/BatchNorm/beta/Adam_1
> 3             frame/conv1/BatchNorm/moving_mean
> 14        frame/conv1/BatchNorm/moving_variance
> 58                          frame/conv1/weights
> 21                     frame/conv1/weights/Adam
> 13                   frame/conv1/weights/Adam_1
> 115                  frame/conv2/BatchNorm/beta
> 90              frame/conv2/BatchNorm/beta/Adam
> 120           frame/conv2/BatchNorm/beta/Adam_1
> 91            frame/conv2/BatchNorm/moving_mean
> 98        frame/conv2/BatchNorm/moving_variance
> 118                         frame/conv2/weights
>                          ...                   
> 126                 velocity/conv0/weights/Adam
> 11                velocity/conv0/weights/Adam_1
> 42                velocity/conv1/BatchNorm/beta
> 83           velocity/conv1/BatchNorm/beta/Adam
> 48         velocity/conv1/BatchNorm/beta/Adam_1
> 56         velocity/conv1/BatchNorm/moving_mean
> 122    velocity/conv1/BatchNorm/moving_variance
> 117                      velocity/conv1/weights
> 124                 velocity/conv1/weights/Adam
> 53                velocity/conv1/weights/Adam_1
> 12                velocity/conv2/BatchNorm/beta
> 64           velocity/conv2/BatchNorm/beta/Adam
> 110        velocity/conv2/BatchNorm/beta/Adam_1
> 39         velocity/conv2/BatchNorm/moving_mean
> 61     velocity/conv2/BatchNorm/moving_variance
> 75                       velocity/conv2/weights
> 25                  velocity/conv2/weights/Adam
> 41                velocity/conv2/weights/Adam_1
> 6                        velocity/fc_end/biases
> 119                 velocity/fc_end/biases/Adam
> 36                velocity/fc_end/biases/Adam_1
> 31                      velocity/fc_end/weights
> 43                 velocity/fc_end/weights/Adam
> 96               velocity/fc_end/weights/Adam_1
> 84             velocity/onset_velocities/biases
> 20        velocity/onset_velocities/biases/Adam
> 63      velocity/onset_velocities/biases/Adam_1
> 92            velocity/onset_velocities/weights
> 49       velocity/onset_velocities/weights/Adam
> 78     velocity/onset_velocities/weights/Adam_1
> Length: 127, dtype: object

Clearly there are no 'bidirectional_rnn' tensors in this model, but these are needed to support  
>  magenta.models.onsets_frames_transcription.model.get_model

Is there a different (updated) checkpoint model, that supports bidirectional autoencoding?

Any other options than training a new model from scratch?

**Comment by hollyhook** [comment]
I encountered the same issue. The pretrained model at https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/checkpoint.zip still works, but I guess it is not the MAESTRO dataset

**Comment by adarob** [comment]
You need to upgrade to 0.4.0 (`pip install --upgrade magenta`) to get the new version of the model.

**Comment by MRGLabs** [comment]
That did the trick, many thanks @adarob !

**Comment by nkjulia** [comment]
> to upgrade to 0.4

hey, i had the same issue when i use the pretrained model to evaluate on the test dataset (detailed in https://github.com/magenta/magenta/issues/1920)

 the magenta version is 2.1.3 and tensorflow version is  2.4.1 , can u tell me how to solve such issue?
