### ISSUE TITLE
Attribute latent vector Z MusicVAE

### ISSUE THREAD

**Issue by Gnefi** [tensorflow/magenta#1381]
Hello everyone!

How can I get Attribute Latent Vector Z to modify music sample?
I red the paper about MusicVAE Project and I focalized on Section C about Attribute Definition. About you're list of definitions.... How can I get those (for example you're Attribute).
Waiting for answer.

Thank you!

**Comment by adarob** [comment]
Sorry @Gnefi but I never got around to publishing this portion of the code. However, it should be fairly straightforward to reproduce these particular functions in Python. Please reopen if you have specific questions about those functions.
