### ISSUE TITLE
importError: No module named magenta.models.score2perf

### ISSUE THREAD

**Issue by cuckooinc** [tensorflow/magenta#1393]
after installing magenta by using the development environment setup. I ran the following commands in my bash terminal 
python setup.py develop
PROBLEM=score2perf_maestro_language_uncropped_aug
BUCKET=xy
PROJECT=yz

PIPELINE_OPTIONS=\
"--runner=DataflowRunner,"\
"--project=${PROJECT},"\
"--temp_location=gs://${BUCKET}/tmp,"\
"--setup_file=/mus/lib/python2.7/site-packages/apache_beam/examples/complete/juliaset/setup.py"

python /magenta/magenta/tensor2tensor/t2t_datagen.py --data_dir=gs://${BUCKET}/datagen --problem=${PROBLEM} --pipeline_options="${PIPELINE_OPTIONS}" ----alsologtostderr

It is giving error  
ImportError: No module named magenta.models.score2perf 
Complete error is in attached document
[transformer error.txt](https://github.com/tensorflow/magenta/files/2713412/transformer.error.txt)

**Comment by iansimon** [comment]
The setup.py location you should point to is wherever you cloned the magenta git repo; in other words, the same directory from which you ran "python setup.py develop".
