### ISSUE TITLE
The 'tensorflow>=1.12.0' distribution was not found and is required by magenta

### ISSUE THREAD

**Issue by Dan1900** [tensorflow/magenta#1395]
I use this command install tensorflow:
pip install tensorflow-gpu
but  the magenta seems can't find it .

**Comment by adarob** [comment]
Which OS?

**Comment by ys23** [comment]
Hello
In addition to install tensorflow, you may have to install magenta separately.

**Comment by adarob** [comment]
I'm guessing you're trying to install tensorflow-gpu on a mac, which doesn't have a pip package for GPUs. Please reopen if there is a magenta-related issue here.
