### ISSUE TITLE
sktch rnn: how to save the results as .png or .svg files which have same size

### ISSUE THREAD

**Issue by OwalnutO** [tensorflow/magenta#1396]
I currently focus on the project of sketch-rnn. Thansk for your code.

My question is how to save all strokes as .png or .svg files which have the same predefined image size. As the code in draw_strokes.py, the size of the .svg file is related with the stroke coordinates. You pad 25 pixels along the two sides for both x and y axes of each stroke image. How to make them to have same size, just as thoese shown in https://quickdraw.withgoogle.com/data/speedboat, that all boats seem have same image size.

I try to save the .svg files and then use some codes to transfer them to .png files. After that I resize the png files, but the images will become blurr.

Hope for your warm help~~~
Thanks

**Comment by adarob** [comment]
@hardmaru
