### ISSUE TITLE
how to use animal sound

### ISSUE THREAD

**Issue by bzvew** [tensorflow/magenta#1402]
I'd like to interpolate cat sound with human vocal singing. I see the experiment(https://experiments.withgoogle.com/sound-maker) has some animal sound. I don't know if I should prepare the animal sound for different pitches. Is that essential to have different pitches of animal sound, e.g. a cat sound? Could I just use the one bird sample(single pitch maybe) and the entire human singing to calculate the embedding and interpolate for the whole singing song?

**Comment by adarob** [comment]
You can use standard pitch shifting techniques to get different pitches of any input sound. However, having multiple pitches is not required unless you want to be able to play back different pitches.
