### ISSUE TITLE
Problem with generator_map[MODEL_NAME](checkpoint=None, bundle=bundle)

### ISSUE THREAD

**Issue by DavidPrimor** [tensorflow/magenta#1406]
Following the instructions for beginners I used this code:
. . .
MODEL_NAME = 'performance_with_dynamics'
BUNDLE_NAME = MODEL_NAME + '.mag'
bundle = mm.sequence_generator_bundle.read_bundle_file(BUNDLE_NAME)
from magenta.models.melody_rnn import melody_rnn_sequence_generator
generator_map = melody_rnn_sequence_generator.get_generator_map()
generator = generator_map[MODEL_NAME](checkpoint=None, bundle=bundle) 

and I got this error:

File "/mnt/c/Users/david/PycharmProjects/MagentaTest/SimpleMusic.py", line 62, in <module>
    generator = generator_map[MODEL_NAME](checkpoint=None, bundle=bundle)
KeyError: 'performance_with_dynamics'

What should I do? Thanks!

**Comment by adarob** [comment]
You will need to use the performance_sequence_generator for that model.
