### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aletote** [tensorflow/magenta#1407]
I'm getting this error when trying to use Magenta. Not getting it with other Tensorflow GPU ML projects. Any ideas how to fix it? Running Ubuntu, Cuda 9.0, cudnn 7.0 and Tensorflow 1.12

**Comment by adarob** [comment]
Hi, not sure about this one. Is this helpful? https://github.com/tensorflow/tensorflow/issues/15604#issuecomment-426688560

**Comment by aletote** [comment]
Thanks, but I had already seen that link and tried the things suggested there to no avail.
