### ISSUE TITLE
ValueError: Unable to get the Filesystem for path gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord

### ISSUE THREAD

**Issue by aletote** [tensorflow/magenta#1408]
I'm getting this error while trying to do the Data generation / preprocessing step of Score2Perf Music Transformer model on my computer. How can I fix it?

**Comment by iansimon** [comment]
You need to do "pip install apache-beam[gcp]".  @adarob I guess we should add the beam + cloud dependency to setup.py.

**Comment by iansimon** [comment]
You can certainly try running t2t_datagen locally, but it won't take advantage of your GPU; note that this isn't training, just preprocessing the dataset.  I'd expect it to take days locally vs minutes on Cloud.

**Comment by aletote** [comment]
Thanks, I still would like to do it locally if it's possible. Can you tell me what do I need to change please?

**Comment by iansimon** [comment]
Just don't pass the --pipeline_options flag, and it should use the [DirectRunner](https://beam.apache.org/documentation/runners/direct/) that uses your local machine.

**Comment by aletote** [comment]
I do on my machine:

t2t_datagen --data_dir=/home/usuario/Escritorio/dataset/ --problem=score2perf_maestro_language_uncropped_aug --alsologstderr

But I get this error:

IOError: No files found based on the file pattern /home/usuario/Escritorio/maestro/maestro-v1.0.0_test.tfrecord

Any ideas what could I be doing wrong?

**Comment by aletote** [comment]
After upgrading to the latest magenta version now I get:

NameError: name 'datagen_beam' is not defined

**Comment by aletote** [comment]
I commented a line and fixed it, now I get:

RuntimeError: The Apache Beam SDK for Python is supported only on Python 2.7. It is not supported on Python [sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)].

**Comment by iansimon** [comment]
Unfortunately Apache Beam doesn't work with Python 3 (yet?).

**Comment by aletote** [comment]
Ok, I reinstalled magenta with conda so now I'm using 2.7 and getting:

ValueError: Unable to get the Filesystem for path gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_train.tfrecord [while running 'input_transform_train/ReadAllFromTFRecord/ReadAllFiles/ExpandIntoRanges']

**Comment by iansimon** [comment]
I think you'll need to `pip install apache-beam[gcp]`.  Let me know if that doesn't help.

**Comment by aletote** [comment]
I did, the problem is, like I told you, doing the 1st step on my machine. I see DirectRunner activates but shouldn't this paths  in score2perf.py change if I'm doing it locally?

'train': 'gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_train.tfrecord',
    'dev': 'gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_validation.tfrecord',
    'test': 'gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord'

**Comment by iansimon** [comment]
The dataset still lives in Google Cloud Storage.  Alternatively, you can download the datasets locally:

https://storage.googleapis.com/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_train.tfrecord
https://storage.googleapis.com/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_validation.tfrecord
https://storage.googleapis.com/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord

But then you'll also need to modify the problem in score2perf.py to point to your local copies.

**Comment by iansimon** [comment]
BTW I was able to get things to run locally (just extremely slowly), even with the data in Google Cloud Storage.

**Comment by aletote** [comment]
What I don't understand is why do I need to use those datasets if I'm going to use my own?

**Comment by iansimon** [comment]
I'm confused now.  You don't, you can just point to your own TFRecord files, like the ones that would be created by https://github.com/tensorflow/magenta/blob/master/magenta/scripts/convert_dir_to_note_sequences.py

**Comment by aletote** [comment]
Ooooh, I see. So I need to create those files with my MIDIs and convert_dir_to_note_sequences.py, and THEN point at them in the source code so it transforms them to the format that works with Transformer. Is that right?

**Comment by iansimon** [comment]
Yes, correct.  Sorry about the confusion.

**Comment by aletote** [comment]
No problem, thanks for helping me out.

**Comment by 00001101-xt** [comment]
> Cloud

Hi, @iansimon on which aspect we can improve the `data-gen` speed locally, like more cores/RAM?

**Comment by 00001101-xt** [comment]
Hi, @iansimon on which aspect we can improve the `data-gen` speed locally, like more cores/RAM? Currently, I see only 1 CPU(out of 40) using, also my RAM usage is only about 1%.

Thanks.

**Comment by adarob** [comment]
I think the issue is that the tfrecords only have a single shard each. We should probably release a version with more shards to take advantage of parallelism.

**Comment by 00001101-xt** [comment]
I see, is it possible if we first load this whole single shard, then do parallel computing on each individual sample? Which maybe a little bit slower than do parallel on each shard.

And, generating training data locally took me about 3hrs, not that "bad"(days mentioned in the above comment). With more cores, we would expect this process down to minutes. 

For now, my training process looks good, but the outputted "tfevents" may be too much(1.5G `tfevents` for 4k steps, roughly 375G needed for 1M steps), so I was wondering is there any `hparams` to decrease the summarization of the training process.

Thanks for your help.

**Comment by adarob** [comment]
You can try adding a beam.Reshuffle() after the beam.io.tfrecord.ReadAllFromTFRecord (https://github.com/magenta/magenta/blob/425d0e471181a7f3f4af7d13dd34072162304fda/magenta/models/score2perf/datagen_beam.py#L65). I think that will do the trick.
