### ISSUE TITLE
ValueError: No data files found in /home/rishabh/train@128/score2perf_maestro_language_uncropped_aug-train*

### ISSUE THREAD

**Issue by cuckooinc** [tensorflow/magenta#1411]
after generating tfrecord files using t2t_datagen command and saving them in
![files](https://user-images.githubusercontent.com/18083285/51317795-8a4cc800-1a7e-11e9-8ec5-9fc02ae6ae13.PNG)
 /home/rishabh/train@128  
and running the commands
DATA_DIR=/home/rishabh/train@128
HPARAMS_SET=transformer_base
MODEL=transformer
PROBLEM=score2perf_maestro_language_uncropped_aug
TRAIN_DIR=/home/rishabh/train@128

HPARAMS=\
"label_smoothing=0.0,"\
"max_length=0,"\
"max_target_seq_length=2048"

t2t_trainer \
  --data_dir="${DATA_DIR}" \
  --hparams=${HPARAMS} \
  --hparams_set=${HPARAMS_SET} \
  --model=${MODEL} \
  --output_dir=${TRAIN_DIR} \
  --problem=${PROBLEM} \
  --train_steps=1000000

I am getting an error saying
 
ValueError: No data files found in /home/rishabh/train@128/score2perf_maestro_language_uncropped_aug-train*

even though the files are present in train@128  folder 
should i modify the file names to run the scripts?

File attatched showing the generated tf record files are present

**Comment by iansimon** [comment]
You need to remove the "datagen_" prefix from the filenames.
