### ISSUE TITLE
How to transform .npz to graph

### ISSUE THREAD

**Issue by Hansxsourse** [tensorflow/magenta#1413]
Hi
Now our team want to use the .npz dataset to do other research,but we tried many times, we can't transform the .npz numpy array to the grtaph like .jpg or .png. we show the shape about the array is (28,3). so we can't get back to rgb graph.
We read the quick draw rnn dataset paper, still don't know how to transform them.
Can you help me to solve it out?

Best wishes
Hans Yang

**Comment by hardmaru** [comment]
Hi, the aim for sketch-rnn codebase is to work with the .npz file format provided. Data must be specified to such a format for this algorithm to work. While we don't support how one converts other formats to/from the format specified in the paper (which is beyond the scope here), I can point you to the direction where you might be able to get some help. You might want to raise an issue here instead:

https://github.com/googlecreativelab/quickdraw-dataset

**Comment by Hansxsourse** [comment]
Thank you
