### ISSUE TITLE
Onset and Frames: inference more than an octave too low

### ISSUE THREAD

**Issue by JulienCardiff** [tensorflow/magenta#1416]
Hello,

Thank you for sharing all your codes and models!

I followed the instructions for training and inference for the onset and frames model. The results seem good but are however **more than an octave too low**. The tempo appears correct, so the problem should not come from a sampling rate discrepancy. Here is an example:

[audioExample.zip](https://github.com/tensorflow/magenta/files/2793747/audioExample.zip) _(sorry was not allowed to upload .wav directly)_

_I didn't change anything, left all of the default parameters, got the dataset directly from MAPS..._

Does someone have any idea what happened? Has someone experienced the same issue?

Thank you in advance for your help!
Best, Julien

**Comment by cghawthorne** [comment]
Hi @JulienCardiff. I suspect the error you're having was fixed by #1353. Can you try syncing to the latest version of the code and see if that fixes it?

**Comment by cghawthorne** [comment]
Also, you should know that I've been making significant changes to the code base over the last few days to bring it up to date with the latest changes from our paper, [Enabling Factorized Piano Music Modeling and Generation with the MAESTRO Dataset](https://goo.gl/magenta/maestro-paper). So it's likely that there will be some incompatibilities with any checkpoints you've previously trained after you sync.
