### ISSUE TITLE
pip: No matching distribution found for tensorflow-metadata

### ISSUE THREAD

**Issue by kjcole** [tensorflow/magenta#1422]
```
Collecting tensorflow-metadata (from tfds-nightly->tensor2tensor>=1.10.0->magenta)
  Could not find a version that satisfies the requirement tensorflow-metadata (from tfds-nightly->tensor2tensor>=1.10.0->magenta) (from versions: )
No matching distribution found for tensorflow-metadata (from tfds-nightly->tensor2tensor>=1.10.0->magenta)
```

The entire log from `$ sudo pip3 install magenta` to the failure:

[magenta-bug.txt](https://github.com/tensorflow/magenta/files/2813703/magenta-bug.txt)

**Comment by cghawthorne** [comment]
Can you list the exact version of python you're running? It looks like tensorflow-metadata does have some restrictions for python version: https://github.com/tensorflow/metadata/blob/master/setup.py#L56

**Comment by kjcole** [comment]
@cghawthorne 

```
$ python3
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
(on an up-to-date Arch Linux system BTW.)

**Comment by cghawthorne** [comment]
Yeah, this is because the tensorflow-metadata version requirement is too strict. Their python_requires of '>=2.7,<=3.7' will accept only up to Python 3.7.0. Can you file a bug on their repo (https://github.com/tensorflow/metadata/issues)? I'll close this bug since it's not a Magenta issue. Thanks!
