### ISSUE TITLE
Error on urllib.urlretrieve when running download_pretrained_models in python 3

### ISSUE THREAD

**Issue by vaipatel** [tensorflow/magenta#1427]
Hi there, I was wondering if anyone has encountered the following error and if the subsequent thoughts seem reasonable. Thanks!

### Environment
* Windows 10 64-bit
* Python 3.6.8
* Installed `magenta-gpu` in a `conda` env using `pip install magenta-gpu`

### Issue
I'm trying to run the [`download_pretrained_models`](https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py#L94-L111) function defined in the  [`magenta/models/sketch_rnn/sketch_rnn_train.py`](https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py) to download pretrained weights in Python 3.6.

This results in an `AttributeError: module 'urllib' has no attribute 'urlretrieve'` on [line 106](https://github.com/tensorflow/magenta/blob/24ff8241f210926cefa8e7d57af227f25aa3653a/magenta/models/sketch_rnn/sketch_rnn_train.py#L106) where a call to `urllib.urlretrieve` is made.

Specifically, here is the code I execute and the subsequent error.
```
>>> import tensorflow as tf
>>> from magenta.models.sketch_rnn.sketch_rnn_train import *
>>> download_pretrained_models(models_root_dir="sketchrnn/models")
INFO:tensorflow:Downloading pretrained models from http://download.magenta.tensorflow.org/models/sketch_rnn.zip...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\Vai\Anaconda3\envs\artsy\lib\site-packages\magenta\models\sketch_rnn\sketch_rnn_train.py", line 106, in download_pretrained_models
    urllib.urlretrieve(pretrained_models_url, zip_path)
AttributeError: module 'urllib' has no attribute 'urlretrieve'
```

### Possible cause
I think this has to do with the fact that [urllib has been split into submodules in Python 3](https://docs.python.org/2/library/urllib.html#module-urllib), and the `urlretrieve` function now resides in `urllib.request`.

### Possible fix
The following change inspired by [this stack answer](https://stackoverflow.com/a/34128192) to the [`import urllib`](https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py#L24) line at the beginning seems to fix the issue for me. 

```
import sys
if sys.version_info[0] >= 3:
    # Check may need to be updated if python 4+ adopts the earlier style.
    from urllib.request import urlretrieve
else:
    from urllib import urlretrieve
```

Of course, with the above import style we need to drop the `urllib.` from [line 106](https://github.com/tensorflow/magenta/blob/24ff8241f210926cefa8e7d57af227f25aa3653a/magenta/models/sketch_rnn/sketch_rnn_train.py#L106) and just call
```
urlretrieve(pretrained_models_url, zip_path)
``` 

With the above fix the `download_pretrained_models` function works as expected.
```
>>> from magenta.models.sketch_rnn.sketch_rnn_train import *
>>> download_pretrained_models(models_root_dir="sketchrnn/models")
INFO:tensorflow:Downloading pretrained models from http://download.magenta.tensorflow.org/models/sketch_rnn.zip...
INFO:tensorflow:Download complete.
INFO:tensorflow:Unzipping sketchrnn/models\sketch_rnn.zip...
INFO:tensorflow:Unzipping complete.
```

**Comment by vaipatel** [comment]
Sorry just saw pull request #1345 addresses this and a few more problems related to [sketch_rnn_train.py](https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py) and Python 3. Add I guess a better more concise fix was to use `six.moves.urllib.request` per this [review note](https://github.com/tensorflow/magenta/pull/1345/files#r233199710). I'll close this issue.

**Comment by adarob** [comment]
@vaipatel the author of #1345 has been unresponsive. Can you continue that fix?

**Comment by vaipatel** [comment]
Just making a note for future reference - #1345 was continued and finished up in #1429. Thanks.
