### ISSUE TITLE
Melody RNN does not receive all available MIDI notes

### ISSUE THREAD

**Issue by AndrewRahman** [tensorflow/magenta#1428]
I am using a primer_midi file that contains all available MIDI notes from 0-127, however after the MIDI file is generated it shows that it is truncating the incoming MIDI notes from C3 to B5 (48 to 83). This issue occurs on all three models of the Melody_RNN (basic, attention, lookback).

This means that the Melody is constrained to a narrow range, and therefore cannot be used to generate a bassline. 

I have attached the generated MIDI file, an image of it, as well as the primer_midi file.

![screen shot 2019-02-04 at 13 43 05](https://user-images.githubusercontent.com/17302975/52209593-b93baa00-2884-11e9-84a5-14b9ffd23e1f.png)

**MIDI Files**
https://drive.google.com/drive/folders/1TtKwOwh2jooiXkE_ZCWkVcP8HlQIoU9d?usp=sharing

**Comment by hedonistrh** [comment]
The reason comes from [the model.](https://github.com/tensorflow/magenta/blob/master/magenta/models/melody_rnn/melody_rnn_model.py)

```
DEFAULT_MIN_NOTE = 48
DEFAULT_MAX_NOTE = 84
```

Also, if you check [melody encoder-decoder](https://github.com/tensorflow/magenta/blob/master/magenta/music/melody_encoder_decoder.py), you can see that
```python
def events_to_input(self, events, position):
    """Returns the input vector for the given position in the melody.
    Returns a self.input_size length list of floats. Assuming
    self._min_note = 48, self._note_range = 36, two lookback distances, and
    seven binary counters, then self.input_size = 74. Each index represents a
    different input signal to the model.
    Indices [0, 73]:
    [0, 35]: A note is playing at that pitch [48, 84).
    36: Any note is playing.
    37: Silence is playing.
    38: The current event is the note-on event of the currently playing note.
    39: Whether the melody is currently ascending or descending.
    40: The last event is repeating (first lookback distance).
    41: The last event is repeating (second lookback distance).
    [42, 48]: Time keeping toggles.
    49: The next event is the start of a bar.
    [50, 61]: The keys the current melody is in.
    [62, 73]: The keys the last 3 notes are in.

```

**Comment by adarob** [comment]
I added a new model config called `mono_rnn` that uses the full range. I think we just need to publish a bundle for it. Would that be of interest?

**Comment by hedonistrh** [comment]
Hey @adarob I think, that will be nice :octocat: 👍

**Comment by AndrewRahman** [comment]
Thank you for your responses. Would love to check out the mono_rnn!

**Comment by adarob** [comment]
Please try http://download.magenta.tensorflow.org/models/mono_rnn.mag

**Comment by adarob** [comment]
Fixed by https://github.com/tensorflow/magenta/commit/e4f3bb9816c0f2589beff67ec98e80510b8cfb90
