### ISSUE TITLE
score2perf ; t2t_datagen generates files with size zero

### ISSUE THREAD

**Issue by Kangmo** [tensorflow/magenta#1433]
First of all, thanks for the release of music transformer. I love it!

Before getting the script to generate the zero sized files, I hit the following error. 

IOError: No files found based on the file pattern /bigstore/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord

> WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
> For more information, please see:
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
>   * https://github.com/tensorflow/addons
> If you depend on functionality not listed there, please file an issue.
> 
> INFO:tensorflow:Generating problems:
>     score2perf:
>       * score2perf_maestro_language_uncropped_aug
> INFO:tensorflow:Generating data for score2perf_maestro_language_uncropped_aug.
> Traceback (most recent call last):
>   File "/home/kangmo/.conda/envs/gcp-p27/bin/t2t_datagen", line 10, in <module>
>     sys.exit(console_entry_point())
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/magenta/tensor2tensor/t2t_datagen.py", line 34, in console_entry_point
>     tf.app.run(main)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/magenta/tensor2tensor/t2t_datagen.py", line 29, in main
>     t2t_datagen.main(argv)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/bin/t2t_datagen.py", line 198, in main
>     generate_data_for_registered_problem(problem)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/bin/t2t_datagen.py", line 260, in generate_data_for_registered_problem
>     problem.generate_data(data_dir, tmp_dir, task_id)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/magenta/models/score2perf/score2perf.py", line 157, in generate_data
>     absolute_timing=self.absolute_timing)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/magenta/models/score2perf/datagen_beam.py", line 404, in generate_examples
>     for split_name in split_names
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 840, in __ror__
>     return self.transform.__ror__(pvalueish, self.label)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 491, in __ror__
>     result = p.apply(self, pvalueish, label)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/pipeline.py", line 479, in apply
>     return self.apply(transform, pvalueish)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/pipeline.py", line 515, in apply
>     pvalueish_result = self.runner.apply(transform, pvalueish)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 193, in apply
>     return m(transform, input)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 199, in apply_PTransform
>     return transform.expand(input)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/magenta/models/score2perf/datagen_beam.py", line 63, in expand
>     pcoll |= beam.io.tfrecordio.ReadFromTFRecord(self._tfrecord_path)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 259, in __init__
>     validate)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 170, in __init__
>     validate=validate)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/io/filebasedsource.py", line 121, in __init__
>     self._validate()
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/options/value_provider.py", line 137, in _f
>     return fnc(self, *args, **kwargs)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/apache_beam/io/filebasedsource.py", line 181, in _validate
>     'No files found based on the file pattern %s' % pattern)
> IOError: No files found based on the file pattern /bigstore/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord
> 

So I had to mount the magentadata bucket to get the script run.

> $ gcsfuse magentadata /bigstore/magentadata
> Using mount point: /bigstore/magentadata
> Opening GCS connection...
> Opening bucket...
> Mounting file system...
> File system has been successfully mounted.
> 

After running t2t_datagen on google cloud, I get files with size zero.(attached screenshot)
![1](https://user-images.githubusercontent.com/510271/52458629-e8fbf200-2ba3-11e9-9f96-2188fa615b18.PNG)

How can I resolve this issue?

-- here are list of software versions I use --

> magenta version 1.0.2
> tensorflow version 1.13.0rc1
> python 2.7.8
> CentOS 7.5
> 

-- here is the t2t_datagen command I use --

> PROBLEM=score2perf_maestro_language_uncropped_aug
> BUCKET=aa
> PROJECT=bb
> 
> PIPELINE_OPTIONS=\
> "--runner=DataflowRunner,"\
> "--project=${PROJECT},"\
> "--temp_location=gs://${BUCKET}/tmp,"\
> "--setup_file=/data/ai/magenta-source/setup.py"
> 
> t2t_datagen \
>   --data_dir=gs://${BUCKET}/datagen \
>   --problem=${PROBLEM} \
>   --pipeline_options="${PIPELINE_OPTIONS}" \
>   --alsologtostderr

The console output after running the command is attached as console-output.txt
[console-output.txt.txt](https://github.com/tensorflow/magenta/files/2843597/console-output.txt.txt)

**Comment by Kangmo** [comment]
It seems these three lines are the root cause of the issue. After changing /bigstore/ to gs:// the problem is gone.

magenta/models/score2perf/score2perf.py

> MAESTRO_TFRECORD_PATHS = {
>     'train': 'gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_train.tfrecord',
>     'dev': 'gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_validation.tfrecord',
>     'test': 'gs://magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord'
> #    'train': '/bigstore/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_train.tfrecord',
> #    'dev': '/bigstore/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_validation.tfrecord',
> #    'test': '/bigstore/magentadata/datasets/maestro/v1.0.0/maestro-v1.0.0_test.tfrecord'
> }
> # pylint: enable=line-too-long
>

**Comment by iansimon** [comment]
This should now be fixed on master as of commit [4a6041c](https://github.com/tensorflow/magenta/commit/4a6041c9c64aebb5b501e5300dcc1bb3868d2e98).
