### ISSUE TITLE
how to cite melody rnn

### ISSUE THREAD

**Issue by cristianmtr** [tensorflow/magenta#1438]
Hey

I am writing my thesis on music generation in DL. How should I cite your melody rnn models? I can't find a paper. Is it just the blog post?

Thanks

**Comment by hedonistrh** [comment]
In [this paper](https://arxiv.org/pdf/1712.05274.pdf), they cited like:

> Waite,  E.;  Eck,  D.;  Roberts,  A.;  and  Abolafia,  D.   2016.Project  magenta:  Generating  long-term  structure  in  songs and storie

Also, [in this paper](https://arxiv.org/pdf/1709.01620.pdf), they cited MusicVae like:

> Adam Roberts, Jesse Engel, Colin Raffel, Ian Simon, and Curtis Hawthorne.  MusicVAE: Creating a palette for musical scores withmachine learning, March 2018. https://magenta.tensorflow.org/music-vae.

**Comment by adarob** [comment]
We have no melody rn paper, so you can cite the blog post as in that first article. For music vae please cite:
```
@inproceedings{47078,
title	= {A Hierarchical Latent Vector Model for Learning Long-Term Structure in Music},
author	= {Adam Roberts and Jesse Engel and Colin Raffel and Curtis Hawthorne and Douglas Eck},
year	= {2018},
URL	= {http://proceedings.mlr.press/v80/roberts18a.html},
booktitle	= {International Conference on Machine Learning (ICML)}
}
```
