### ISSUE TITLE
Colabs appear to be broken

### ISSUE THREAD

**Issue by luckandrew** [tensorflow/magenta#1439]
Have tried a few of the colab notbooks for magenta with python and some similar errors are being thrown with magenta.etc imports...I noticed this on PerformanceRNN, Hello Magenta, and MultiTrackMusicVAE...Here's a trace from Hello Magenta:

Installing dependencies...
Uninstalling tensorflow-1.12.0:
  Successfully uninstalled tensorflow-1.12.0
Importing libraries and defining some helper functions...

ImportErrorTraceback (most recent call last)
<ipython-input-2-61d987c2c9c7> in <module>()
     22 from google.colab import files
     23 
---> 24 import magenta.music as mm
     25 import magenta
     26 import tensorflow

/usr/local/lib/python2.7/dist-packages/magenta/__init__.py in <module>()
     23 # TODO(adarob): Remove these imports once moved to /py internally.
     24 
---> 25 import magenta.common.beam_search
     26 import magenta.common.concurrency
     27 import magenta.common.nade

/usr/local/lib/python2.7/dist-packages/magenta/common/__init__.py in <module>()
     18 
     19 from .beam_search import beam_search
---> 20 from .nade import Nade
     21 from .sequence_example_lib import count_records
     22 from .sequence_example_lib import flatten_maybe_padded_sequences

/usr/local/lib/python2.7/dist-packages/magenta/common/nade.py in <module>()
     21 
     22 import tensorflow as tf
---> 23 import tensorflow_probability as tfp
     24 
     25

**Comment by adarob** [comment]
Thanks for reporting this! It looks like a couple of issues:

1. We should always be installing magenta with "pip install -U magenta" since it looks like Colab will keep an older version if it was previously installed on the same machine.
2. tensorflow_probability may be pointing to a different version of TF as we are.

1 is easy to fix, and I'm still investigating 2.

**Comment by adarob** [comment]
I fixed these internally but you won't see the updates in colab for a day or two. You can make the local modifications yourself however:

1. Fixed this by adding `-U` to the magenta pip install so it becomes: `!pip install -qU magenta`
2. Fixed this (in hello magenta only) by removing the temporary hack that uninstalls the pre-installed TensorFlow version (`!pip uninstall -y tensorflow`).
