### ISSUE TITLE
Certain MIDI files don't work at all with Magenta.

### ISSUE THREAD

**Issue by aaaooooaaa** [tensorflow/magenta#1440]
I've found quite a lot of the MIDI files I have don't work at all, especially ones I've made myself using Ableton. Does anyone have any suggestions to fix this? I've tried a few things like converting between MIDI formats 0 and 1 but nothing seems to work. 

In Drums_RNN for instance everything seems to work up until the generation of training_drum_tracks.tfrecord which for some MIDI files contains data but for most remains blank.

**Comment by adarob** [comment]
I believe drum tracks need to be on Channel 10 for Magenta to recognize them. Give that a shot and reopen if you still have an issue.

**Comment by aaaooooaaa** [comment]
It doesn't look like that's the problem. I have some MIDI files which use channel 10 that don't work either, I also tried converting the others to channel 10 without any luck.
