### ISSUE TITLE
failed with error code 1 when installing magenta

### ISSUE THREAD

**Issue by Kyler03** [tensorflow/magenta#1441]
Hello
sorry to ask some help but i'm lost right now and don't know what to do
so im on python 3.7 and tried to pip install magenta in the virtualenv but in the middle i have this fail >>

`Failed building wheel for networkx`

<<<

i have this error at the end >>

`Command "d:\python~1\musicai\scripts\python.exe -u -c "import setuptools, tokenize;__file__='AppData\\Local\\Temp\\pip-install-zle3e1s0\\networkx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record AppData\Local\Temp\pip-record-g5jtoccx\install-record.txt --single-version-externally-managed --compile --install-headers d:\python~1\musicai\include\site\python3.7\networkx" failed with error code 1 in AppData\Local\Temp\pip-install-zle3e1s0\networkx\`

**Comment by Kyler03** [comment]
anyone please ??

**Comment by adarob** [comment]
any ideas @cghawthorne ?

**Comment by cghawthorne** [comment]
This looks like a problem with the `networkx` package. Can you try just doing `pip install networkx` by itself? If that doesn't work, it might just be an issue with their package on Windows, and you could try asking on their issue tracker: https://github.com/networkx/networkx/issues

**Comment by alexnathanson** [comment]
@cghawthorne I'm running in to this same issue. Pip install networkx works fine, but pip install magenta still fails. 

Thanks!

**Comment by alexnathanson** [comment]
@Kyler03 did you figure out a work around for this?

**Comment by cghawthorne** [comment]
That chess_master.py file is also a part of networkx, so I think the problem is still somehow related to that package. I'd suggest asking on the networkx issue tracker.

**Comment by dkter** [comment]
Magenta depends on networkx==1.8.1, which is the broken version. Newer versions of networkx seem to work fine.
