### ISSUE TITLE
Magenta Studio crashes Ableton 10

### ISSUE THREAD

**Issue by winkpain** [tensorflow/magenta#1444]
I am having an issue with Magenta and a new, fresh install of Ableton 10
More than half of the time I load it into an Ableton session, it crashes. 
When it loads successfully, which it seems to want to do only in an empty, fresh project, it functions as expected, but when I save the project with Magenta still loaded it will crash when trying to open that project again. 
As well, whenever I try to load the .amxd file from the Ableton browser it will crash the current project.
In fact, the only way I can consistently use it, it seems, is by dragging the .amxd from a Windows browser into an empty, fresh project, then using the tools of Magenta, then deleting it from the project and saving what I had done after that.
Any ideas or other similar issues?

I have all the Ableton crash logs if needed.
Attached is the error message from Ableton:
![capturea](https://user-images.githubusercontent.com/47703661/52906703-5d2b3b00-321f-11e9-94be-0c8dd9e4c4d8.JPG)

**Comment by adarob** [comment]
If you're still having this issue, please reopen at github.com/tensorflow/magenta-studio
