### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file /home/<username>/anaconda3/envs/py2/lib/python2.7/site-packages/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py o n line 3346

### ISSUE THREAD

**Issue by crizzy9** [tensorflow/magenta#1452]
I get this error while trying to run the score2perf model in the DataGeneration/Preprocessing step on GCP inside a VM.
I installed magenta-gpu as per the instructions given on the main README.

**Comment by crizzy9** [comment]
Figured out the issue.
`pip install magenta-gpu` installs scipy-1.2.1
which is incompatible and while running setup.py it also installs scipy-1.2.0
after uninstalling both versions and installing scipy-1.2.0 after `python setup.py install` started working fine.

**Comment by cghawthorne** [comment]
Can you give some more details on how installing the magenta pip package ended up installing scipy-1.2.1? Our setup.py should restrict it to 1.2.0: https://github.com/tensorflow/magenta/blob/master/setup.py#L53

That said, I'm not sure why 1.2.1 would cause that error anyway.

**Comment by crizzy9** [comment]
So in my conda environment, I would typically install all magenta dependencies with pip install magenta-gpu. If I don't do this and directly go with setup.py it fails to install many of the other dependencies that are required. It is in this step that scipy 1.2.1 is installed and after that during the setup.py installation scipy 1.2.0 is also installed making both the versions useless. But after uninstalling both versions and reinstalling scipy 1.2.0 solves the problem.

**Comment by cghawthorne** [comment]
Yeah, installing via pip rather than setup.py (even if it's pip -e .) definitely does a better job of handling dependencies. Glad you go things working.
