### ISSUE TITLE
Magenta 1.0.2 Incompatible Error - Latest NumPy (1.16.1)

### ISSUE THREAD

**Issue by skresearcher** [tensorflow/magenta#1453]
I'm trying to install and use Magenta and Tensorflow, but I keep running into compatibility issues with NumPy. First when I installed Magenta, it removed the latest version of NumPy and installed NumPy 1.15.4, but this led to import issues with both Magenta and Tensorflow. When I updated to NumPy 1.16.1 again, the issue with Tensorflow is resolved, but now Magenta is throwing more errors due to binary incompatibility. This is the error message I get when I install NumPy 1.16.1. Any help would be much appreciated.

`pip install --upgrade numpy`
`Collecting numpy`
`Using cached https://files.pythonhosted.org/packages/41/b8/3a6b07352c2542ca1c89be7583e7ca07bf513895b6ac59ae008054f326b1/numpy-1.16.1-cp37-cp37m-win_amd64.whl`
`magenta 1.0.2 has requirement numpy<=1.15.4,>=1.14.6, but you'll have numpy 1.16.1 which is incompatible.`
`Installing collected packages: numpy`
  `Found existing installation: numpy 1.15.4`
    `Uninstalling numpy-1.15.4:`
      `Successfully uninstalled numpy-1.15.4`
`Successfully installed numpy-1.16.1`

**Comment by cghawthorne** [comment]
Can you be more specific about the errors you're seeing with TensorFlow or Magenta with the different numpy versions? Either 1.15.4 or 1.16.1 should work fine with either Magenta or TensorFlow, we just restrict to 1.15.4 because newer versions cause problems with our pylint checks.

**Comment by sk004git** [comment]
Hi,

Thanks for your response. This is the error I get when I try to import either Magenta or Tensorflow with Numpy 1.15.4 installed.

```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-02-25 15:17:31.842994: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
```
[Magenta Error with Numpy 1.16.1.txt](https://github.com/tensorflow/magenta/files/2902475/Magenta.Error.with.Numpy.1.16.1.txt)

When I use Numpy 1.16.1, Tensorflow imports successfully, but Magenta continues to give errors. I've attached a notepad with the error log when I try to import Magenta using Numpy 1.16.1, as it is very long.

I have tried uninstalling, reinstalling, and using different versions of NumPy, but to no avail. Appreciate any help regarding this issue.

**Comment by cghawthorne** [comment]
That sounds like a corrupt numpy installation. I've seen problems like that before when a user numpy installation is interacting with a site numpy install. Can you try using [conda](https://conda.io/en/latest/miniconda.html) (or virtualenv) to set up an isolated environment that is definitely separate from your system python installation?

**Comment by sk004git** [comment]
Thanks for the response. The issue still exists when using conda also. The system Python installation was on a new PC with not much applications installed, so there is less chance of any corrupted packages. But I still installed conda to check if it was a corruption issue; however, I still get the exact same errors when trying to use either NumPy 1.15.4 or 1.16.1.

**Comment by cghawthorne** [comment]
In f272e6df4a9164fcaef77ed3ce8bc3c89b0a1f79, I removed the upper bound on the numpy version, which should hopefully simplify some of the issues you were having. Can you try installing with the latest code and see if that fixes the problem?
