### ISSUE TITLE
[onset and frame v1.0.2] Training on maestro dataset is so slow, how many iterations did you train to get the provided v1.0.2 checkpoint ?

### ISSUE THREAD

**Issue by pangwong** [tensorflow/magenta#1454]
Iterate 100 steps costs about 780s, what a long time to achieve a comparable result with your provided checkpoint if iterate 76W iterations as stated in your paper. 
I guess most of the time costs on prepareing training data, e.g. noise augment. At the same time, my machine's IO is completely not busy. 
 Or am I wrong with some unknown things ? 
  
```
...
322383 INFO:tensorflow:global_step/sec: 0.127495
322384 INFO:tensorflow:global_step = 20100, loss = 0.09907979 (784.348 sec)
322385 INFO:tensorflow:Executing: sox /tmp/tmp4smib6c4.wav -p synth pinknoise vol 0.03839970058754216 | sox -m /tmp/tmp4smib6c4.wav - /tmp/tmporq8dk4p.wav
322386 output_file: /tmp/tmp_yembn01.wav already exists and will be overwritten on build
...
323985 INFO:tensorflow:global_step/sec: 0.127576
323986 INFO:tensorflow:global_step = 20200, loss = 0.07886424 (783.842 sec)
...
```

**Comment by cghawthorne** [comment]
Yeah, unfortunately it does run quite slow. For the paper, we distributed training across 3 machines with async updates, each with V100 GPUs, and even that took something like a week to train.

I'm working on some updates now that will allow training across multiple local GPUs, and at some point I think we'll need to do the audio augmentation at dataset creation time.
