### ISSUE TITLE
gansynth training with wave dataset

### ISSUE THREAD

**Issue by denton0131** [tensorflow/magenta#1467]
I am wondering if I can use raw wave files as training data with gansynth?  I looked at the data_helper.py and wave_to_data has not been implemented yet.

**Comment by jesseengel** [comment]
Yah, that should be pretty straightforward. If you look in datasets.py you see that it's actually reading waveforms as the input data. I think you just need to write a script to turn  you waveforms into a tfrecord file and read from it in a similar way.
