### ISSUE TITLE
music_vae increase generated file time 

### ISSUE THREAD

**Issue by sophia652** [tensorflow/magenta#1472]
Hi there!
I am using multitrack config hier-multiperf_vel_1bar_med. Could anyone guide how to increase the duration of generated file? Currently it is ~6sec.

**Comment by hedonistrh** [comment]
This issue #1468 can be helpful for you.

**Comment by sophia652** [comment]
@hedonistrh that didn't work for me. changing config.hparams.max_seq_len doesn't effect the output file time.

**Comment by adarob** [comment]
FYI @iansimon 

The multitrack models output an end token to specify when the sequence should end so the best way to extend the sequences is to retrain the model with longer inputs. You could also modify the config to remove the end sequence token and it may allow it to continue past that point, although I suspect the model will not perform well past the end token.

**Comment by iansimon** [comment]
You'll want to train with a new configuration where hop_size_bars (and potentially chunk_size_bars) is larger than 1.  Probably the most straightforward change would be to change hop_size_bars and chunk_size_bars to e.g. 4, and maybe increase max_events_per_instrument by a factor of 2 or 4 as it's per-chunk.

To explain a bit more, the model uses a 3-level hierarchy.  The top level is a sequence of _chunks_.  Each chunk has multiple _tracks_.  And each track has multiple _events_.

The configuration in the Colab uses one single-bar chunk.  I never really tried using chunks longer than a bar, but probably 2 or 4 bars could work.  I did try using multiple single-bar chunks, and there even 4 bars barely worked.

**Comment by VegetaDTX** [comment]
Hello there people!
@iansimon, and others - I'm not sure if I understand well. Is it that it is very hard to achieve samples longer than 30 seconds ANYWAY (as in - there is an intrinsic hardware related/technological/complexity related bottleneck), or is it just that one has to train the model with settings adjusted for a longer sample in order to get a proper longer sample, but it just takes way more time?

I'd really appreciate an explanation!

**Comment by iansimon** [comment]
I couldn't get training to work very well for longer samples in the hierarchical VAE.  I'm not sure if there's some simple change to model architecture that would greatly improve things or if it would require a different kind of architecture entirely.

**Comment by VegetaDTX** [comment]
@iansimon, thank you for your reply! I wish we could know how things really are regarding the duration of the sample so I could fully commit myself to Magenta or move on to some other project.

Theoretically, there should be no reason why training and sampling a 1-minute-long song would be impossible, if the dataset is proper and all the songs in it are longer than 1 minute. It seems that the only bottleneck is the hardware power / speed,  but I totally might be wrong.
