### ISSUE TITLE
Melody rnn note range

### ISSUE THREAD

**Issue by denton0131** [tensorflow/magenta#1475]
Hi there.  I have a question about note generation using melody rnn.

It looks like the note range is different from the training data.  All the high-value notes are missing.  I am wondering if this is caused by ending notes (low notes).  Is there any range limit for attention rnn?  Or this may just result from the training is not over yet?

![image001](https://user-images.githubusercontent.com/32561659/54452001-75ad4900-472a-11e9-8b74-d67f8bed9e3f.png)

**Comment by adarob** [comment]
I believe your concerns are the same as #1428. Please reopen if not.

**Comment by denton0131** [comment]
If I'd like to train my midi in full range, should I modify the code fragment in magenta/magenta/music/melody_encoder_decoder.py?  Or I just need to set the min to 0 and max note to 128.

`def events_to_input(self, events, position):
    """Returns the input vector for the given position in the melody.
    Returns a self.input_size length list of floats. Assuming
    self._min_note = 48, self._note_range = 36, two lookback distances, and
    seven binary counters, then self.input_size = 74. Each index represents a
    different input signal to the model.
    Indices [0, 73]:
    [0, 35]: A note is playing at that pitch [48, 84).
    36: Any note is playing.
    37: Silence is playing.
    38: The current event is the note-on event of the currently playing note.
    39: Whether the melody is currently ascending or descending.
    40: The last event is repeating (first lookback distance).
    41: The last event is repeating (second lookback distance).
    [42, 48]: Time keeping toggles.
    49: The next event is the start of a bar.
    [50, 61]: The keys the current melody is in.
    [62, 73]: The keys the last 3 notes are in.
`
