### ISSUE TITLE
magenta installation with pip

### ISSUE THREAD

**Issue by iqraceme** [tensorflow/magenta#1476]
I am using fedora 28 version. Whenever I try to use the pip install magenta command on bash, I get the following error related to cannot find -ljack:

   g++ -pthread -shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g build/temp.linux-x86_64-3.6/src/_rtmidi.o build/temp.linux-x86_64-3.6/src/rtmidi/RtMidi.o -L/usr/lib64 -lasound -ljack -lpthread -lpython3.6m -o build/lib.linux-x86_64-3.6/rtmidi/_rtmidi.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/8/../../../libjack.so when searching for -ljack
    /usr/bin/ld: skipping incompatible //lib/libjack.so when searching for -ljack
    /usr/bin/ld: skipping incompatible //usr/lib/libjack.so when searching for -ljack
    /usr/bin/ld: cannot find -ljack
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1

**Comment by cghawthorne** [comment]
I'm not familiar with Fedora, but you'll need to install the JACK library development package. The equivalent Debian/Ubuntu command is: `sudo apt-get install build-essential libasound2-dev libjack-dev`. You could try asking on a Fedora support forum to see what the Fedora version of that is.
