### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DEFAULT_HPARAMS'

### ISSUE THREAD

**Issue by ak9250** [tensorflow/magenta#1485]
getting this error when running onsets to frames colab notebook for the model intialization cell

AttributeError: 'module' object has no attribute 'DEFAULT_HPARAMS'

**Comment by cghawthorne** [comment]
Sorry, I need to update the colab to work with some changes in the codebase. Will have a fix shortly.

**Comment by cghawthorne** [comment]
I've got the fix checked in on our side. It will deploy publicly in a couple days.

**Comment by cghawthorne** [comment]
New version is live now.
