### ISSUE TITLE
using other problems in score2perf

### ISSUE THREAD

**Issue by inventor71** [tensorflow/magenta#1487]
Hello,

I am interested in using t2t_datagen for problems other than "score2perf_maestro_language_uncropped_aug ".
But other problems (such as  "chords2perfproblems"), doesn't seem to be included in magenta's t2t_datagen's registry. 
Is there a way to train on other problems?

**Comment by iansimon** [comment]
Currently there are no chords -> performance problems registered; the main reason is that we don't have a good dataset of performances with chord labels.  We're working on a way around this...
