### ISSUE TITLE
pip install issues

### ISSUE THREAD

**Issue by QirenSun** [tensorflow/magenta#1490]
Could not find a version that satisfies the requirement jaxlib (from tensor2tensor) (from versions: )
No matching distribution found for jaxlib (from tensor2tensor)

Windows

**Comment by iansimon** [comment]
Tensor2Tensor appears to have a dependency on Jax, which does not currently support Windows.  You can try using the Magenta development environment as described [here](https://github.com/tensorflow/magenta#development-environment); unless you're using Transformer you won't need the Tensor2Tensor dependency.
