### ISSUE TITLE
Visulization on Score2Perf

### ISSUE THREAD

**Issue by LegendJ** [tensorflow/magenta#1498]
I wonder how the visulization of attention on the piano roll is done? Are there any open-source code or whatever things I can refer to ?

**Comment by notwaldorf** [comment]
Not sure which visualization in particular you're referring to -- if you mean the visualizations of MIDI files on the [blog](https://magenta.tensorflow.org/music-transformer), they're done with one of the magenta.js Visualizers (you can see a demo of them in action [here](https://tensorflow.github.io/magenta-js/music/demos/visualizer.html))

For the attention, we built an interactive [attention visualizer](https://meowni.ca/transformer-visualization/). You can load any of the figures in the paper up, and then click on any of the notes to visualize the attention for that note.

**Comment by 00001101-xt** [comment]
> Not sure which visualization in particular you're referring to -- if you mean the visualizations of MIDI files on the [blog](https://magenta.tensorflow.org/music-transformer), they're done with one of the magenta.js Visualizers (you can see a demo of them in action [here](https://tensorflow.github.io/magenta-js/music/demos/visualizer.html))
> 
> For the attention, we built an interactive [attention visualizer](https://meowni.ca/transformer-visualization/). You can load any of the figures in the paper up, and then click on any of the notes to visualize the attention for that note.

[attention visualizer](https://meowni.ca/transformer-visualization/) page not found.

**Comment by adarob** [comment]
https://magenta.github.io/music-transformer-visualization/

**Comment by 00001101-xt** [comment]
> https://magenta.github.io/music-transformer-visualization/

Thanks for your help. ^_^
