### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'app'

### ISSUE THREAD

**Issue by heaversm** [tensorflow/magenta#1504]
Using [next_frame_prediction](https://github.com/tensorflow/magenta/tree/master/magenta/video/next_frame_prediction_pix2pix), running:

```
./create_video.sh    ./working_folder    20    500   ./output_folder
```

I get the error:

```
training 1/20
Traceback (most recent call last):
  File "pix2pix-tensorflow-0.1/main.py", line 75, in <module>
    tf.app.run()
AttributeError: module 'tensorflow' has no attribute 'app'
```

From other issues and my own search, seems like this might be a tensorflow version issue? I appear to be running:

python 3.7.1
tensorflow version: 2.0.0-alpha0 (?)

I have installed magenta via the `development environment` steps from the magenta README.

**Comment by adarob** [comment]
We do not yet support tf 2.0.

**Comment by heaversm** [comment]
Yes - but I think this is the version that is installed by default using your setup procedures.
