### ISSUE TITLE
ResourceExhaustedError just to generate from pretrained model in NSynth

### ISSUE THREAD

**Issue by smkm** [tensorflow/magenta#1507]
I use a Tesla V100 16GB and I want to generate new sounds using the [pre-trained WaveNet model](http://download.magenta.tensorflow.org/models/nsynth/wavenet-ckpt.tar) using [This Method](https://github.com/tensorflow/magenta/tree/master/magenta/models/nsynth#example-usage-generate-from-wav-files) in [NSynth](https://github.com/tensorflow/magenta/tree/master/magenta/models/nsynth). 

However, even after I decreased the batch size to 1, the model requires way more memory to be available than a normal GPU, and throws a ResourceExhaustedError. (I confirmed that the GPU had all of its memory available before the operation.)

Are there any ways or workarounds for the sound generation to be available to GPUs with VRAM that are even smaller than 16GB (most consumer GPUs) and so?

**Comment by jesseengel** [comment]
Hi, I'm sorry but I'm not able to reproduce your error. I can run the code locally on a Titan X (12GB). Also, Also, the EZ NSynth Colab (https://colab.sandbox.google.com/notebooks/magenta/nsynth/nsynth.ipynb) runs the same methods on a Colab GPU, which I believe has <= 16GB.

**Comment by jesseengel** [comment]
Did a little more sleuthing. If your command is `nsynth_generate --source_path=/path/to/file.wav` you need to also specify `--sample_length=number_of_audio_samples`  where number of audio samples is >= 16000 * number of seconds. Otherwise it runs out of memory on the CPU. I'll submit a PR to avoid this.
