### ISSUE TITLE
IndexError: too many indices for array when running NSynth

### ISSUE THREAD

**Issue by tensorplex** [tensorflow/magenta#1509]
When running NSynth I get the following error:

root@d2b59ff89f7d:/magenta-data# nsynth_generate --checkpoint_path=/magenta-data/models/nsynth/wavenet-ckpt/model.ckpt-200000 --source_path="/magenta-data/input/wav/tensorplex - Rast.wav" --save_path=/magenta-data/output --batch_size=4
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/nsynth/wavenet/masked.py:116: __init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Traceback (most recent call last):
  File "/usr/local/bin/nsynth_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 98, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 85, in main
    batch_data = fastgen.load_batch(batch_files, sample_length=sample_length)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/nsynth/wavenet/fastgen.py", line 150, in load_batch
    batch_data[i] = data[np.newaxis, :, :]
IndexError: too many indices for array

**Comment by jesseengel** [comment]
Hi! I think you're using an old version of magenta, `fastgen.load_batch()` was split in a previous PR. `pip install --upgrade magenta-gpu` should do it.

**Comment by tensorplex** [comment]
Thanks for the quick response @jesseengel ! I am running with docker and on the latest image...

$ docker pull tensorflow/magenta
Using default tag: latest
latest: Pulling from tensorflow/magenta
Digest: sha256:ca8094cc110cd9dd2a4ed0a2650c1c51a5dfe6d1a13279d2832da5b198db72f3
Status: Image is up to date for tensorflow/magenta:latest

**Comment by jesseengel** [comment]
That makes sense, the docker image hasn't been updated since we simplified the build system (removed the need for bazel). It's now a lot easier to use pip to install which is what we recommend.

**Comment by tensorplex** [comment]
@jesseengel got it - thanks, makes sense.

**Comment by paulogaspar** [comment]
@jesseengel Is that still valid? I tried installing from pip and ended up having to install bazel. Anyway, I can't install magenta from pip so I'm also dependent on a docker image. Is there a workaround for this issue?
