### ISSUE TITLE
Onsets and Frames: inference script issue

### ISSUE THREAD

**Issue by jthickstun** [tensorflow/magenta#1530]
Hello,

I ran into an issue following the [inference section](https://github.com/tensorflow/magenta/tree/master/magenta/models/onsets_frames_transcription#inference) of the [readme](https://github.com/tensorflow/magenta/blob/master/magenta/models/onsets_frames_transcription/README.md) instructions for onsets and frames:

`onsets_frames_transcription_infer --examples_path="data/maps_config2_test.tfrecord" --model_dir="train/" --output_dir="train/eval/"`

The code above yields the following error at infer.py, line 148 (full trace attached):

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: length (data type: int64) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[node IteratorGetNext (defined at /home/thickstn/magenta/magenta/models/onsets_frames_transcription/infer.py:135) ]]
```

I'm using your [pre-trained model](https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/maestro_checkpoint.zip) above, but I get the same behavior using my own trained model. The following command successfully produces a transcription of a single file:

`onsets_frames_transcription_transcribe --model_dir="checkpoints/" MAPS_MUS-chpn-p14_ENSTDkAm.wav`

The infer and transcribe scripts have superficially similar data pipelines, except infer takes a tfrecord to construct its dataset (infer.py, line 109) whereas transcribe takes a string wavefile path (onsets_frames_transcription_transcribe.py, line 103). I was able train a model on the MAPS training tfrecord (maps_config2_train.tfrecord) so I don't think I botched the construction of the tfrecord objects (I followed [these](https://github.com/tensorflow/magenta/tree/master/magenta/models/onsets_frames_transcription#maps-dataset-optional) instructions).

Any idea what's gone wrong?

Best,
John

[trace.txt](https://github.com/tensorflow/magenta/files/3179618/trace.txt)

**Comment by cghawthorne** [comment]
I think this might be a bug introduced by our recent preprocessing code changes. Can you try running the script with `--preprocess_examples=True`? If you can confirm that fixes it, I'll send a PR to make that the default.

@asleep FYI

**Comment by jthickstun** [comment]
That fixed it. I ran into another issue at infer.py, line 189: sequences_lib.pianoroll_to_note_sequence expects frame_predictions to be a list of arrays, but the current input is simply an array. I addressed this problem by removing the final zero index in lines 177-181:

```
        frame_probs = prediction_list[0]['frame_probs']
        frame_predictions = prediction_list[0]['frame_predictions']
        onset_predictions = prediction_list[0]['onset_predictions']
        velocity_values = prediction_list[0]['velocity_values']
        offset_predictions = prediction_list[0]['offset_predictions']
```

You'd know better than me whether that's the right fix, but after changing that I got transcription results out that seem reasonable.

Thanks!

**Comment by cghawthorne** [comment]
I think that's due to an incompatibility with how some of our internal code returns results. I'll see if there's a good way to unify the two so it works without that change. Thanks for the report!

**Comment by cghawthorne** [comment]
Can you see if 9e5b51f5d808dc0fb16e50034295a0c54e3620b1 fixes your remaining issues?

**Comment by jthickstun** [comment]
Yes this resolves the indexing issue.
