### ISSUE TITLE
How to work with .wav

### ISSUE THREAD

**Issue by markus-weiss** [tensorflow/magenta#1535]
Hello, 

we want to work with gansynth on our researchproject. We want to train with our own files, but they are only in .wav- format. And now we ask ourselves how to convert .wav into tfrecord files. We found some solutions but they don't work. How do you convert your files to tfrecord, if you do that?

Kind regards,

Markus

**Comment by prakilambi** [comment]
check out https://github.com/IBM/tensorflow-hangul-recognition/blob/master/tools/convert-to-tfrecords.py
It converts image to frecord but can be implemented for wav files by changing the example format to store wav data instead of raw image data.

**Comment by jesseengel** [comment]
Sorry there's no public data ingestion pipeline, we used the tfrecords from the nsynth dataset. Here's a [gist](https://gist.github.com/jesseengel/dedb8bc19212d4b982fb51f879728a0d) that should convert a single wav file to a tfrecord. With the previous link you should be able to make a record out of a whole lot of them.

**Comment by itsKaspar** [comment]
hi, i'm trying to do the same thing, but can't figure out how to use @prakilambi's example 
because the script expects a .csv input whereas I have a folder full of .wav files that do not need labels.

I tried concatenating all of them with ffmpeg to use the small gist instead but I get an obvious overflow error

**Comment by markus-weiss** [comment]
Hey there, sorry for my late answer but we switched to another concept to convert our files. At first we convert the wavefiles to images of log magnitude and phase, after that we read it into our GAN. At the moment we have no new findings.
 
https://github.com/markus-weiss/AVGAN
https://github.com/markus-weiss/AVGAN/blob/master/AVGAN_Paper.pdf
https://colab.research.google.com/drive/1KSErEzANTaUr3Br7bAO848Pd4K-3oONA
