### ISSUE TITLE
gansynth: how do you convert the Generator output to the audio waveform ?

### ISSUE THREAD

**Issue by shamanez** [tensorflow/magenta#1541]

**Comment by jesseengel** [comment]
First, check out the demo for generating audio in case you haven't already, it has examples: https://colab.sandbox.google.com/notebooks/magenta/gansynth/gansynth_demo.ipynb

More specifically, `data_helper.data_to_waves()` is what you want https://github.com/tensorflow/magenta/blob/master/magenta/models/gansynth/lib/model.py#L381
