### ISSUE TITLE
bazel test //magenta/... error

### ISSUE THREAD

**Issue by AragakiSaro** [tensorflow/magenta#1543]
My environment is Ubuntu18.04,bazel 0.26.0 
The error reads like:
root@ecs-60f5:~/magenta# bazel test //magenta/...
ERROR: error loading package 'magenta/music/alignment': Unable to find package for @com_google_protobuf//:protobuf.bzl: The repository '@com_google_protobuf' could not be resolved.
INFO: Elapsed time: 0.191s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: magenta/music/alignment
I'm sorry if it's a foolish question.

**Comment by cghawthorne** [comment]
Hi @AragakiSaro, we no longer user Bazel for the main Magenta repo. Could you please sync your git client and follow the new installation instructions in our [README](/tensorflow/magenta)?
