### ISSUE TITLE
On onset&frames, how could I get the GraphDef File by the pre-trained checkpoint?

### ISSUE THREAD

**Issue by wwpww** [tensorflow/magenta#1553]
On onset&frames, how could I get the GraphDef File by the pre-trained checkpoint? Do I have to retrain the model?

**Comment by cghawthorne** [comment]
I haven't done much with GraphDef files, but the easiest way might be to just modify one of the train or inference scripts to call  [as_graph_def](https://www.tensorflow.org/guide/extend/model_files#graphdef) on the graph as soon as it's finished being created.
