### ISSUE TITLE
MusicVae - Is music_vae_create_dataset not needed?

### ISSUE THREAD

**Issue by ys23** [tensorflow/magenta#1577]
Hello
I tried to train own model on MusicVae.
But I can't find music_vae_create_dataset.py.
Is music_vae_create_dataset not needed?
Or is there other ways?

I already succeeded to train own models on others such as Melody RNN.

**Comment by adarob** [comment]
MusicVAE does preprocessing on the fly so you don't need a create_dataset script. Please see the instructions here: https://github.com/tensorflow/magenta/tree/master/magenta/models/music_vae#training-your-own-musicvae
