### ISSUE TITLE
How to set a different note density?

### ISSUE THREAD

**Issue by BjoernBerlin** [tensorflow/magenta#1578]
Probably a newcomer's question, but how do I set a different note density? I probably have to set a new argument for performance_controls, but I'm stuck... (alternatively: is there a group I can adress those kind of questions to?)

**Comment by adarob** [comment]
Which model are you referring to? PerformanceRNN? If so, @iansimon should be able to help you.

**Comment by iansimon** [comment]
First, make sure you're using the `density_conditioned_performance_with_dynamics` (or `multiconditioned_performance_with_dynamics`) config, and the corresponding checkpoint available [here](https://github.com/tensorflow/magenta/tree/master/magenta/models/performance_rnn#pre-trained).

Then, in the call to `performance_rnn_generate`, set the `--notes_per_second` flag to the desired note density.  It's quantized to powers of 2, so in essence only responds to doublings or halvings of note density.

**Comment by BjoernBerlin** [comment]
Thank you. I was referring to performance_sequence_generator and the colab-notebook. I wanted to set "notes_per_second" in generator_options and failed... it takes the value from control_signals, which I don't know how to adress
