### ISSUE TITLE
Is the "Magenta Studio Groove" built on GrooVAE and Groove Midi Dataset?

### ISSUE THREAD

**Issue by IvanWeiYR** [tensorflow/magenta#1584]
Hi, I want to use the GrooVAE to make some drum piece sounds more like the drummer performance. But I also found a tool released by Magenta Studio called "Groove" here [magenta.tensorflow.org/studio/standalone](url). But it didn't mention clearly that whether it was built by GrooVAE and Groove Midi Dataset or not. 

So may I know the model and dataset behind that tool?  Because if it is built on GrooVAE and Groove Midi Dataset, then that tool and the function it provided are exactly what I am looking for.

**Comment by adarob** [comment]
Yes, that tool does use GrooVAE and the Groove dataset.

**Comment by IvanWeiYR** [comment]
@adarob Thank you so much!
