### ISSUE TITLE
PIP install issue with networkx

### ISSUE THREAD

**Issue by Ceebox** [tensorflow/magenta#1586]
I try to pip install with latest pip and python 3.6.8 and I get this error:
``  ERROR: Failed building wheel for networkx
  Running setup.py clean for networkx
Failed to build networkx
ERROR: scikit-image 0.15.0 has requirement networkx>=2.0, but you'll have networkx 1.8.1 which is incompatible.

Please comment if you need more info

**Comment by Ceebox** [comment]
I'd really appreciate any contribution, as I need this for a ml project for the end of the week

**Comment by cghawthorne** [comment]
Can you include the full output of your pip install command? Does it make any difference if you include the -U (upgrade) flag?

**Comment by tongyuantongyu** [comment]
Hi! I also have the same problem and I find a solution.
You see [here](https://github.com/tensorflow/magenta/blob/77f867b3821577f3642f34be90e7a4f149e1fe73/setup.py#L61) that magenta tries to install sonnet as a dependency, but I found that it actually means to install another library named dm-sonnet, so you can correct it and manually run setup.py to install it.
By the way it will tend to install tensorflow 2.0 which is incompatible with
magenta itself, so I have to manually uninstall the 2.0 version and install 1.14.0 version (I'm not sure if there is some better way). After that it should work. (with bunch of deprecate warning though)
I hope this will help.

**Comment by cghawthorne** [comment]
Can you try again with the latest version of the pip package in a clean environment (e.g., a fresh conda env)? For now, we've pinned everything to TensorFlow 1.x until we have better support for 2.0. This should fix some of the issues you were seeing.

**Comment by tongyuantongyu** [comment]
> Can you try again with the latest version of the pip package in a clean environment (e.g., a fresh conda env)? For now, we've pinned everything to TensorFlow 1.x until we have better support for 2.0. This should fix some of the issues you were seeing.

Yes now pip can pick the right version (1.14.0) of tensorflow, but the problem about sonnet is still present.
I checked the code and the 'sonnet' package should mean to this:
https://github.com/deepmind/sonnet
https://pypi.org/project/dm-sonnet/
but when you ask pip to install 'sonnet', pip will (at least on my computer) try to install this:
https://pypi.org/project/sonnet/
This package has a dependence networkx==1.8.1, which occurs this issue.

**Comment by cghawthorne** [comment]
Ah, I understand now. Sorry for the confusion. I'll get that fixed.
