### ISSUE TITLE
Compatible version for TF2

### ISSUE THREAD

**Issue by Lamicc** [tensorflow/magenta#1588]
Will there be a compatible version for TF2?

**Comment by DBraun** [comment]
https://github.com/tensorflow/magenta/blob/0af29601b9d7e499af83352a9df3e97c7da63cbd/setup.py#L71
 It's not the biggest problem, but I think this info should be front and center in the README.

**Comment by cghawthorne** [comment]
We're tracking TF2 compatibility in #1594, so closing this issue.

Feel free to send a PR to update the README.
