### ISSUE TITLE
HELP! Some questions about training onsets&frames model

### ISSUE THREAD

**Issue by wwpww** [tensorflow/magenta#1589]
I just want to try to train this model (just try using CPU, I know it's quite slow )
I set up the full Development Environment 
I run transcription locally in this environment using command, and it works
Then I download the pre-generated copy of the TFRecord files
When I use the command to train transcription model using the training TFRecord file generated from the MAESTRO dataset
Some errors occur
`ValueError: Dimension 0 in both shapes must be equal, but are 1 and 8. Shapes are [1,?,88] and [8,?,88]. for 'concat_2' (op: 'ConcatV2') with input shapes: [8,?,88,1], [1,?,88,1], [8,?,88,1], [] and with computed input tensors: input[3] = <3>.`
So how to fix this pronlem?
Could anyone tell me?
Thanks

**Comment by cghawthorne** [comment]
Sorry you're having that error. Can you paste the full command line you're using and the full output of the command?

**Comment by wwpww** [comment]
> Sorry you're having that error. Can you paste the full command line you're using and the full output of the command?
![1](https://user-images.githubusercontent.com/48265203/65210850-2d9f2280-dacf-11e9-8e62-ec4bcdf630ce.png)
![2](https://user-images.githubusercontent.com/48265203/65210851-3263d680-dacf-11e9-8538-1c37704a0c76.png)
![3](https://user-images.githubusercontent.com/48265203/65210854-355ec700-dacf-11e9-93f5-5bb1f32b533f.png)
![4](https://user-images.githubusercontent.com/48265203/65210857-37c12100-dacf-11e9-8f64-7040ea26fae5.png)
![5](https://user-images.githubusercontent.com/48265203/65210859-3b54a800-dacf-11e9-9959-c2f1514248d7.png)

**Comment by wwpww** [comment]
@cghawthorne

**Comment by cghawthorne** [comment]
Thanks for the info. I've reproduced the problem locally and will look into it!

**Comment by wwpww** [comment]
> Thanks for the info. I've reproduced the problem locally and will look into it!

Do you have any clues?

**Comment by cghawthorne** [comment]
The new pip package (version 1.1.6) should have a fix for this problem.
