### ISSUE TITLE
I would like to write a review of Boulanger-Lewandowski  2012 (http://www-etud.iro.umontreal.ca/~boulanni/ICML2012.pdf)

### ISSUE THREAD

**Issue by dshieble** [tensorflow/magenta#159]
I would like to write a review of [Boulanger-Lewandowski 2012](http://www-etud.iro.umontreal.ca/~boulanni/ICML2012.pdf). This paper describes a few powerful sequential generative models, such as the RNN-RBM.

The architecture is simple but brilliant: at each timestep, the RNN specifies the parameters of an RBM, which then generates musical notes via Gibbs sampling. The architecture in [Graves 2013](http://arxiv.org/pdf/1308.0850v5.pdf) is similar to the RNN-RBM and Graves 2013 references Boulanger-Lewandowski 2012

I also have reimplemented the RNN-RBM model in TensorFlow, and would be happy to share and document my code in the review. There does already exist a Theano implementation of this model [here](http://deeplearning.net/tutorial/rnnrbm.html). 

As per the instructions on the reviews page, I am filing an issue with this request. I'm looking forward to hearing back.

**Comment by cinjon** [comment]
That sounds fantastic. We would welcome that Dan.
