### ISSUE TITLE
Onset and Frames is broken on Google Colab and Locally

### ISSUE THREAD

**Issue by fayezsalka** [tensorflow/magenta#1595]
Hi,

It seems that Onset and Frames is broken when trying to running it locally and on the provided google colab project. Whenever I try to run a prediction i get the error 

```
  File "/Users/Machine Learning/magenta/models/onsets_frames_transcription/model.py", line 402, in model_fn
    sequence_label=labels.note_sequence,

AttributeError: 'NoneType' object has no attribute 'note_sequence'

```
Any help is appreciated

**Comment by cghawthorne** [comment]
Sorry it was broken for a while. Both the colab and local script should be fixed as of today. If the local script isn't working, can you verify that you have the latest version of the pip package?
