### ISSUE TITLE
Unable to run the example

### ISSUE THREAD

**Issue by thEpisode** [tensorflow/magenta#1604]
Hi, I followed the instructions inside readme, I installed Tensorflow 2 and I cannot run the example:

`python magenta/models/melody_rnn/melody_rnn_generate.py --config... `

Logs:

> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/thepisode/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> WARNING:tensorflow:From /home/thepisode/miniconda3/lib/python3.7/site-packages/magenta/music/note_sequence_io.py:60: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.
> 
> WARNING:tensorflow:From /home/thepisode/miniconda3/lib/python3.7/site-packages/magenta/pipelines/statistics.py:132: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.
> 
> WARNING:tensorflow:
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> For more information, please see:
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
>   * https://github.com/tensorflow/addons
>   * https://github.com/tensorflow/io (for I/O related ops)
> If you depend on functionality not listed there, please file an issue.
> 
> WARNING:tensorflow:From magenta/models/melody_rnn/melody_rnn_generate.py:250: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.
> 
> WARNING:tensorflow:From magenta/models/melody_rnn/melody_rnn_generate.py:221: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
> 
> W1010 12:37:22.001311 139649976895232 deprecation_wrapper.py:119] From magenta/models/melody_rnn/melody_rnn_generate.py:221: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
> 
> Traceback (most recent call last):
>   File "magenta/models/melody_rnn/melody_rnn_generate.py", line 254, in <module>
>     console_entry_point()
>   File "magenta/models/melody_rnn/melody_rnn_generate.py", line 250, in console_entry_point
>     tf.app.run(main)
>   File "/home/thepisode/miniconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/thepisode/miniconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/home/thepisode/miniconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "magenta/models/melody_rnn/melody_rnn_generate.py", line 230, in main
>     config = melody_rnn_config_flags.config_from_flags()
>   File "/home/thepisode/miniconda3/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_config_flags.py", line 110, in config_from_flags
>     'Exactly one of `--config` or `--melody_encoder_decoder` must be '
> magenta.models.melody_rnn.melody_rnn_config_flags.MelodyRnnConfigError: Exactly one of `--config` or `--melody_encoder_decoder` must be supplied.

I need to install some version of Python and Tensorflow to use it?

**Comment by adarob** [comment]
Magenta is not 2.0-compatible yet. Please try with 1.15 and let us know if you still have issues!
