### ISSUE TITLE
gansynth: replicating results

### ISSUE THREAD

**Issue by lonce** [tensorflow/magenta#1607]
Jesse and All,
      It looks like the training with 'best' configs/mel_prog_hires.py should train a model similar to the one provided in the checkpoints directory of this repository. From what I can tell, the training is on acoustic only (by default), notes in [24, 84], experiments.json has the "right" parameters, and my 88 hour run on a V100 completes 11M images and 12 stages.
   However, when I generate with the model I trained (exactly the way I do with the checkpoint model in this repository) using a midi file, I don't get those sweet instruments and interpolations. I get a properly-pitched rendering on a bellish instrument that doesn't change through the piece. 
    So my question is should I expect training with configs/mel_prog_hires to produce a model with generate capabilities comparable to your checkpointed model?

Thanks,
                   - lonce

**Comment by jesseengel** [comment]
Ah, I think I found it. I retrained a model on GCP to see what you were talking about. It trains fine, but I noticed the generated instruments were mostly organs (which is the majority of "electronic" instruments in the nsynth dataset).  Sure enough the code currently is filtering for the electronic subset (which has less diversity). I'll submit a PR, but for now you can just change this line: https://github.com/tensorflow/magenta/blob/0afca8f87dc8af4ef71ded5f680014d00d3da625/magenta/models/gansynth/lib/datasets.py#L114 from filter for index 1 to filtering for index 0.
