### ISSUE TITLE
GANSynth memory requirements

### ISSUE THREAD

**Issue by ahihi** [tensorflow/magenta#1611]
hi,

i am attempting to run GANSynth on the Raspberry Pi 4 with 4GB RAM, but during generation it exits with `LLVM ERROR: out of memory`.

i'm using `generate_samples_from_z()` with a single latent vector and single pitch, and have tried reducing `max_audio_length` down to 4000, but still run out of memory. are there any other parameters i could try tweaking to reduce memory usage, or is this a no go?

**Comment by jesseengel** [comment]
You should make sure your batch size is 1 (1 input z), but unfortunately, for the python version there's not much more to do  beyond that as GANSynth was trained on fixed-length sequences. 

We did create a javascript version: https://github.com/tensorflow/magenta-js/blob/master/music/demos/gansynth.html
Used in this demo:
https://ganharp.ctpt.co/

That might suit your needs.
