### ISSUE TITLE
issue magenta/models/sketch_rnn/model.py

### ISSUE THREAD

**Issue by Pauladds** [tensorflow/magenta#1618]
When I tried to run this https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn
I have the next issue: ~/magenta/magenta/models/sketch_rnn/model.py in get_default_hparams()
     64       augment_stroke_prob=0.10,  # Point dropping augmentation proportion.
     65       conditional=True,  # When False, use unconditional decoder-only model.
---> 66       is_training=True  # Is model training? Recommend keeping true.
     67   )
     68   return hparams

TypeError: hparams() got an unexpected keyword argument 'data_set'
I don't know what happend there

**Comment by Pauladds** [comment]
The problem is "tf.contrib.training.HParams" (from magenta/magenta/models/sketch_rnn/model.py) 
![Capture](https://user-images.githubusercontent.com/38189240/68376718-5b0c6200-0149-11ea-8755-428aed13575a.PNG)
does not exist so I don't know what I need to put to replace

**Comment by adarob** [comment]
Can you make sure you're using TF 1.15? HParams is removed in TF 2.0.

**Comment by Pauladds** [comment]
Yes, now i'm using TF1.15 and it works. Thank you
