### ISSUE TITLE
Onsets frames model: Discrepancy in parameter names

### ISSUE THREAD

**Issue by SargamMenghani** [tensorflow/magenta#1620]
Hello,

We are trying to fine-tune onsets_and_frames_transcription checkpoint model using our own data. While trying to load the checkpoint version (from here: https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/maestro_checkpoint.zip) and fine-tuning it, we are running into the following error: 
```
2 root error(s) found.
  (0) Not found: Key training/beta1_power not found in checkpoint
     [[node save/RestoreV2 (defined at /home/nisarg/inhouse_research/imusic/third_party_repos/magenta_env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Not found: Key training/beta1_power not found in checkpoint
     [[node save/RestoreV2 (defined at /home/nisarg/inhouse_research/imusic/third_party_repos/magenta_env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
     [[save/transpose/Rank/_339]]
```
We tried inspecting the provided checkpoint file and found that it does indeed have the beta1_power parameter. A snippet of the output:
```
beta1_power (DT_FLOAT) []
beta2_power (DT_FLOAT) []
```
But the parameter name is different from what the training code is expecting (`training/beta1_power`). We are not sure why that is the case. Do you have any suggestions?

Thank you in advance!

**Comment by cghawthorne** [comment]
I suspect that's due to some training changes I made in 982740ee6e56d674e3f220d7bf215ae4132c9c1c. Sorry about the incompatibility, I've mostly paid attention to making the checkpoints compatible for inference. You could try removing the 'training' parameter in the call to optimize_loss, edit the checkpoint itself, or sync to before that commit.

**Comment by SargamMenghani** [comment]
Thank you so much for your suggestions!

Changing the call to optimize_loss to how it was before the [982740e](https://github.com/tensorflow/magenta/commit/982740ee6e56d674e3f220d7bf215ae4132c9c1c) commit helped resolve the problem.

Specifically, changing this snippet: https://github.com/tensorflow/magenta/blob/177416c365bf2d6eea3bb38c1bd2d2a54acf8652/magenta/models/onsets_frames_transcription/model.py#L485-L496 to this 
```
adam_optimizer = tf.train.AdamOptimizer(
                        learning_rate=hparams.learning_rate)
train_op = slim.learning.create_train_op(
          loss,
          adam_optimizer,
          clip_gradient_norm=hparams.clip_norm,
          summarize_gradients=True,
          variables_to_train=None)
``` 
worked!
