### ISSUE TITLE
Problem with encoder 

### ISSUE THREAD

**Issue by Pauladds** [tensorflow/magenta#1624]
I tried to train the model (sketch_rnn_train.py) with pig.npz and to test it I used (https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN.ipynb) when I get the next problem: 
![download](https://user-images.githubusercontent.com/38189240/68851933-1fd4da80-06d7-11ea-8688-74547d549eae.png)

**Comment by nirajpandkar** [comment]
Hey @Pauladds Did you manage to fix this? I am still getting the same error only now it's - 
```
ValueError: Cannot feed value of shape (1, 251, 5) for Tensor u'vector_rnn_1/Placeholder_1:0', which has shape '(1, 76, 5)'
```

Is the input shape hardcoded somewhere? Can't seem to find it.

Thanks,
Niraj

**Comment by Pauladds** [comment]
Hello!
Yes, I solve it! 
In https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN.ipynb
in "encode" function you have : 
![image](https://user-images.githubusercontent.com/38189240/80870544-5adbc200-8ca7-11ea-8a82-c993ee4c5b34.png)
So, inside of that, you have: "to_big_strokes"  and one of the parameters of that function is max_len that by default is 251, and you need to change to the number that you need, in your case 76.
For example, you can write: 
![image](https://user-images.githubusercontent.com/38189240/80870613-e3f2f900-8ca7-11ea-9cb7-f0d33ba88391.png)
I hope you understand it! :)
You´re welcome 
Paula

**Comment by nirajpandkar** [comment]
That actually worked! Thanks a lot @Pauladds 

Had to put in 75 to make it work. Will investigate further as to why this happened. Thanks again!

**Comment by Pauladds** [comment]
I know why it is!
It is because the parameter is prefixed to have the longest input length that you enter in the training dataset (In the case of the example it is 250).
