### ISSUE TITLE
Unable to run Hello Magenta Python example

### ISSUE THREAD

**Issue by qscacheri** [tensorflow/magenta#1630]
I am able to get through step 0 (installing dependencies) but if I try and run step 1, it fails and I get the error: 

`ModuleNotFoundError Traceback (most recent call last)
<ipython-input-2-acbb8b942830> in <module>()
----> 1 from magenta.music.protobuf import music_pb2
      2 
      3 twinkle_twinkle = music_pb2.NoteSequence()
      4 
      5 # Add the notes to the sequence.

ModuleNotFoundError: No module named 'magenta.music.protobuf'
`
I was able to run this example a few weeks ago with no problem. Am I doing something wrong or has something changed?

**Comment by adarob** [comment]
Sorry about that, but the pip package and colab are out of sync. For now, you can should be able to change that line to

`from magenta.protobuf import music_pb2`

**Comment by qscacheri** [comment]
Great thanks!

**Comment by cghawthorne** [comment]
We release a new version of the pip package and the notebook should be working again without any changes.

**Comment by yhb-art** [comment]
这里也出现这样的报错 runfile('C:/Users/Q3288/.spyder-py3/magenta_demo.py', wdir='C:/Users/Q3288/.spyder-py3')
Traceback (most recent call last):

  File ~\.conda\envs\Magenta_env\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\q3288\.spyder-py3\magenta_demo.py:14
    from magenta.protobuf import generator_pb2

ModuleNotFoundError: No module named 'magenta.protobuf'
