### ISSUE TITLE
TypeError : Couldn't build proto file into descriptor pool

### ISSUE THREAD

**Issue by jijiao820** [tensorflow/magenta#1632]
https://colab.research.google.com/notebooks/magenta/hello_magenta/hello_magenta.ipynb#scrollTo=71dgCmmBli-s
on this webpage run Step 1. Making sounds with NoteSequences error:
"TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "music.proto":"

Pls help me ,how to resolve it

**Comment by cghawthorne** [comment]
I'm not able to reproduce this, but I wonder if it's related to a recent package path change we made. Can you try going to the Runtime menu and selecting "Reset all runtimes" and see if that fixes it?

**Comment by jijiao820** [comment]
> I'm not able to reproduce this, but I wonder if it's related to a recent package path change we made. Can you try going to the Runtime menu and selecting "Reset all runtimes" and see if that fixes it?

Thankyou ,I want to know how to find the "Reset all runtimes" menu!

**Comment by jijiao820** [comment]
I try it again today ,It's OK ,so amazing! thank you! But I don't know why the error happened in yestorday
