### ISSUE TITLE
Dockerfile is gone?

### ISSUE THREAD

**Issue by Debdutto** [tensorflow/magenta#1645]
I was looking for the Dockerfile used to publish to docker hub which says `Updated a year ago`

Apparently it used to live at `master/magenta/tools/docker` but seems to be gone now?

**Comment by cghawthorne** [comment]
Yes, we no longer officially support the Docker setup, but you can look in the repo history to see the old file. It probably wouldn't take too much effort for you to get it working again with the current state of the repo.

**Comment by Debdutto** [comment]
Ok thanks. Will try setting it up with docker. 👍

**Comment by robotastic** [comment]
I came here looking for the same thing because I want to create a reproducible build env. The commit removing docker is here in case anyone else needs it: https://github.com/tensorflow/magenta/commit/ee21abf65a576388de3a6af289599a536dd3c7c8
