### ISSUE TITLE
Can't open a .mag file（mono_rnn，lookback_rnn，basic_rnn，attention_rnn）How can I open it？

### ISSUE THREAD

**Issue by yakiyaku** [tensorflow/magenta#1646]
I am using windows 10. I want to open the .mag file described in the following URL, but even if I open it with a text editor such as visualstudio, the conversion is not successful and the characters are garbled. 
[https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn](url)

I set the character code utf-8, but it didn't work. If anyone knows how to convert characters in .mag files, I would appreciate it.

**Comment by adarob** [comment]
Mag files contain binary information and aren't expected to be human-readable.
