### ISSUE TITLE
No module named 'magenta'

### ISSUE THREAD

**Issue by yakiyaku** [tensorflow/magenta#1651]
I wrote the following code as "test.py" using visual studio2019.

# internal imports
import importlib
import magenta.lib
from magenta.lib import melodies_lib
import tensorflow as tf

When I executed without debugging, I got the following error.

ModuleNotFoundError: No module named 'magenta'

I would be grateful if you could tell me the solution.

**Comment by trungtle** [comment]
Make sure you have installed [magenta](https://github.com/tensorflow/magenta/blob/master/README.md) successfully, I think it should fix this.

**Comment by csmith44** [comment]
I ran into the same issue then ran 
source activate magenta 
to activate magenta before installing magenta again in the magenta environment. So:

source activate magenta
pip install magenta

Worked for me!
