### ISSUE TITLE
No matching distribution found for Tensorflow

### ISSUE THREAD

**Issue by cannc4** [tensorflow/magenta#1652]
I've been trying to install magenta on a virtual machine that runs an Alpine Linux with python2 pip (version 19.3.1). 
I managed to install all the libraries as expected but hitting an issue with `pip install magenta`

```
no matching distribution found for tensorflow>=1.12.0 
```

Any thoughts?

**Comment by cannc4** [comment]
Here is what I've been trying in my yml file for the reference
```
- pip install --upgrade pip virtualenv setuptools
  - virtualenv .
  - source bin/activate
  - pip debug --verbose
  - pip install --upgrade pip setuptools wheel
  - pip install six==1.12.0  # temporary fix for astroid compatibility.
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.0rc0-cp27-none-linux_x86_64.whl
  # - pip install magenta==0.4.0
```

**Comment by cghawthorne** [comment]
I would recommend not installing tensorflow from a specific .whl package, but just letting the dependencies in the latest version of the magenta package select the correct version.

**Comment by cannc4** [comment]
I don't think the latest magenta version is supported on Alpine, is it?

**Comment by adarob** [comment]
Try `pip install --upgrade pip`.

**Comment by teleportingtortoise** [comment]
Getting a similar error when trying to install magenta through pip letting it handle dependencies on it's own. This was after trying the suggested `pip install --upgrade pip`

```
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0.0,>=1.15.0 (from magenta) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.0.0,>=1.15.0 (from magenta)
```

**Comment by adarob** [comment]
We are now compatible with tf2
