### ISSUE TITLE
Consider increasing `timeout_factor` for PyAudio in the Onsets and Frames realtime Python demo

### ISSUE THREAD

**Issue by janek** [tensorflow/magenta#1653]
The Python demo for [OnF realtime](https://github.com/tensorflow/magenta/tree/master/magenta/models/onsets_frames_transcription/realtime) was crashing on me, because of a timeout issue in PyAudio. 

Since I heard about problems with PyAudio on macOS Catalina, I first went down the wrong path, instead of just increasing the timeout, and struggled until I got the right idea. The current value for `timeout_factor` is 12 and I found that I need at least 24 for the demo to work (and it works perfectly fine after). Since I have a reasonably fast machine, I thought other people might have the same problem and that it might be sensible to increase the default `timeout_factor` (also because there's not a big downside to doing that).

Tagging @cghawthorne as likely the codeowner. Feel free to disagree and close this. Thank you for all your work!

**Comment by cghawthorne** [comment]
@mtyka any thoughts on this?

**Comment by mtyka** [comment]
I've run into this issue also. Happy to increase it if that helps.
