### ISSUE TITLE
onsets_frames_transcription Create dataset from midi's and wav's no documented

### ISSUE THREAD

**Issue by faniuy** [tensorflow/magenta#1654]
The document and source code of onsets_frames_transcription_create_dataset_maestro.py just read pre-generated tfrecord files from gs://magentadata/datasets/maestro/v1.0.0/

**Comment by cghawthorne** [comment]
Sorry, we should have some better examples for that. In the meantime, you can get a good idea of how the process works by looking at onsets_frames_transcription_create_dataset_maps.
