### ISSUE TITLE
GANSynth training performance

### ISSUE THREAD

**Issue by ahihi** [tensorflow/magenta#1666]
hello,

some questions about optimizing GANSynth training :)

1. is it possible to run on multiple GPUs?
2. when training on a Tesla V100, i see ≤30% GPU utilization as reported by nvidia-smi. it doesn't look like the process is being bottlenecked by CPU or RAM either... is there any way to improve this?

**Comment by jesseengel** [comment]
The code is mostly a documentation of the research paper, and isn't actively used for research at the moment (we're focusing on [DDSP](https://github.com/magenta/ddsp)), so it's unlikely to see any speed improvements on our end. Apologies if it's a bit slow, but a single GPU was sufficient for the experiments in the paper, so we stuck to that :).
