### ISSUE TITLE
A request for Multitrack MusicVAE checkpoint

### ISSUE THREAD

**Issue by fnyhy** [tensorflow/magenta#1669]
Thanks for your work and I am interested in the works about Multitrack MusicVAE. But I can not find the pretrained model about it.

**Comment by adarob** [comment]
It looks like the original model checkpoints are in the magenta-js directories. You can check out the links in https://goo.gl/magenta/js-checkpoints. For any of the multitrack directories, you should be able to download the files `model.ckpt-100000.data-00000-of-00001` and `model.ckpt-100000.index` which you can use to run the Python models.
