### ISSUE TITLE
Wrong link to install TensorFlow in README.md

### ISSUE THREAD

**Issue by fcahoon** [tensorflow/magenta#167]
Here's a patch:

--- README.md~	2016-08-18 22:17:02.067518925 -0500
+++ README.md	2016-08-18 22:19:47.074969525 -0500
@@ -50,7 +50,7 @@
 Next, [install Bazel](http://www.bazel.io/docs/install.html). We recommend the
 latest version, currently 0.3.1.
 
-Finally, [install TensorFlow](http://www.bazel.io/docs/install.html). We require
+Finally, [install TensorFlow](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html). We require
 version 0.10 or later.
 
 After that's done, run the tests with this command:

**Comment by cghawthorne** [comment]
Thanks for catching this!
