### ISSUE TITLE
Deprecated  BUG: onsets_frames_transcription imsave is removed.

### ISSUE THREAD

**Issue by HsunGong** [tensorflow/magenta#1672]
scipy.misc.imsave has been deprecated since `SciPy 1.0`, and was removed in `SciPy 1.2`.

Use `imwrite` in `imageio.imwrite` instead.

Refer: https://stackoverflow.com/questions/57253048/scipy-misc-has-no-attribute-imsave?rq=1

**Comment by cghawthorne** [comment]
Thanks for the heads up, we'd be happy to accept a pull request.
