### ISSUE TITLE
Regarding the availability of the quanitized style transfer models

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/magenta#1680]
Hi. 

I am referring to this tutorial: https://github.com/tensorflow/magenta/blob/master/magenta/models/arbitrary_image_stylization/README.md. 

Towards the very end, there is mentioned of the following models:

![image](https://user-images.githubusercontent.com/22957388/77219885-fa158180-6b5f-11ea-94f2-0ef23698ea2d.png)

I am particularly interested in two of them:
- `style_transform_quantized.tflite`
- `style_transform_calibrated.tflite`

Are they available in a pre-trained capacity?

**Comment by adarob** [comment]
@reiinakano do you have these hosted somewhere?

**Comment by reiinakano** [comment]
Actually, I've never seen this Readme before. @khanhlvg can answer this better probably!

**Comment by khanhlvg** [comment]
Yes we have them hosted on TF.
https://www.tensorflow.org/lite/models/style_transfer/overview

And they are used in our sample apps.
https://github.com/tensorflow/examples/tree/master/lite/examples/style_transfer/android

**Comment by adarob** [comment]
Thanks @reiinakano and @khanhlvg!

**Comment by sayakpaul** [comment]
I looked at the tutorial @khanhlvg mentioned before. I suppose that version (style_transform) is not int8 quantized.
