### ISSUE TITLE
[Question] Example Docker Image ? 

### ISSUE THREAD

**Issue by Mylab6** [tensorflow/magenta#1684]
Hi 

Do you have an example Docker image to run these examples inside of.

Specifically I want to run the Offsets and Frames model inside if a Flask API.

**Comment by cghawthorne** [comment]
We used to have a Docker image, but we no longer maintain it. You can look at the commit where we removed it (ee21abf65a576388de3a6af289599a536dd3c7c8) for more details and a possible starting point for your project.
