### ISSUE TITLE
Runtime error: PS:Is this module depreciated?

### ISSUE THREAD

**Issue by LJWxyz** [tensorflow/magenta#1686]
**No module named 'magenta.protobuf'**

_I have no idea where to find this particular module/script._

**Comment by LJWxyz** [comment]
#uses pip install magenta
to make sure used the upgrade option
#ALL white

**Comment by eps696** [comment]
it seems it moved to `magenta.music.protobuf`

**Comment by LJWxyz** [comment]
THANK YOU VERY MUCH.
