### ISSUE TITLE
Error training latest version of MusicVAE

### ISSUE THREAD

**Issue by Elvenson** [tensorflow/magenta#1699]
#### Steps to reproduce the issue

- Create new magenta environment as well as cloning magenta repo:
`curl https://raw.githubusercontent.com/tensorflow/magenta/master/magenta/tools/magenta-install.sh > /tmp/magenta-install.sh`
`bash /tmp/magenta-install.sh`
`git clone https://github.com/tensorflow/magenta.git`

- Training simple model:
`music_vae_train --config=cat-mel_2bar_small --run_dir=/tmp/cat-mel_2bar_small/ --mode=train --examples_path=data/notesequences.tfrecord`

#### Expected results:

- Training loss and global_step print on console.

#### Actual output:

- `line 123, in _get_input_tensors
    iterator = dataset.make_one_shot_iterator()
AttributeError: 'PrefetchDataset' object has no attribute 'make_one_shot_iterator'`

**Comment by adarob** [comment]
Can you try `pip install https://github.com/tensorflow/magenta/archive/master.zip`?

**Comment by willfenton** [comment]
I'm having the same issue, just tried `pip install https://github.com/tensorflow/magenta/archive/master.zip` and got the same error.

**Comment by willfenton** [comment]
Update: replacing `iterator = dataset.make_one_shot_iterator()` with `iterator = tf.data.make_one_shot_iterator(dataset)` seems to have fixed this. 

Running into this error now: #1622

**Comment by adarob** [comment]
@willfenton do you want to make a PR or should I make that change? I'm looking into the second issue now, but i think we just have to add back disabling autograph until we can move to tf 2.x.

**Comment by adarob** [comment]
@gauravmishra the get_dataset test you added would ideally catch this autograph issue. I think you need to actually make a simple DataConverter instead of mocking the whole thing.
