### ISSUE TITLE
Trying to use onset_frames_transcription on Windows

### ISSUE THREAD

**Issue by defnotanengineer** [tensorflow/magenta#1707]
Hi,

I'm having problems using the onset_frames_transcription on Windows, when I try to use the command as guided, this is what I get :

```
'MODEL_DIR' is not recognized as an internal or external command,
operable program or batch file.
```
and then the script executes and says this at the end
```
  File "c:\users\kairo\miniconda3\lib\ntpath.py", line 291, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This is what I'm copy pasting in the Windows cmd, as per the [readme ](https://github.com/tensorflow/magenta/tree/master/magenta/models/onsets_frames_transcription#transcription-script)  instructions :
```
MODEL_DIR=C:\Users\kairo\Downloads\maestro_checkpoint\train
onsets_frames_transcription_transcribe \
  --model_dir="${CHECKPOINT_DIR}" \
  <piano_recording1.wav>
```

I don't know what I'm doing wrong and where to investigate, so I would love if you guys could help me, thank you in advance

**Comment by cghawthorne** [comment]
Hi @defnotanengineer, I'm not familiar with exactly how the Windows command line interprets those commands. I'd suggest using a Linux virtual machine or cloud instance.

**Comment by defnotanengineer** [comment]
> Hi @defnotanengineer, I'm not familiar with exactly how the Windows command line interprets those commands. I'd suggest using a Linux virtual machine or cloud instance.

I ended up using a ubuntu terminal in Windows and found how to launch the command so that it would work for me (with everything in the same line), like this : 

`onsets_frames_transcription_transcribe --model_dir="C:\Users\kairo\Downloads\maestro_checkpoint\train" C:\Users\kairo\Desktop\1.wav --hparams=use_cudnn=false`

**Comment by defnotanengineer** [comment]
Actually I didn't use Ubuntu because it couldn't install the right version of tensorflow, even after many tries with many pip and python versions, so I just had it working in Windows

**Comment by samar-fathallah** [comment]
what did you write exactly on windows to run the model plz??
