### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by suphysis** [tensorflow/magenta#1714]
Hello there,

I'm experimenting with the pianoroll_rnn_nade model (CPU) and have successfully generated the notesequences.tfrecord to start training.  But when I try (with default parameters):

> pianoroll_rnn_nade_train --run_dir=/Users/gustavodiazjerez/Metaludio/logdir --sequence_example_file=/Users/gustavodiazjerez/Metaludio/tmp/notesequences.tfrecord --hparams="batch_size=128, rnn_layer_sizes=[128]" --num_training_steps=2000

I always get a segmentation fault:

> INFO:tensorflow:Starting training loop...
I0503 12:28:53.464735 140736517456832 events_rnn_train.py:76] Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
I0503 12:28:53.464906 140736517456832 basic_session_run_hooks.py:541] Create CheckpointSaverHook.
WARNING:tensorflow:From /Users/gustavodiazjerez/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0503 12:28:54.724611 140736517456832 deprecation.py:323] From /Users/gustavodiazjerez/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Graph was finalized.
I0503 12:28:54.787981 140736517456832 monitored_session.py:240] Graph was finalized.
2020-05-03 12:28:54.788360: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-03 12:28:54.798875: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe7ee37d490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-03 12:28:54.798894: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:Running local_init_op.
I0503 12:28:55.473730 140736517456832 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0503 12:28:55.670964 140736517456832 session_manager.py:502] Done running local_init_op.
WARNING:tensorflow:From /Users/gustavodiazjerez/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py:882: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0503 12:28:55.886166 140736517456832 deprecation.py:323] From /Users/gustavodiazjerez/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py:882: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Fatal Python error: Segmentation fault

I've tried different batch sizes, etc., but nothing seems to work.  Any ideas?

Thanks

Gustavo

**Comment by suphysis** [comment]
These are my specs:

MacOS 12.6 (Sierra)
Python 3.7.7

**Comment by cghawthorne** [comment]
This type of error usually indicates a problem with your TensorFlow installation. You could try reinstalling it in a fresh python environment. Or it could be that TensorFlow is compiled with options not supported by your processor. To fix this, you could build your own copy of TensorFlow, or just try things out on a virtual machine (e.g., GCP, AWS, etc.).

**Comment by suphysis** [comment]
Thank you.  I tried with a fresh install of Tensorflow and it didn't work, I even tried with earlier versions of Magenta/Python but nothing seems to work.  Building Tensorflow is out of my reach, so my last chance is trying the VM.  If anyone has this problem and solves it please let me know!

**Comment by suphysis** [comment]
SOLVED: After trying millions of things, including recompiling Tensorflow, etc., I realized I was missing an intermediate step: generating the training_pianoroll_tracks.tfrecord files before training...ah well, stupid of me.  Now it's working and training properly :)))
