### ISSUE TITLE
How to run Onset Frames

### ISSUE THREAD

**Issue by lalisalala** [tensorflow/magenta#1720]
Hi,
I am a beginner to this, so sorry if the question is stupid.
But how do I simply run the piano transcription with the existing maestro checkpoint? 
I know there is an instruction, but I do not understand what to do .
After I downloaded the checkpoint and extracted the files into a directory, what do I need to do in the code in order to upload my own piano .wav file for it to transcribe?

Can someone give me an idiotproof instruction?
That would help me out a lot.

thank you :D

**Comment by cghawthorne** [comment]
Hi @lalisalala. There are instructions on how to use the scripts here: https://github.com/tensorflow/magenta/blob/master/magenta/models/onsets_frames_transcription/README.md

The easiest possible way to use it is from our Javascript version: https://goo.gl/magenta/piano-scribe

And only slightly more difficult would be from the colab: https://goo.gl/magenta/onsets-frames-colab

I hope one of those works for you!
