### ISSUE TITLE
Colabs produce Environament Errors, Please help!

### ISSUE THREAD

**Issue by asigalov61** [tensorflow/magenta#1728]
Hey guys!

Both colabs for MuseVue are giving me many Environment Errors, Please help!

ERROR: dm-sonnet 1.36 has requirement tensorflow-probability<0.9.0,>=0.8.0, but you'll have tensorflow-probability 0.7.0 which is incompatible.
ERROR: google-api-core 1.17.0 has requirement google-auth<2.0dev,>=1.14.0, but you'll have google-auth 1.7.2 which is incompatible.
ERROR: google-cloud-spanner 1.13.0 has requirement google-cloud-core<2.0dev,>=1.0.3, but you'll have google-cloud-core 1.0.2 which is incompatible.
ERROR: apache-beam 2.20.0 has requirement dill<0.3.2,>=0.3.1.1, but you'll have dill 0.3.0 which is incompatible.
ERROR: apache-beam 2.20.0 has requirement oauth2client<4,>=2.0.1, but you'll have oauth2client 4.1.3 which is incompatible.
ERROR: apache-beam 2.20.0 has requirement python-dateutil<3,>=2.8.0, but you'll have python-dateutil 2.5.3 which is incompatible.
ERROR: proto-google-cloud-datastore-v1 0.90.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.3 which is incompatible.
ERROR: gym 0.14.0 has requirement cloudpickle~=1.2.0, but you'll have cloudpickle 1.3.0 which is incompatible.
ERROR: googledatastore 7.0.2 has requirement oauth2client<4.0.0,>=2.0.1, but you'll have oauth2client 4.1.3 which is incompatible.

**Comment by adarob** [comment]
This is now fixed for g.co/magenta/musicvae-colab. @iansimon is working on the multitrack colab.
