### ISSUE TITLE
CoLab MusicVAE SyntaxError & AttributeError

### ISSUE THREAD

**Issue by Z-QIAO** [tensorflow/magenta#1731]
Hi there,

I still have issues on the MusicVAE example there from the setup
[https://colab.research.google.com/notebooks/magenta/music_vae/music_vae.ipynb](https://colab.research.google.com/notebooks/magenta/music_vae/music_vae.ipynb)

```WARNING: Logging before flag parsing goes to stderr.
W0526 11:38:44.626660 140652784363392 tf_compat.py:73] TFDS is going to drop Python 2 support. Please update to Python 3.
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_datasets/core/api_utils.py", line 49
    wrapped: None,
           ^
SyntaxError: invalid syntax
```

The same for the rest part.

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-6b0da3a4e082> in <module>()
      4 for ns in mel_input_seqs:
      5   extracted_mels.extend(
----> 6       mel_2bar_config.data_converter.to_notesequences(
      7           mel_2bar_config.data_converter.to_tensors(ns)[1]))
      8 for i, ns in enumerate(extracted_mels):

AttributeError: 'OneHotMelodyConverter' object has no attribute 'to_notesequences
```

I am very sorry about that, I cannot figure out the update or how to apply it from last week. Thanks very much indeed

**Comment by adarob** [comment]
Please try refreshing. It looks like you're seeing out-of-date code.

**Comment by adarob** [comment]
Ah nevermind. It looks like the change has not made it to prod yet for some reason. I'm going to move the colab into GitHub so we won't have this issue in the future.

**Comment by adarob** [comment]
Please try https://colab.research.google.com/github/magenta/magenta-demos/blob/master/colab-notebooks/MusicVAE.ipynb

It will give you a warning for now that it's not authored by Google but this will go away in a day or so.

**Comment by Z-QIAO** [comment]
Thanks very much Adam! It works perfectly now!
