### ISSUE TITLE
[Question] is the MAESTRO checkpoint for onset frames transcription trained with augmented data?

### ISSUE THREAD

**Issue by avikj** [tensorflow/magenta#1736]
In the MAESTRO paper, it mentions that data was augmented with pitch shift, pink noise, reverb, and compression for training, but that some results were reported on a model trained without augmentation. Is the model in onsets_frames_dataset_maestro_v1.0.0.zip trained with or without augmentation?

Thanks

**Comment by cghawthorne** [comment]
That model was trained with augmentation.
