### ISSUE TITLE
ImportError: cannot import name melody_rnn_graph

### ISSUE THREAD

**Issue by tanemaki** [tensorflow/magenta#207]
After updating my repos to the latest version (1e4ca2f57cb7e998bff448c11d88600dfccfa46c), I start getting the following errors. Almost identical errors can be generated by running the folllwing: basic_rnn_train, lookback_rnn_train, or attention_rnn_train.

```
Traceback (most recent call last):
  File "/Users/makoto/git/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 37, in <module>
    import basic_rnn_graph
  File "/Users/makoto/git/magenta/magenta/models/basic_rnn/basic_rnn_graph.py", line 19, in <module>
    from magenta.models.shared import melody_run_graph
ImportError: cannot import name melody_rnn_graph
```

**Comment by adarob** [comment]
Can you share the command you are giving that leads to these errors? Have you rebuilt your binaries with bazel build?

**Comment by tanemaki** [comment]
Thanks Adam,

The problem has solved!
The import error has disappeared after rebuilding my binaries as follows.

```
bazel build //magenta/models/${RNN_TYPE}:${RNN_TYPE}_train    # This line is added

./bazel-bin/magenta/models/$RNN_TYPE/${RNN_TYPE}_train --run_dir=$RUN_DIR --sequence_example_file=$TRAIN_DATA --hparams=$HPARAMS --num_training_steps=$NUM_TRAINING_STEPS &
```

It was my bad.
Thanks for your help ;)

Makoto
