### ISSUE TITLE
Midi files with duplicate time signature events are discarded

### ISSUE THREAD

**Issue by jbloit** [tensorflow/magenta#208]
Reporting a case where midi files were created from within Ableton live (with the "export clip as midi" functionality). This seems to create midi files where the same time signature event is written twice to the midi file, which is currently probably being interpreted as a time signature change by magenta, and thus discarded form the training data set. 

[lullabies.zip](https://github.com/tensorflow/magenta/files/465644/lullabies.zip)

**Comment by adarob** [comment]
Thanks for reporting jbloit. Dan, can you look into this?

**Comment by adarob** [comment]
Fixed!
