### ISSUE TITLE
tmp file holding midi

### ISSUE THREAD

**Issue by vmeade** [tensorflow/magenta#220]
How do I access the /tmp file, where the midi's go after being generated?

**Comment by elburz** [comment]
Were you able to find it based on the other discussion? 

https://github.com/tensorflow/magenta/issues/221

**Comment by elburz** [comment]
I just ran one of the other examples and think I know where you're stuck on this one. On the default example on the front page, they took this piece of code

`bazel run //magenta/models/lookback_rnn:lookback_rnn_generate -- \
--bundle_file=/magenta-models/lookback_rnn.mag \
--output_dir=/magenta-data/lookback_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"
`

And the person who wrote it made the `--output_dir=` match the directory in the earlier steps when you launched the instance with `docker run -it -p 6006:6006 -v /tmp/magenta:/magenta-data tensorflow/magenta`. So you see when you ran the container, you made the shared folder `:/magenta-data`.

In the examples on the other pages, the `--output_dir=` is still set to tmp like in this example from the basic_rnn realm

`bazel run //magenta/models/basic_rnn:basic_rnn_generate -- \
--bundle_file=${BUNDLE_PATH} \
--output_dir=/tmp/basic_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"`

So you'd want to change the `/tmp/basic_rnn/generated` to be `/magenta-data/basic_rnn/generated` or whatever you designated the shared folder as when you boot the container.

**Comment by elburz** [comment]
Made a note about my above comment in #224

**Comment by vmeade** [comment]
Unfortunately not. I think it's something to do with the nature of a Windows 7 Path that Magenta recognizes but doesn't compute...

I'm just reading your message now... okay I'm going try this. 

This I'm thinking I'm understanding, this would explain the missing link between the Docker folder and my local machine. I'll see if I can configure it right and get success.

I didn't believe I had the knowledge power to set this up but I'm literally 95% of the way through, so if I get this to work I'll be happy and proud.

**Comment by elburz** [comment]
We'll get you there! If you've got your shared folder working then I think it might be a case of updating the output path in the bazel commands. 

An easy way to test to make sure your shared folder is working is to go into the docker session, navigate to your folder with `cd /magenta-data` and do a `mkdir test` you should see a folder named test pop up on the windows side in the shared folder.

**Comment by vmeade** [comment]
Wow, I see ten midi's within the container by

cd /magenta-data/lookback_rnn/generated

ls

You definitely solved it, congrats and thank you!

**Comment by elburz** [comment]
Great. Please close this issue if it's solved.
