### ISSUE TITLE
copying from host machine in docker

### ISSUE THREAD

**Issue by vmeade** [tensorflow/magenta#221]
I am on windows and am trying to copy from host machine the files.. like the midi from Docker.

can anyone help me with the commands?

**Comment by cghawthorne** [comment]
Hi @vmeade. If you start docker using the command listed in our readme, then the folder /magenta-data within the Docker container will be mapped to /tmp/magenta on your host machine.

```
docker run -it -p 6006:6006 -v /tmp/magenta:/magenta-data tensorflow/magenta
```

So, to copy a file to the host machine from within Docker, you would just run `cp file.mid /magenta-data`.

**Comment by vmeade** [comment]
Hi @cghawthorne.

In the end of computing the lookback_rnn example I get "INFO:tensorflow:Wrote 10 MIDI files to /magenta-data/lookback_rnn/generated"

I thought the files would be written onto my computer, but couldn't find them. I then looked to see if they were in a directory in Docker and that's why I was trying to copy them from there but I may have had a misunderstanding.

Do you know where the location of these MIDIs are? 

I ran the "cp file.mid /magenta-data"

but got "cp: cannot stat 'file.mid': No such file or directory"

I apologize for being a beginner if I have done something wrong because many things aren't obvious to me.

**Comment by elburz** [comment]
When you run the Docker script, this part "/tmp/magenta:/magenta-data" assigned a folder on your local system at /tmp/magenta to the folder on the Docker container /magenta-data. By default I believe the midi files are written to /magenta-data, so you'd just need to go on your local machine to /tmp/magenta, or wherever you specified that folder to be.

**Comment by vmeade** [comment]
Do I need to create the folder /tmp/magenta prior to running the lookback_rnn in order for Docker to find this folder?

The folder currently doesn't exist on my computer or it is extremely hidden.
I'm not sure if running in Windows will have an effect about any of this?

Thanks for the help so far.

**Comment by douglaseck** [comment]
I'm not sure where the temp directory is created in Windows.  Any Windows
users able to help?

In general TensorFlow life is easier on Linux and Mac OSX.

**Comment by elburz** [comment]
I'm unaware of how to access /tmp on a Windows. I did quick tests on a Mac and used my home folder `~/magenta:/magenta-data` . So you may want to do something similar but for Windows, like `C:/magenta:/magenta-data`

**Comment by vmeade** [comment]
@elburz
Ya, I'm going to try 
docker run -it -p 6006:6006 -v C:/magenta:/magenta-data tensorflow/magenta

bazel run //magenta/models/lookback_rnn:lookback_rnn_generate -- \
--bundle_file=/magenta-models/lookback_rnn.mag \
--output_dir=/magenta-data/lookback_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"

If it works I'll share the piece.

@douglaseck 
Ya, I can understand. I just was captivated by the whole early stages of the movement of these things and wound up getting this far working through docker,msys,bazel,tensorflow, and then magenta.
