### ISSUE TITLE
Clarify output file paths

### ISSUE THREAD

**Issue by elburz** [tensorflow/magenta#224]
I think it can be confusing for new users that on the [main readme] (https://github.com/tensorflow/magenta) someone took the time to update the output path of the bazel command to match the designated shared folder from the docker run command listed just above. On the pages about each specific model like [this one for basic_rnn](https://github.com/tensorflow/magenta/tree/master/magenta/models/basic_rnn), the output is defaulted to /tmp.

I think the solution could just be a few steps added to the initial readme to bring to users attention that the output flag was updated to match the designated shared folder. Alternative solution, although maybe not as clean, would be to update the other pages to also used /magenta-data instead of /tmp for uniformity.

**Comment by cghawthorne** [comment]
Hey @elburz, feel free to submit a pull request if you have thoughts on how to make the documentation more clear. I'd suggest we leave the non-Docker documentation using /tmp because most systems won't have a /magenta-data directory (and probably wouldn't want to make one).

**Comment by elburz** [comment]
Sure, I'm new to Docker, is there anything significant about the /magenta-data folder itself? There's a warning that calls it out here, I can edit this as well to be more generic:

> WARNING: only data saved in /magenta-data will persist across Docker sessions.

**Comment by elburz** [comment]
created a pull request #226 for this.

**Comment by cghawthorne** [comment]
Fixed by #226
