### ISSUE TITLE
File Paths

### ISSUE THREAD

**Issue by vmeade** [tensorflow/magenta#225]
So I had success once, but I tried so many variations I'm not sure which one it was

I basically know it has something to do with lining up the Docker container with the output_dir.
This is close to what I write each time, but I haven't gotten it to work since I unknowingly did it earlier today and discovered this only recently by chance:

docker run -it -p 6006:6006 -v **/c/Users/Vincent/notebooks:**/magenta-data tensorflow/magenta

bazel run //magenta/models/lookback_rnn:lookback_rnn_generate -- --bundle_file=/magenta-models/lookback_rnn.mag --**output_dir=/c/Users/Vincent/notebooks** --num_outputs=20 --num_steps=128 --primer_melody="[60]"

I've bolden that which I'm trying to line up. I do have 10 midis that I enjoy but I've not retained my method for doing so, can anyone help me out by correcting my docker command and magenta output_dir command?

**Comment by vmeade** [comment]
Basically I know this happened because one time I misspelled a path for the output_div and docker created the folder set (with the misspelling) on my harddrive 

I think the

 docker run -it -p 6006:6006 **C:/magenta:/magenta-data** tensorflow

**output_dir=/c/Users/Vincent/notebooks**

might be it but i'll have to check tomorrow.

**Comment by vmeade** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22435073/18870406/505e71ea-8465-11e6-8b3c-efbf203a27b3.jpg)


a view of the chaos... i see the folders but can not access them?

**Comment by elburz** [comment]
The issue is your output_dir variable should match the 2nd half of your docker path assignment, not the first. The first is the path on your local machine, and the 2nd path is the corresponding path in the docker session. So you should do this to correspond with that docker run command :

`output_dir=/magenta-data`

**Comment by vmeade** [comment]
very beautiful. thank you.
