### ISSUE TITLE
Add Python 3 compatibility to Magenta.

### ISSUE THREAD

**Issue by adarob** [tensorflow/magenta#304]
Magenta is currently only compatible with Python 2. We would like to make it compatible with Python 3 as well in order to take advantage of improvements, such as more accurate timing for real-time interfaces.

**Comment by souravsingh** [comment]
I would like to help in the issue

**Comment by xxlv** [comment]
👍

**Comment by CihanSari** [comment]
This should have a very high priority, as _TensorFlow supports **only** 64-bit Python 3.5 on Windows._([link](https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#pip-installation-on-windows)).

**Comment by arijit17** [comment]
Does it mean once we have it Magenta will work on Windows 10 as well?

**Comment by akuckartz** [comment]
:+1:

**Comment by maria8899** [comment]
Any news on this?

**Comment by irvanrahadhian** [comment]
yes is there any news on magenta support python 3?

**Comment by cghawthorne** [comment]
No news right now, but this is something that we definitely want to move forward on, especially since IPython now supports only Python 3.

**Comment by sanz999** [comment]
I'd be willing to help.

**Comment by mscuthbert** [comment]
Version 4.0 of music21 which can be used for Magenta MusicXML parsing was released today and it is the last version to support Python 2.  The master branch of music21 is now Python 3 only.  I'd very much like to keep up connecting Magenta and music21!

**Comment by cghawthorne** [comment]
Thanks to @umbanhowar, the majority of our code base is now Python 3 compatible! Closing this bug now, and we can track any remaining incompatibilities with separate bugs.
