### ISSUE TITLE
Missing flute_scale_with_png.mxl file

### ISSUE THREAD

**Issue by cghawthorne** [tensorflow/magenta#341]
I'm seeing a Bazel test failure related to flute_scale_with_png.mxl not being found. @jsawruk, did you maybe forget to check that one in?

**Comment by jsawruk** [comment]
Oops, forgot to check it in. It's now on the musicxml branch, commit 0eb36d5.

**Comment by cghawthorne** [comment]
Cool. Can you do a new pull request for that?

**Comment by jsawruk** [comment]
Pull request #342.

**Comment by cghawthorne** [comment]
Looks like the pull request was closed before it could be merged. Were you planning on making a different pull request?

**Comment by jsawruk** [comment]
I didn't like how the rebase went, so I deleted the branch, rebranched off of master, and created a new branch. I guess I need to create a new pull request now.
