### ISSUE TITLE
Exactly one of `--config` or `--melody_encoder_decoder` must be supplied.

### ISSUE THREAD

**Issue by johndpope** [tensorflow/magenta#350]
dockerfile 

running this inside docker
```
melody_rnn_generate \
  --bundle_file=/magenta-models/lookback_rnn.mag \
  --output_dir=/magenta-data/lookback_rnn/generated \
  --num_outputs=10 \
  --num_steps=128 \
  --primer_melody="[60]"

```
 -> blows up 

![screen shot 2016-11-03 at 16 02 21](https://cloud.githubusercontent.com/assets/289994/19983060/d1647ef6-a1de-11e6-8087-8ee3fb76a0ce.png)

tried passing

`
 melody_rnn_generate   --bundle_file=/magenta-models/lookback_rnn.mag   --output_dir=/magenta-data/lookback_rnn/generated   --num_outputs=10   --num_steps=128   --primer_melody="[60]" --melody_encoder_decoder='lookback'
`

```
melody_encoder_decoders = {
    'onehot': one_hot_melody_encoder_decoder,
    'lookback': lookback_melody_encoder_decoder,
    'key': magenta.music.KeyMelodyEncoderDecoder
}
```

![screen shot 2016-11-03 at 16 06 49](https://cloud.githubusercontent.com/assets/289994/19983199/6c6b911e-a1df-11e6-89b8-1fb818aa8cef.png)
but fails

AttributeError: 'NoneType' object has no attribute 'id'

I'm using the dockerfile from the readme.

**Comment by cghawthorne** [comment]
Thanks for catching this! We forgot to update the example command with the --config parameter. I'll fix that shortly.

**Comment by jellysquider** [comment]
Hello, 
I encountered this issue after running
```
melody_rnn_generate \
  --bundle_file=/magenta-models/lookback_rnn.mag \
  --output_dir=//anaconda/generated \
  --num_outputs=10 \
  --num_steps=128 \
  --primer_melody="[60]"
```
I got: 

> File "/Users/govi/miniconda2/envs/magenta/bin/melody_rnn_generate", line 11, in <module>
>     sys.exit(console_entry_point())
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 256, in console_entry_point
>     tf.app.run(main)
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 239, in main
>     config = melody_rnn_config_flags.config_from_flags()
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_config_flags.py", line 111, in config_from_flags
>     'Exactly one of `--config` or `--melody_encoder_decoder` must be '
> magenta.models.melody_rnn.melody_rnn_config_flags.MelodyRnnConfigFlagsException: Exactly one of `--config` or `--melody_encoder_decoder` must be supplied.

I described similar issue in [#296](https://github.com/tensorflow/magenta/issues/296#issuecomment-260358733)

**Comment by cghawthorne** [comment]
@jellysquider can you try adding `--config=lookback_rnn` to your command?

**Comment by jellysquider** [comment]
```
(magenta) Gabrielas-Mac-Pro:magenta govi$ BUNDLE_PATH=//miniconda2/envs/magenta/magenta/models/melody_rnn/lookback_rnn.mag
(magenta) Gabrielas-Mac-Pro:magenta govi$ CONFIG=‘lookback_rnn’
(magenta) Gabrielas-Mac-Pro:magenta govi$ bazel-bin/magenta/models/melody_rnn/melody_rnn_generate 
--config=${CONFIG} \ 
--bundle_file=${BUNDLE_PATH} \ 
--output_dir=//miniconda2/generated \ 
--num_outputs=10 \ --num_steps=128 \ —primer_melody="[60]"
```

> 
> Traceback (most recent call last):
>   File "/Users/govi/miniconda2/envs/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 260, in <module>
>     console_entry_point()
>   File "/Users/govi/miniconda2/envs/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 256, in console_entry_point
>     tf.app.run(main)
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/Users/govi/miniconda2/envs/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 239, in main
>     config = melody_rnn_config_flags.config_from_flags()
>   File "/Users/govi/miniconda2/envs/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_config_flags.py", line 136, in config_from_flags
>     melody_rnn_model.default_configs.keys(), FLAGS.config))
> magenta.models.melody_rnn.melody_rnn_config_flags.MelodyRnnConfigFlagsException: `--config` must be one of ['basic_rnn', 'attention_rnn', 'lookback_rnn']. Got ‘lookback_rnn’.
> 
>

**Comment by cghawthorne** [comment]
@jellysquider it looks like you're including some unicode quote characters on your command line to set the CONFIG value. Try this for setting the CONFIG value:

```
CONFIG=lookback_rnn
```
