### ISSUE TITLE
Enhancement - script to spit out grpc libraries (swift / python /etc) en masse

### ISSUE THREAD

**Issue by johndpope** [tensorflow/magenta#358]
I drafted this script to spit out 
Swift /ObjC /Python /Ruby /Node/c# or c++ / QuickProto files.
https://gist.github.com/johndpope/3c264dfab5bd493d138e8f415070a31b

**Comment by johndpope** [comment]
Do you guys have any gists you can share to get the proto files to talk to magenta?

**Comment by cghawthorne** [comment]
@adarob has looking into using Magenta via grpc before.

I'm curious what your goal is for having the proto files generated outside the repo or pip package. Are you wanting to add support for manipulating NoteSequence protos via another programming language, or did you have something else in mind?

**Comment by johndpope** [comment]
until  tensorflow has a native swift wrapper - the grpc will allow apps or server side micro services to interact with it. https://github.com/tensorflow/tensorflow/issues/19
It's kind of pioneering work - and any pointers by @adarob  would be most appreciated.

**Comment by adarob** [comment]
Hi John. Which parts of Magenta are you looking to open up to Swift? We
have some plans around building a gRPC interface for musical sequence
generation. If that's what you had in mind, we should definitely coordinate.

**Comment by johndpope** [comment]
sounds awesome. I built an desktop osx app and was looking at HMM hidden markov models to spew out midi - but would love to upgrade it with some real smarts.
The swift grpc project is making head way here - https://github.com/grpc/grpc-swift/issues/6
so just need to glue it all together.

https://github.com/tensorflow/magenta/blob/00bfe59fd038e2df17db3db7ef6377ee49d5dc33/magenta/protobuf/music.proto

 but um, frankly without a grpc service + documentation (independent of swift) /notes  - then it's a kind of a black hole.  Which is ok - but just would be good to share workings.

**Comment by johndpope** [comment]
fyi - I have an inception + swift + docker container talking together. 
 https://github.com/nubbel/swift-tensorflow/

I couldn't see any service layer inside magenta proto files / so haven't explored further with this. 
@adarob - was there any progress here?
