### ISSUE TITLE
TypeError: Expected binary or unicode string

### ISSUE THREAD

**Issue by 1N50MN14** [tensorflow/magenta#368]
When running the code snippet as described in `models/image_stylization/README.md` for stylizing an image,  `compat.py` throws an error in L61 `TypeError: Expected binary or unicode string` when passing a Python dictionary to `--which-style` (i.e. `--which_styles="{0:0.1,1:0.1,2:0.1,3:0.1,4:0.1,5:0.1,6:0.1,7:0.1,8:0.1,9:0.1}"`). This error does not occur when passing an array value (i.e. `--which_styles="[1,2,3]"`).

Unrelated, where do I find the list/names of original style used for Monet and Varied model?

**Comment by cghawthorne** [comment]
@1N50MN14 I'm not sure if this is relevant, but we just released a new version of the pip package (0.1.6). Can you try upgrading and see if that fixes it?

**Comment by 1N50MN14** [comment]
Thanks @cghawthorne does tensorflow/magenta pull from the repo or should I attempt a manual install?

About the list of styles, one of the reasons I'm trying to look them up is because it will be hard for me attempt to train new models if I don't know which styles are included in the pre-trained models or compare my own results. 

Will take a look look at Dockerfile and rebuild in the meantime

**Comment by 1N50MN14** [comment]
Yes it does, rebuilding.

**Comment by 1N50MN14** [comment]
@cghawthorne Dockfile build now fails with the following error:
```javascript
Executed 30 out of 30 tests: 29 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
The command '/bin/sh -c bazel build //magenta/... && bazel test //magenta/...' returned a non-zero code: 3
```

**Comment by cghawthorne** [comment]
Can you include a bit more of the output to show which test is failing?

Is there a reason you need to build a new Docker image? If you're wanting to do more than just run a few example commands, I'd recommend installing the pip package locally: https://github.com/tensorflow/magenta#python-pip

**Comment by 1N50MN14** [comment]
Apologies I missed the relevant error line:
```javascript
//magenta/interfaces/midi:midi_hub_test                                  FAILED in 21.5s
  /root/.cache/bazel/_bazel_root/cb5f479c6a7afa91f510d7ce625f6aa5/execroot/magenta/bazel-out/local-opt/testlogs/magenta/interfaces/midi/midi_hub_test/test.log

Executed 30 out of 30 tests: 29 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
The command '/bin/sh -c bazel build //magenta/... && bazel test //magenta/...' returned a non-zero code: 3
```
The reason for building myself is image is based from `tensorflow/tensorflow:0.11.0rc1-devel` and I'd like to be able to based it from `tensorflow/tensorflow:0.11.0rc1-devel-gpu` later on.

**Comment by cghawthorne** [comment]
Hmm, not sure why that one would be failing. Can you include the test.log from the failing test?

If you're wanting to use the GPU, I would definitely recommend using the pip package with a locally installed tensorflow setup. Getting the GPU to work in a Docker container can be tricky (though it should be possible).

**Comment by 1N50MN14** [comment]
My experience with `tensorflow-devel-gpu` has been relatively smooth thus far it's based from nvidia-docker / `nvidia/cuda:8.0-cudnn5-devel`. I'm not quite sure how to extract test.log as it's the build which fails and it seems the file is stored in a random tmp directory name. 

Will try to build on a different machine, possibly try to skip this test all together as it's only the style transfer I'm interested in. Will post an update shorty.

**Comment by 1N50MN14** [comment]
@cghawthorne Success!

Got rid of bazel test in Dockerfile for now so I was able to build again, the new version of the pip package seemed to have resolved the issue.

Appreciate your help!

**Comment by cghawthorne** [comment]
Glad to hear it!
