### ISSUE TITLE
Image stylization model training fails on TF 0.11.0

### ISSUE THREAD

**Issue by jveres** [tensorflow/magenta#385]
Hi,

I'm trying to create a new image stylization model and followed the README guides.
After 40000 iterations the resulting model.ckpt-40000 file is 548MB and it only produces black images.

Anyone had success training new models?

Magenta 0.1.6
Tf 0.11.0
CUDA 8.0
cuDNN 5.1

**Comment by jveres** [comment]
Checking my output by evaluating a single style model after a few hundreds of iterations describes the "black images" notation better. After ~1000 iterations outputs become fully dark.
![screen shot 2016-11-15 at 12 25 57](https://cloud.githubusercontent.com/assets/6890818/20304147/13f9cd1c-ab2f-11e6-9523-43e275d584f8.png)

**Comment by jveres** [comment]
I guess the model size problem could be solved by stripping `VGG16` from the final checkpoint?

**Comment by jveres** [comment]
I think the image bug lies in not converting inputs into the range `[-1,1]`, instead they are divided again by `255.0` here: [https://github.com/tensorflow/magenta/blob/master/magenta/models/image_stylization/image_utils.py#L124](image_utils.py). Please fix.

**Comment by jveres** [comment]
I've fixed the training code so now it produces much better results.
![screen shot 2016-11-16 at 22 16 38](https://cloud.githubusercontent.com/assets/6890818/20366367/0ef7b686-ac4b-11e6-9e95-8d59c9971a60.png)

**Comment by iansimon** [comment]
Those looks great!  Thanks for doing this!  Do you want to submit a pull request for your fix?

**Comment by jveres** [comment]
I'd need a bit more exact reference data to evaluate my changes made in the code before I'd make a PR.

**Comment by jveres** [comment]
I see some visual glitches in my results: it has a border effect and after ~15k iterations results get grainy.
Anyone of the authors could join this thread please to check? Thanks!
(Here's a sample with Picasso pencil drawing style.)
![tofa_hanna_picasso](https://cloud.githubusercontent.com/assets/6890818/20462131/57284b34-af14-11e6-826b-03e0569b313e.png)

**Comment by ouyanghao** [comment]
Hi. I encountered the same problem. The output results are just like yours. Can I know how you fix the problem?

**Comment by iansimon** [comment]
This should now be fixed by #445 but let me know if your results still look incorrect.

**Comment by sann5130** [comment]
@jveres How did you solve your problem? 
@iansimon I just trained a SINGLE style model (the style being starrynight) using the image_stylization_train.py code, following the instructions on README, for 40k iterations. However, my results are very weird.
![starrynight_step40k_fulltraining_picabo_0](https://user-images.githubusercontent.com/32304564/32230672-9df162ca-be4b-11e7-9a2f-c81d5b7b756d.png)
![starrynight_step40k_fulltraining_guerrillero_0](https://user-images.githubusercontent.com/32304564/32230676-a1c856e2-be4b-11e7-9a51-d4984eee372a.png)
