### ISSUE TITLE
Building Dataset Documentation Error

### ISSUE THREAD

**Issue by jsleep** [tensorflow/magenta#391]
https://github.com/tensorflow/magenta/blob/master/magenta/scripts/README.md

Says to use "convert_dir_to_note_sequences" but my magenta environment only found the command "convert_**midi**_dir_to_note_sequences".

**Comment by cghawthorne** [comment]
Ah sorry, that was caused by #377 that combined the musicxml and midi parser scripts and updated the documentation accordingly. We need to cut a new pip package with the new command. In the mean time, you can proceed using convert_midi_dir_to_note_sequences.

**Comment by cghawthorne** [comment]
We've just released Magenta 0.1.8, so this should be fixed.

**Comment by jasondesante** [comment]
now says   File "demo.py", line 16
    convert_midi_dir_to_note_sequences \
SyntaxError: can't assign to operator
