### ISSUE TITLE
C++ compilation of rule '@protobuf//:protobuf_lite' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh 

### ISSUE THREAD

**Issue by dbl001** [tensorflow/magenta#435]
OS X 10.11.6
Mac ports

MacBook-Pro:magenta davidlaxer$ which gcc
/opt/local/bin/gcc
MacBook-Pro:magenta davidlaxer$ gcc --version
gcc (MacPorts gcc5 5.4.0_0) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

MacBook-Pro:magenta davidlaxer$ python --version
Python 2.7.10 :: Anaconda 2.3.0 (x86_64)

MacBook-Pro:magenta davidlaxer$ bazel test //magenta:all
..
WARNING: /private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 2 targets and 0 test targets...
ERROR: /private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/external/protobuf/BUILD:71:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 41 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
INFO: Elapsed time: 10.207s, Critical Path: 1.48s
ERROR: No test targets were found, yet testing was requested.
D

**Comment by douglaseck** [comment]
does it help to run "bazel clean" and try again?
What xcode version are you on? I don't have my mac here but I think "gcc
--version" will tell you something.

**Comment by dbl001** [comment]
XCode Version 8.0 (8A218a)

David-Laxers-MacBook-Pro:magenta davidlaxer$ bazel clean
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
David-Laxers-MacBook-Pro:magenta davidlaxer$ gcc --version
gcc (MacPorts gcc5 5.4.0_0) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

David-Laxers-MacBook-Pro:magenta davidlaxer$ bazel test //magenta:all
WARNING: /private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 2 targets and 0 test targets...
ERROR: /private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/external/protobuf/BUILD:71:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 41 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
INFO: Elapsed time: 9.644s, Critical Path: 2.90s
ERROR: No test targets were found, yet testing was requested.
David-Laxers-MacBook-Pro:magenta davidlaxer$

**Comment by dbl001** [comment]
Would you recommend running Magenta on the Google Cloud Platform instead of on a Mac?
Does Magenta require/utilize Google TPUs?

**Comment by cghawthorne** [comment]
It looks like you're using the MacPorts version of gcc. We recommend using the version from xcode:

```
$ which gcc
/usr/bin/gcc
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

http://www.bazel.io/versions/master/docs/install.html#install-with-installer-1

**Comment by dbl001** [comment]
Issue Resolved.

Thank You!

**Comment by cghawthorne** [comment]
Glad to hear it!

**Comment by cusitkhan** [comment]
i am also facing this problem since one week but could not fix it till now if any one have any idea pleas guide mee

**Comment by SimplePaul** [comment]
the same
