### ISSUE TITLE
" --input=/tmp/notesequences.tfrecord: No such file or directory" shows when I try to "Create SequenceExamples"

### ISSUE THREAD

**Issue by buaatian** [tensorflow/magenta#437]
Hello everybody.I'm new here.when I try to "[Create SequenceExamples"](https://github.com/tensorflow/magenta/blob/master/magenta/models/melody_rnn/README.md) according to this tourist,I meet a problem shows like this:

AttributeError: 'NoneType' object has no attribute 'startswith' /root/train/mymodels/SequenceExamples.sh: line 4: --input=/tmp/notesequences.tfrecord: No such file or directory

However,I do have the file"/tmp/notesequences.tfrecord".And this file was created by the flowing codes:

INPUT_DIRECTORY=<folder containing MIDI and/or MusicXML files. can have child folders.>
SEQUENCES_TFRECORD=/tmp/notesequences.tfrecord
convert_dir_to_note_sequences \
  --input_dir=$INPUT_DIRECTORY \
  --output_file=$SEQUENCES_TFRECORD \
  --recursive

In fact,when I run the above codes,I received a wrong message which said like "No command convert_dir_to_note_sequences". After I searched on the internet,I use "convert_midi_dir_to_note_sequences" instead of it. And then,it showed this:

INFO:tensorflow:Converting MIDI files in '/root/midimusic/Mozart/'.
/root/miniconda2/envs/magenta/lib/python2.7/site-packages/pretty_midi/pretty_midi.py:93: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  RuntimeWarning)
INFO:tensorflow:Converted 10 MIDI files in '/root/midimusic/Mozart/'.
INFO:tensorflow:Could not parse 0 MIDI files.
INFO:tensorflow:Wrote 10 NoteSequence protos to '/tmp/notesequences.tfrecord'

I don't know whether it is normal or not. No matter what,it did create the file"/tmp/notesequences.tfrecord".But now, I can't run "Create SequenceExamples" code which shows "--input=/tmp/notesequences.tfrecord: No such file or directory".Can anyone help me?

**Comment by buaatian** [comment]
I found the problem and solved.How stupid I am......

**Comment by leonfrank** [comment]
Excuse me, can you explain how you solved this problem cause I meet the same problem now
