### ISSUE TITLE
Cannot train my own model when I run "melody_rnn_train"

### ISSUE THREAD

**Issue by buaatian** [tensorflow/magenta#439]
hello everyone, I meet some problems when I try to train my own model. Every time I tried to run my code, it always had below wrong massage:

_INFO:tensorflow:hparams = {'rnn_layer_sizes': [128, 128], 'attn_length': 40, 'dropout_keep_prob': 0.5, 'batch_size': 128, 'decay_rate': 0.97, 'clip_norm': 3, 'initial_learning_rate': 0.001, 'decay_steps': 1000, 'skip_first_n_losses': 0}
INFO:tensorflow:Train dir: /tmp/melody_rnn/logdir/run1/train
INFO:tensorflow:Starting training loop...
INFO:tensorflow:global_step/sec: 0
trainthemodel.sh: **line 6: 13536 Killed** melody_rnn_train --config=attention_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=/tmp/melody_rnn/sequence_examples/training_melodies.tfrecord --hparams="{'batch_size':64,'rnn_layer_sizes':[64,64]}" --num_training_steps=20000_

I think it isn't correct. Does anyone know how to solve it?

**Comment by cghawthorne** [comment]
Can you paste the contents of your `trainthemodel.sh` script?

**Comment by buaatian** [comment]
Here is my trainthemodel.sh：

```
melody_rnn_train \
--config=attention_rnn \
--run_dir=/tmp/melody_rnn/logdir/run1 \
--sequence_example_file=/tmp/melody_rnn/sequence_examples/training_melodies.tfrecord \
--hparams="{'batch_size':64,'rnn_layer_sizes':[64,64]}" \
--num_training_steps=20000
```

I just copied it according to the tutorial. Although it always shows "balabala(Is the number a PID?) Killed", It did create the folder "/tmp/melody_rnn/logdir/run1/train" and it contents four files: 
checkpoint                               graph.pbtxt   model.ckpt-0.meta
events.out.tfevents.1480998996.tianwang  model.ckpt-0

**Comment by cghawthorne** [comment]
One other thing to double check, has the file `/tmp/melody_rnn/sequence_examples/training_melodies.tfrecord` been correctly created with training data in it?

Also, what environment are you running this in? Is there any possibility some other part of the system is killing the process, maybe for exceeding quota or something?

**Comment by buaatian** [comment]
OK，I checked and the file "training_melodies.tfrecord" does exist and has file size(means it's not 0kb and has data in it). However,I don't know how to read the ".tfrecord" file.so I can't figure out whether it is correct.I searched on the internet and found the below python code to read data in tfrecord file.
`readtfrecordfile.py`
```
import tensorflow as tf
import os
current_path = os.getcwd()
input_file = os.path.join(current_path, "training_melodies.tfrecord")
for serialized_example in tf.python_io.tf_record_iterator(input_file):
        example = tf.train.Example()
        example.ParseFromString(serialized_example)
        feature = example.features.feature["feature"].float_list.value
        label = example.features.feature["label"].float_list.value
        print("Feature: {}, label: {}".format(feature, label))
```
When I run it, the output are multi lines `Feature: [], label: []`.Is this correct?Does it mean there are no training data in training_melodies.tfrecord or I didn't use the right way to read the data in tfrecord file?

What's more,I use the vps which bought from Bandwagon Host.Here is the environment:
CPU:2x Intel Xeon
RAM:512MB
OS:Ubuntu 16.04 64bit with Python2.7
Disk storage:11GB available

Are there any problems about the environment?Looking forward your reply.Thank you very much!

**Comment by cghawthorne** [comment]
I suspect the main problem is that your environment doesn't have enough RAM. If you check the output of `dmesg`, you'll probably see something related to the process being killed due to running out of memory. I'd suggest getting a machine with at least 2GB of RAM, though the exact amount used will depend on how you configure the training.

**Comment by buaatian** [comment]
ahah! I used the command `dmesg` and it  showd numbers of wrong information about `out of memory in ub `.you are right.thank you so much! seems that i need a new machine,lol 🙈
