### ISSUE TITLE
bash: drums_rnn_create_dataset: command not found

### ISSUE THREAD

**Issue by wxy656** [tensorflow/magenta#480]
hi, I find  drums_rnn_create_dataset can't work  .

and  after i  trying " python drums_rnn_create_dataset_test." 
 it says:"ImportError: cannot import name drums_rnn_create_dataset"

**Comment by cghawthorne** [comment]
Our build environment uses bazel, so you can't run the tests directly. To run the tests, you'll need to first install the [development environment](https://github.com/tensorflow/magenta/blob/master/README.md#development-environment) and then run ```bazel test //magenta/models/drums_rnn:drums_rnn_create_dataset_test```.
