### ISSUE TITLE
bazel tests failing "Attempted relative import in non-package"

### ISSUE THREAD

**Issue by nadavbh12** [tensorflow/magenta#485]
Hi,
When running the bazel tests I get the following output attached below.
Ubuntu 14.04, tensorflow 0.12, bazel 0.4.2
I've attached the log of the first test after the bazel output.

`WARNING: /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/external/protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/external/protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
INFO: Found 103 targets and 35 test targets...
FAIL: //magenta/pipelines:melody_pipelines_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/melody_pipelines_test/test.log).
FAIL: //magenta/pipelines:chord_pipelines_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/chord_pipelines_test/test.log).
FAIL: //magenta/music:drums_encoder_decoder_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/drums_encoder_decoder_test/test.log).
FAIL: //magenta/models/drums_rnn:drums_rnn_create_dataset_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/drums_rnn/drums_rnn_create_dataset_test/test.log).
FAIL: //magenta/pipelines:pipelines_common_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipelines_common_test/test.log).
FAIL: //magenta/music:drums_lib_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/drums_lib_test/test.log).
FAIL: //magenta/models/polyphony_rnn:polyphony_lib_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_lib_test/test.log).
FAIL: //magenta/music:lead_sheets_lib_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/lead_sheets_lib_test/test.log).
FAIL: //magenta/models/melody_rnn:melody_rnn_create_dataset_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/melody_rnn/melody_rnn_create_dataset_test/test.log).
FAIL: //magenta/music:encoder_decoder_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/encoder_decoder_test/test.log).
FAIL: //magenta/music:melody_encoder_decoder_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/melody_encoder_decoder_test/test.log).
FAIL: //magenta/scripts:convert_dir_to_note_sequences_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_dir_to_note_sequences_test/test.log).
FAIL: //magenta/interfaces/midi:midi_hub_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/interfaces/midi/midi_hub_test/test.log).
FAIL: //magenta/pipelines:lead_sheet_pipelines_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/lead_sheet_pipelines_test/test.log).
FAIL: //magenta/pipelines:drum_pipelines_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/drum_pipelines_test/test.log).
FAIL: //magenta/music:midi_io_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/midi_io_test/test.log).
FAIL: //magenta/models/rl_tuner:rl_tuner_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/rl_tuner/rl_tuner_test/test.log).
FAIL: //magenta/models/polyphony_rnn:polyphony_rnn_create_dataset_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_rnn_create_dataset_test/test.log).
FAIL: //magenta/music:melodies_lib_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/melodies_lib_test/test.log).
FAIL: //magenta/models/polyphony_rnn:polyphony_encoder_decoder_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_encoder_decoder_test/test.log).
FAIL: //magenta/models/shared:events_rnn_graph_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/shared/events_rnn_graph_test/test.log).
FAIL: //magenta/music:sequences_lib_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/sequences_lib_test/test.log).
FAIL: //magenta/music:chords_lib_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/chords_lib_test/test.log).
FAIL: //magenta/models/improv_rnn:improv_rnn_create_dataset_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/improv_rnn/improv_rnn_create_dataset_test/test.log).
FAIL: //magenta/music:chords_encoder_decoder_test (see /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/chords_encoder_decoder_test/test.log).
INFO: Elapsed time: 1.486s, Critical Path: 0.91s
//magenta/common:concurrency_test                               (cached) PASSED in 2.6s
//magenta/common:tf_lib_test                                    (cached) PASSED in 1.1s
//magenta/music:chord_symbols_lib_test                          (cached) PASSED in 0.9s
//magenta/music:events_lib_test                                 (cached) PASSED in 1.0s
//magenta/music:musicxml_parser_test                            (cached) PASSED in 3.2s
//magenta/music:note_sequence_io_test                           (cached) PASSED in 0.9s
//magenta/music:sequence_generator_test                         (cached) PASSED in 0.8s
//magenta/pipelines:dag_pipeline_test                           (cached) PASSED in 0.8s
//magenta/pipelines:pipeline_test                               (cached) PASSED in 1.1s
//magenta/pipelines:statistics_test                             (cached) PASSED in 1.1s
//magenta/interfaces/midi:midi_hub_test                                  FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/interfaces/midi/midi_hub_test/test.log
//magenta/models/drums_rnn:drums_rnn_create_dataset_test                 FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/drums_rnn/drums_rnn_create_dataset_test/test.log
//magenta/models/improv_rnn:improv_rnn_create_dataset_test               FAILED in 0.2s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/improv_rnn/improv_rnn_create_dataset_test/test.log
//magenta/models/melody_rnn:melody_rnn_create_dataset_test               FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/melody_rnn/melody_rnn_create_dataset_test/test.log
//magenta/models/polyphony_rnn:polyphony_encoder_decoder_test            FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_encoder_decoder_test/test.log
//magenta/models/polyphony_rnn:polyphony_lib_test                        FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_lib_test/test.log
//magenta/models/polyphony_rnn:polyphony_rnn_create_dataset_test         FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_rnn_create_dataset_test/test.log
//magenta/models/rl_tuner:rl_tuner_test                                  FAILED in 0.5s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/rl_tuner/rl_tuner_test/test.log
//magenta/models/shared:events_rnn_graph_test                            FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/shared/events_rnn_graph_test/test.log
//magenta/music:chords_encoder_decoder_test                              FAILED in 0.2s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/chords_encoder_decoder_test/test.log
//magenta/music:chords_lib_test                                          FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/chords_lib_test/test.log
//magenta/music:drums_encoder_decoder_test                               FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/drums_encoder_decoder_test/test.log
//magenta/music:drums_lib_test                                           FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/drums_lib_test/test.log
//magenta/music:encoder_decoder_test                                     FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/encoder_decoder_test/test.log
//magenta/music:lead_sheets_lib_test                                     FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/lead_sheets_lib_test/test.log
//magenta/music:melodies_lib_test                                        FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/melodies_lib_test/test.log
//magenta/music:melody_encoder_decoder_test                              FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/melody_encoder_decoder_test/test.log
//magenta/music:midi_io_test                                             FAILED in 0.2s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/midi_io_test/test.log
//magenta/music:sequences_lib_test                                       FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/sequences_lib_test/test.log
//magenta/pipelines:chord_pipelines_test                                 FAILED in 0.2s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/chord_pipelines_test/test.log
//magenta/pipelines:drum_pipelines_test                                  FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/drum_pipelines_test/test.log
//magenta/pipelines:lead_sheet_pipelines_test                            FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/lead_sheet_pipelines_test/test.log
//magenta/pipelines:melody_pipelines_test                                FAILED in 0.2s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/melody_pipelines_test/test.log
//magenta/pipelines:pipelines_common_test                                FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipelines_common_test/test.log
//magenta/scripts:convert_dir_to_note_sequences_test                     FAILED in 0.3s
  /home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_dir_to_note_sequences_test/test.log
`

**Output of the file:**
/home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/encoder_decoder_test/test.log

`
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:95] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/bin/magenta/music/encoder_decoder_test.runfiles/__main__/magenta/music/encoder_decoder_test.py", line 18, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 76, in <module>
    import parser
  File "/home/itayh/.cache/bazel/_bazel_itayh/7fc566bae45cac53fe2c35d2f4dac0fb/execroot/magenta/bazel-out/local-opt/bin/magenta/music/encoder_decoder_test.runfiles/mido/parser.py", line 17, in <module>
    from .messages import Message, build_message, get_spec
ValueError: Attempted relative import in non-package
`

**Comment by cghawthorne** [comment]
What version of Python are you using?

**Comment by astvd3** [comment]
I am having the exact same issue and I am using python 2.7

**Comment by cghawthorne** [comment]
I believe this is the same root issue as #529.
