### ISSUE TITLE
Readme lacks instructions for training and generation

### ISSUE THREAD

**Issue by jdsutton** [tensorflow/magenta#49]
The readme provides a script for building the dataset, but does not describe how to train the model or use it to generate new music.

From the discussion page I was able to find a script for generating music:
https://groups.google.com/a/tensorflow.org/forum/#!topic/magenta-discuss/BAPcTHUulLs

I have added it to this branch:
https://github.com/jdsutton/magenta/tree/update-readme-instructions

However an example training script is still needed.

**Comment by adarob** [comment]
https://github.com/tensorflow/magenta/pull/52

**Comment by adarob** [comment]
Thanks for bringing this issue to our attention! Fixed.
