### ISSUE TITLE
Rename tf.concat_v2 references to tf.concat

### ISSUE THREAD

**Issue by annarev** [tensorflow/magenta#509]
We just made the second part of switching argument order of tf.concat. Second step is to rename tf.concat_v2 to tf.concat. The new tf.concat is available in v1.0.0-rc0 release  (https://github.com/tensorflow/tensorflow/blob/v1.0.0-rc0/tensorflow/python/ops/array_ops.py).

**Comment by cghawthorne** [comment]
It looks like the latest release that has a pip package is 0.12.1. Do you know when 1.0.0-rc0 will be available as a pip package?

https://pypi.python.org/pypi/tensorflow

**Comment by annarev** [comment]
rc0 won't be available as a pip package. Next release that will be available as a pip package will be 1.0. Do you need pip package to have these changes?

**Comment by cghawthorne** [comment]
Yes, we need to be able to depend on a pip package listed in our setup.py: https://github.com/tensorflow/magenta/blob/master/magenta/tools/pip/setup.py#L31

**Comment by annarev** [comment]
Sorry, I was actually wrong in my previous reply. 1.0.0rc0 is actually available as a pip package, but you would need to use one of the URLs listed here:
https://www.tensorflow.org/versions/r1.0/get_started/os_setup#pip_installation

**Comment by cghawthorne** [comment]
Do you know if it will be available on pypi at some point? We prefer if we can set things up so that `pip install magenta` just works.

**Comment by annarev** [comment]
It will be available for 1.0 release but not rc0.

**Comment by cghawthorne** [comment]
OK, we'll probably wait until then so we can make sure our pip package is in a good state.
