### ISSUE TITLE
basic_rnn readme filename issue

### ISSUE THREAD

**Issue by arsone** [tensorflow/magenta#51]
The initial training and eval dataset script defines the output as `/tmp/training_melodies.tfrecord` and `/tmp/evaluation_melodies.tfrecord` respectively. The readme then inaccurately references these files under "Running training in depth" as `/tmp/train_melodies.tfrecord` and `/tmp/eval_melodies.tfrecord`. Readme should be updated for consistent filenames.

**Comment by bryongloden** [comment]
👍

**Comment by adarob** [comment]
https://github.com/tensorflow/magenta/pull/52

**Comment by adarob** [comment]
Thanks for pointing this out! Fixed.
