### ISSUE TITLE
bazel tests failing !!  help wanted!!!!

### ISSUE THREAD

**Issue by sunxiaowu** [tensorflow/magenta#515]
bazel test //magenta/...ERROR: /home/sun/.cache/bazel/_bazel_sun/c0c3455d0ac97de9b6a093e0717b5ffc/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.
ERROR: package contains errors: magenta/protobuf.
ERROR: error loading package 'magenta/protobuf': Extension 'protobuf.bzl' has errors.
INFO: Elapsed time: 0.491s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by lifavor** [comment]
use the latest vesion of relate ref may kill the HOST_CFG problem.  and now i still have some problems about protobuf.

**Comment by cghawthorne** [comment]
We're tracking this in #518.
