### ISSUE TITLE
primer_melody to generate melodies have to be specified by 16th note?

### ISSUE THREAD

**Issue by icoxfog417** [tensorflow/magenta#516]
I read the [`Generate Melodies` in Melody RNN](https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn#generate-melodies). 

>For example --primer_melody="[60, -2, 60, -2, 67, -2, 67, -2]" would prime the model with the first four > notes of Twinkle Twinkle Little Star. 

The first four notes of Twinkle Twinkle Little Star is a quarter note, So I think --primer_melody have to be `[60, -2, -2, -2, 60, -2, -2, -2, 67, -2, -2, -2, 67, -2, -2, -2]`. Is it right? Or primer_melody is specified by quarter note?

**Comment by cghawthorne** [comment]
I think the example in the documentation assumes that the first four notes of "Twinkle Twinkle, Little Star" are eighth notes. The example you gave looks correct if you want them to be quarter notes instead. I'd suggest trying both and seeing what kind of output you get either way.

**Comment by icoxfog417** [comment]
@cghawthorne Thank you for reply! I'll try it.
