### ISSUE TITLE
bazel test error related to protobuf, help?

### ISSUE THREAD

**Issue by brisker** [tensorflow/magenta#518]
My environment is Ubuntu14.04 ,CPU, bazel 0.4.4 and python2.7, and after I install the packages necessary,  running "bazel test //magenta:all" gives me this error:
    ERROR:     /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.
    ERROR: /home/jcc/magenta/magenta/BUILD:21:1: error loading package 'magenta/protobuf': Extension 'protobuf.bzl' has errors and referenced by '//magenta:magenta'.
    ERROR: Analysis of target '//magenta:magenta' failed; build aborted.
    INFO: Elapsed time: 0.219s
ERROR: Couldn't start the build. Unable to run tests.

Any suggestions? Thanks  in advance!

**Comment by cghawthorne** [comment]
Should be fixed now.

**Comment by lifavor** [comment]
open the file  "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/external/protobuf/protobuf.bzl"
than, relpace **HOST_CFG** to '**host**' ,   and run test again just fine for me solve this problem
