### ISSUE TITLE
error when running conda create -n magenta python=2.7 jupyter

### ISSUE THREAD

**Issue by brisker** [tensorflow/magenta#522]
The error reads like 
jcc@jcc:~$ conda create -n magenta python=2.7 jupyter
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/jcc/anaconda2/envs/magenta:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    expat-2.1.0                |                0         365 KB
    icu-54.1                   |                0        11.3 MB
    jpeg-9b                    |                0         941 KB
    libffi-3.2.1               |                1          38 KB
    libgcc-5.2.0               |                0         1.1 MB
    libiconv-1.14              |                0         2.0 MB
    libxcb-1.12                |                1         1.5 MB
    openssl-1.0.2k             |                0         3.2 MB
    dbus-1.10.10               |                0         2.4 MB
    libpng-1.6.27              |                0         219 KB
    libxml2-2.9.4              |                0         3.7 MB
    pcre-8.39                  |                1         656 KB
    python-2.7.13              |                0        11.5 MB
    zeromq-4.1.5               |                0         4.1 MB
    backports_abc-0.5          |           py27_0          11 KB
    decorator-4.0.11           |           py27_0          15 KB
    freetype-2.5.5             |                2         2.5 MB
    glib-2.50.2                |                1         5.6 MB
    mistune-0.7.3              |           py27_0         560 KB
    path.py-10.0               |           py27_0          46 KB
    pyzmq-16.0.2               |           py27_0         835 KB
    scandir-1.4                |           py27_0          38 KB
    setuptools-27.2.0          |           py27_0         521 KB
    sip-4.18                   |           py27_0         264 KB
    wcwidth-0.1.7              |           py27_0          21 KB
    configparser-3.5.0         |           py27_0          31 KB
    fontconfig-2.12.1          |                3         429 KB
    gstreamer-1.8.0            |                0         2.6 MB
    jinja2-2.9.4               |           py27_0         291 KB
    pathlib2-2.2.0             |           py27_0          30 KB
    pexpect-4.2.1              |           py27_0          69 KB
    pip-9.0.1                  |           py27_1         1.6 MB
    prompt_toolkit-1.0.9       |           py27_0         311 KB
    traitlets-4.3.1            |           py27_0         118 KB
    entrypoints-0.2.2          |           py27_1           9 KB
    gst-plugins-base-1.8.0     |                0         3.1 MB
    jupyter_core-4.2.1         |           py27_0          56 KB
    pickleshare-0.7.4          |           py27_0           8 KB
    tornado-4.4.2              |           py27_0         555 KB
    ipython-5.1.0              |           py27_0         936 KB
    jupyter_client-4.4.0       |           py27_0          97 KB
    nbformat-4.2.0             |           py27_0         130 KB
    qt-5.6.2                   |                3        43.4 MB
    ipykernel-4.5.2            |           py27_0         132 KB
    pyqt-5.6.0                 |           py27_2         5.3 MB
    jupyter_console-5.0.0      |           py27_0          28 KB
    notebook-4.3.1             |           py27_0         5.3 MB
    qtconsole-4.2.1            |           py27_1         148 KB
    widgetsnbextension-1.2.6   |           py27_0         1.1 MB
    ipywidgets-5.2.2           |           py27_1          63 KB
    ------------------------------------------------------------
                                           Total:       118.9 MB

The following NEW packages will be INSTALLED:

    backports:          1.0-py27_0    
    backports_abc:      0.5-py27_0    
    configparser:       3.5.0-py27_0  
    dbus:               1.10.10-0     
    decorator:          4.0.11-py27_0 
    entrypoints:        0.2.2-py27_1  
    enum34:             1.1.6-py27_0  
    expat:              2.1.0-0       
    fontconfig:         2.12.1-3      
    freetype:           2.5.5-2       
    functools32:        3.2.3.2-py27_0
    get_terminal_size:  1.0.0-py27_0  
    glib:               2.50.2-1      
    gst-plugins-base:   1.8.0-0       
    gstreamer:          1.8.0-0       
    icu:                54.1-0        
    ipykernel:          4.5.2-py27_0  
    ipython:            5.1.0-py27_0  
    ipython_genutils:   0.1.0-py27_0  
    ipywidgets:         5.2.2-py27_1  
    jinja2:             2.9.4-py27_0  
    jpeg:               9b-0          
    jsonschema:         2.5.1-py27_0  
    jupyter:            1.0.0-py27_3  
    jupyter_client:     4.4.0-py27_0  
    jupyter_console:    5.0.0-py27_0  
    jupyter_core:       4.2.1-py27_0  
    libffi:             3.2.1-1       
    libgcc:             5.2.0-0       
    libiconv:           1.14-0        
    libpng:             1.6.27-0      
    libsodium:          1.0.10-0      
    libxcb:             1.12-1        
    libxml2:            2.9.4-0       
    markupsafe:         0.23-py27_2   
    mistune:            0.7.3-py27_0  
    nbconvert:          4.2.0-py27_0  
    nbformat:           4.2.0-py27_0  
    notebook:           4.3.1-py27_0  
    openssl:            1.0.2k-0      
    path.py:            10.0-py27_0   
    pathlib2:           2.2.0-py27_0  
    pcre:               8.39-1        
    pexpect:            4.2.1-py27_0  
    pickleshare:        0.7.4-py27_0  
    pip:                9.0.1-py27_1  
    prompt_toolkit:     1.0.9-py27_0  
    ptyprocess:         0.5.1-py27_0  
    pygments:           2.1.3-py27_0  
    pyqt:               5.6.0-py27_2  
    python:             2.7.13-0      
    pyzmq:              16.0.2-py27_0 
    qt:                 5.6.2-3       
    qtconsole:          4.2.1-py27_1  
    readline:           6.2-2         
    scandir:            1.4-py27_0    
    setuptools:         27.2.0-py27_0 
    simplegeneric:      0.8.1-py27_1  
    singledispatch:     3.4.0.3-py27_0
    sip:                4.18-py27_0   
    six:                1.10.0-py27_0 
    sqlite:             3.13.0-0      
    ssl_match_hostname: 3.4.0.2-py27_1
    terminado:          0.6-py27_0    
    tk:                 8.5.18-0      
    tornado:            4.4.2-py27_0  
    traitlets:          4.3.1-py27_0  
    wcwidth:            0.1.7-py27_0  
    wheel:              0.29.0-py27_0 
    widgetsnbextension: 1.2.6-py27_0  
    zeromq:             4.1.5-0       
    zlib:               1.2.8-3       

Proceed ([y]/n)? y

Fetching packages ...
Error: Could not open u'/home/jcc/anaconda2/pkgs/expat-2.1.0-0.tar.bz2.part' for writing (seek).

Any help?

**Comment by cghawthorne** [comment]
Based on the anaconda bug tracker, this may be caused by a conflict with other python package management setups: https://github.com/ContinuumIO/anaconda-issues/issues/416 Could you try out the solutions mentioned in that thread?
