### ISSUE TITLE
error running bazel test //magenta/...

### ISSUE THREAD

**Issue by brisker** [tensorflow/magenta#523]
**The error reads like:**

jcc@jcc:~/magenta$ bazel test //magenta/...
.
INFO: Found 106 targets and 36 test targets...
FAIL: //magenta/models/shared:events_rnn_graph_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/shared/events_rnn_graph_test/test.log).
FAIL: //magenta/models/improv_rnn:improv_rnn_create_dataset_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/improv_rnn/improv_rnn_create_dataset_test/test.log).
FAIL: //magenta/models/polyphony_rnn:polyphony_rnn_create_dataset_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_rnn_create_dataset_test/test.log).
FAIL: //magenta/models/rl_tuner:rl_tuner_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/rl_tuner/rl_tuner_test/test.log).
FAIL: //magenta/music:musicnet_io_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/musicnet_io_test/test.log).
FAIL: //magenta/models/melody_rnn:melody_rnn_create_dataset_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/melody_rnn/melody_rnn_create_dataset_test/test.log).
FAIL: //magenta/models/drums_rnn:drums_rnn_create_dataset_test (see /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/drums_rnn/drums_rnn_create_dataset_test/test.log).
INFO: Elapsed time: 27.270s, Critical Path: 23.68s
//magenta/common:concurrency_test                                        PASSED in 3.3s
//magenta/common:tf_lib_test                                             PASSED in 1.6s
//magenta/interfaces/midi:midi_hub_test                                  PASSED in 19.9s
//magenta/models/polyphony_rnn:polyphony_encoder_decoder_test            PASSED in 1.9s
//magenta/models/polyphony_rnn:polyphony_lib_test                        PASSED in 1.9s
//magenta/music:chord_symbols_lib_test                                   PASSED in 2.0s
//magenta/music:chords_encoder_decoder_test                              PASSED in 1.7s
//magenta/music:chords_lib_test                                          PASSED in 1.7s
//magenta/music:drums_encoder_decoder_test                               PASSED in 1.7s
//magenta/music:drums_lib_test                                           PASSED in 1.7s
//magenta/music:encoder_decoder_test                                     PASSED in 1.7s
//magenta/music:events_lib_test                                          PASSED in 1.6s
//magenta/music:lead_sheets_lib_test                                     PASSED in 1.8s
//magenta/music:melodies_lib_test                                        PASSED in 1.7s
//magenta/music:melody_encoder_decoder_test                              PASSED in 1.8s
//magenta/music:midi_io_test                                             PASSED in 7.8s
//magenta/music:musicxml_parser_test                                     PASSED in 7.3s
//magenta/music:note_sequence_io_test                                    PASSED in 2.1s
//magenta/music:sequence_generator_test                                  PASSED in 1.7s
//magenta/music:sequences_lib_test                                       PASSED in 1.7s
//magenta/pipelines:chord_pipelines_test                                 PASSED in 1.7s
//magenta/pipelines:dag_pipeline_test                                    PASSED in 1.7s
//magenta/pipelines:drum_pipelines_test                                  PASSED in 1.7s
//magenta/pipelines:lead_sheet_pipelines_test                            PASSED in 1.8s
//magenta/pipelines:melody_pipelines_test                                PASSED in 1.7s
//magenta/pipelines:pipeline_test                                        PASSED in 1.7s
//magenta/pipelines:pipelines_common_test                                PASSED in 1.8s
//magenta/pipelines:statistics_test                                      PASSED in 1.6s
//magenta/scripts:convert_dir_to_note_sequences_test                     PASSED in 1.8s
//magenta/models/drums_rnn:drums_rnn_create_dataset_test                 FAILED in 1 out of 2 in 1.9s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/drums_rnn/drums_rnn_create_dataset_test/test.log
//magenta/models/improv_rnn:improv_rnn_create_dataset_test               FAILED in 1 out of 2 in 2.0s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/improv_rnn/improv_rnn_create_dataset_test/test.log
//magenta/models/melody_rnn:melody_rnn_create_dataset_test               FAILED in 1 out of 2 in 1.9s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/melody_rnn/melody_rnn_create_dataset_test/test.log
//magenta/models/polyphony_rnn:polyphony_rnn_create_dataset_test         FAILED in 1 out of 2 in 2.3s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_rnn_create_dataset_test/test.log
//magenta/models/rl_tuner:rl_tuner_test                                  FAILED in 1 out of 2 in 2.3s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/rl_tuner/rl_tuner_test/test.log
//magenta/models/shared:events_rnn_graph_test                            FAILED in 1 out of 2 in 1.9s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/shared/events_rnn_graph_test/test.log
//magenta/music:musicnet_io_test                                         FAILED in 1 out of 2 in 1.7s
  /home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/musicnet_io_test/test.log

Executed 36 out of 36 tests: 29 tests pass and 7 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

**I have opened the failed test logs and I found that all of them share the same reason like:\  AttributeError: 'module' object has no attribute 'rnn_cell'
one of the test logs looks like:**

exec ${PAGER:-/usr/bin/less} "$0" || exit 1

Traceback (most recent call last):
  File "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/bin/magenta/models/improv_rnn/improv_rnn_create_dataset_test.runfiles/__main__/magenta/models/improv_rnn/improv_rnn_create_dataset_test.py", line 20, in <module>
    from magenta.models.improv_rnn import improv_rnn_create_dataset
  File "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/bin/magenta/models/improv_rnn/improv_rnn_create_dataset_test.runfiles/__main__/magenta/models/improv_rnn/improv_rnn_create_dataset.py", line 26, in <module>
    from magenta.models.improv_rnn import improv_rnn_config_flags
  File "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/bin/magenta/models/improv_rnn/improv_rnn_create_dataset_test.runfiles/__main__/magenta/models/improv_rnn/improv_rnn_config_flags.py", line 19, in <module>
    from magenta.models.improv_rnn import improv_rnn_model
  File "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/bin/magenta/models/improv_rnn/improv_rnn_create_dataset_test.runfiles/__main__/magenta/models/improv_rnn/improv_rnn_model.py", line 21, in <module>
    from magenta.models.shared import events_rnn_model
  File "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/bin/magenta/models/improv_rnn/improv_rnn_create_dataset_test.runfiles/__main__/magenta/models/shared/events_rnn_model.py", line 25, in <module>
    from magenta.models.shared import events_rnn_graph
  File "/home/jcc/.cache/bazel/_bazel_jcc/ed5599de3378c6e0a5a71ebe1650713e/execroot/magenta/bazel-out/local-opt/bin/magenta/models/improv_rnn/improv_rnn_create_dataset_test.runfiles/__main__/magenta/models/shared/events_rnn_graph.py", line 24, in <module>
    base_cell=tf.nn.rnn_cell.BasicLSTMCell,
AttributeError: 'module' object has no attribute 'rnn_cell'

**Comment by cghawthorne** [comment]
Can you give some more details about your environment? What version of magenta do you have installed, are you in the development environment? In what context are you trying to import magenta.protobuf?

**Comment by brisker** [comment]
@cghawthorne
I have rewrote my error and my environment is Ubuntu14.04,titan x gpu, cuda 7.5 , bazel 0.4.4 and cudnn5.0. 
I install the development version of magenta and the process of my installing is:
1. install bazel
2. install tensorflow
3. git clone https://github.com/tensorflow/magenta.git
4. cd magenta
5. bazel test //magenta/...

**Comment by cghawthorne** [comment]
I believe this particular problem has been fixed by #527, so I'll go ahead and close this bug. However, I suspect you'll now see an error related to importing 'parser'. I'm tracking that in #529.

**Comment by brisker** [comment]
@cghawthorne 
So right now, I can do nothing?

**Comment by cghawthorne** [comment]
@brisker there are a few things you could try:
- revert your git repo to cbee9fa (before the changes to use the new TensorFlow API) and use a version of TensorFlow older than 1.0
- locally build and install a Magenta pip package with your changes. the problems occur only when using the bazel wrappers around scripts and tests. building the pip package will let you run things outside of the bazel environment
- If you don't need to change any of the core Magenta libraries, you could just install our pip package and develop your changes outside of the repo.

Sorry for these problems, we're working to get them resolved as soon as possible.
