### ISSUE TITLE
Mido parser takes precedence over core python parser in unit tests

### ISSUE THREAD

**Issue by cghawthorne** [tensorflow/magenta#529]
Started a discussion here: https://groups.google.com/d/msg/bazel-discuss/NK4DuqDlY2w/jQY310XxCAAJ

**Comment by PeterMitrano** [comment]
This seems to be a blocking issue for not just unit tests. I get this same error when trying to use one of the generators:

    bazel-bin/magenta/models/melody_rnn/melody_rnn_generate --config=lookback_rnn --bundle_file=${PWD}/bundles/lookback_rnn.mag --output_dir=${PWD}/generated --primer_melody="[60]"

**Comment by PeterMitrano** [comment]
Also, is there a commit/version I can go back to that will allow me to use magenta without this issue?

**Comment by cghawthorne** [comment]
Just to update from the email thread:

I chatted with @kchodorow earlier today, and there's not a good workaround that doesn't involve modifying dependencies. The problem should be solved in Bazel 0.5, which should hopefully be released in a week or so.

@PeterMitrano you could try going back to cbee9fa, but you'll also need to make sure you're using a version of TensorFlow earlier than 1.0.

**Comment by cghawthorne** [comment]
Thanks to work from the Bazel team, we now have a workaround (#547). It requires Bazel 0.4.5, which is not yet released, but if you want to try it out, you can download a release candidate. I'll submit the CL once the release is officially available.
