### ISSUE TITLE
music xml parser (partial measure indicator)

### ISSUE THREAD

**Issue by Lizzard13** [tensorflow/magenta#534]
noticed that in the Music XML Parser there's a simple error- mxl file being used when it should be an xml file.  "testdata/flute_scale_with_png.mxl",

**Comment by adarob** [comment]
Hi @Lizzard13, I'm not very familiar with this part of the code, but are I believe it that particular test is for the compressed version of MusicXML (http://www.musicxml.com/tutorial/compressed-mxl-files/). Please re-open if I'm wrong. Thanks!
