### ISSUE TITLE
MIDI keyboard recommendation?

### ISSUE THREAD

**Issue by kazoo-kmt** [tensorflow/magenta#536]
Hi, this is a cool project and I'd like to start exploring. I don't have MIDI keyboard, so I'd like to know which MIDI keyboard do you use and if you have a recommendation, please let me know.

**Comment by RobertRivas** [comment]
http://www.akaipro.com/product/lpk25

This one is good.
Wait till you see it on sale for 40 - 50 dollars.

**Comment by kazoo-kmt** [comment]
Thank you. I'll look it!

**Comment by cghawthorne** [comment]
We've been using http://www.akaipro.com/product/mpk-mini-mkii in the office and for some of our demos, and it's worked well for us.
