### ISSUE TITLE
documentation: missing dependencies

### ISSUE THREAD

**Issue by mattetti** [tensorflow/magenta#540]
I installed magenta from scratch on a clean Mac using the README and some tests from`bazel test //magenta/...` were failing because of the missing dependencies:

```
pip install IPython
pip install intervaltree
```

The other failures are related to https://github.com/tensorflow/magenta/issues/529 and apparently should be fixed with the upcoming version of Bazel

This issue might be related to the fact that I wasn't using conda, which could totally be a user error.

**Comment by cghawthorne** [comment]
@mattetti in the [dev environment setup instructions](https://github.com/tensorflow/magenta#development-environment), we suggest looking at dependency list in setup.py for what to install. That should cover intervaltree, but you're right that we're currently missing IPython form that list. We'll get that fixed.
