### ISSUE TITLE
[style transfer] Big size of checkpoint after training compare to pre-trained model

### ISSUE THREAD

**Issue by guanjhensu** [tensorflow/magenta#546]
I trained a model with 12 style images following the instruction of the README.md: https://github.com/tensorflow/magenta/tree/master/magenta/models/image_stylization

However, the checkpoint output is very large:
model.ckpt-0.data-00000-of-00001  (574MB)
model.ckpt-0.index   (7KB)
model.ckpt-0.meta.  (2.2MB)

The pre-trained models provided, such as Monet.ckpt and Varied.ckpt, are only 6.8MB and 7.1MB respectively. How can I significantly reduce my model from 574MB to small size like the pre-trained models?

**Comment by lakeinchina** [comment]
it seems that train.py combines vgg with transformer , then it saves vgg&transformer at same time.

**Comment by guanjhensu** [comment]
Thanks for your comment! 
But is there any way to drop vgg out of the checkpoint?

**Comment by lakeinchina** [comment]
modify image_stylization_train.py
```python
from tensorflow.contrib.framework.python.ops import variables

savertransformer = tf.train.Saver(variables.get_variables("transformer"))
# Run training
slim.learning.train(
    train_op=train_op,
    logdir=os.path.expanduser(FLAGS.train_dir),
    master=FLAGS.master,
    is_chief=FLAGS.task == 0,
    number_of_steps=FLAGS.train_steps,
    init_fn=init_fn,
    saver=savertransformer,
    save_summaries_secs=FLAGS.save_summaries_secs,
    save_interval_secs=FLAGS.save_interval_secs)
```
 That will only save the transformer network,~20mb.
but I do not know where the remaining 13mb comes from.

**Comment by guanjhensu** [comment]
Thanks a lot. It solves the big size problem!

**Comment by haikuoyao** [comment]
hi @lakeinchina @guanjhensu 

What do you set for  `init_fn `?

Do you still use 
```
saver = tf.train.Saver(slim.get_variables('vgg_16'))

def init_fn(session):
      saver.restore(session, vgg.checkpoint_file())
```
