### ISSUE TITLE
polyphony_rnn_train: Incpomatible shapes (InvalidArgumentError)

### ISSUE THREAD

**Issue by Nimeas** [tensorflow/magenta#549]
Hi all,

I was wondering what output would a polyphony_rnn give when trained on some jazzy tunes, so I gathered some midi files from [The Jazz Page](http://www.thejazzpage.de/) and generated dataset, but when attempting to train, I get `Incompatible shapes`:

> InvalidArgumentError (see above for traceback): Incompatible shapes: [27776] vs. [28416]

I am attaching full error traceback [Here](https://gist.github.com/Nimeas/2e8c3cc641c82dc575f39bfe54da6dfc#file-terminal_executions-log), including output from dataset preparation.

I use tensorflow-gpu r0.12 (in order to workaround #538 as suggested by @brannondorsey)

Any hints would be highly appreciated.

Thanks!

**Comment by pkmital** [comment]
I'm running into this as well.  I think this is related to https://github.com/tensorflow/magenta/issues/525

By default the polyphony model has `skip_first_n_losses` set to 10.  

I tried passing the hyperparms as a flag, (e.g.: `--hparams="{'batch_size': 100, 'skip_first_n_losses':0}"` but I still get different parameters being printed when I call the train method, e.g.:
```
INFO:tensorflow:hparams = {'rnn_layer_sizes': [256, 256, 256], 'decay_rate': 0.95, 'dropout_keep_prob': 0.5, 'batch_size': 64, 'decay_steps': 1000, 'clip_norm': 5, 'initial_learning_rate': 0.001, 'skip_first_n_losses': 10...
```

So it seems there might be two potential issues, 1 as described in https://github.com/tensorflow/magenta/issues/525 w/ nonzero `skip_first_n_losses`, and another w/ setting `hparams` on the polyphony CLI interface for training.

**Comment by MarkYHZhang** [comment]
From my testing, the pull request https://github.com/tensorflow/magenta/pull/551 eliminates this error.

**Comment by wilderfield** [comment]
I am also having the problem of hparams taking no effect. Mac OSx. I used the provided script to install everything. No matter what my --hparams is defined to be, I am getting a log that prints:
INFO:tensorflow:hparams = {'rnn_layer_sizes': [256, 256, 256], 'decay_rate': 0.95, 'dropout_keep_prob': 0.5, 'batch_size': 64, 'decay_steps': 1000, 'clip_norm': 5, 'initial_learning_rate': 0.001, 'skip_first_n_losses': 10}

And training runs forever... even if I tell it to run 1 training step
