### ISSUE TITLE
Cannot set up MIDI interface: qjackctl vmpk fail to start on Ubuntu 16.04

### ISSUE THREAD

**Issue by neovaldivia** [tensorflow/magenta#550]
Has anybody overcome this error:
QXcbConnection: Could not connect to display
Aborted (core dumped)
****

I am trying to set up the MIDI interface, thanks!

**Comment by neovaldivia** [comment]
$ vmpk
vmpk: cannot connect to X server

**Comment by cghawthorne** [comment]
@neovaldivia the MIDI interface instructions assume you are using a local machine with a local display. If you're running vmpk remotely, you'll need to set up some sort of tunneling for both X and sound.
