### ISSUE TITLE
import error?? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [tensorflow/magenta#552]
```
D:\Temp>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import magenta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Python35\lib\site-packages\magenta-0.1.9-py3.5.egg\magenta\__init__.py", line 26, in <module>
  File "D:\Programs\Python35\lib\site-packages\magenta-0.1.9-py3.5.egg\magenta\common\__init__.py", line 17, in <module>
ImportError: No module named 'sequence_example_lib'
```

I manually copied `setup.py` and manually installed all requirements, installed `tensorflow-gpu` so I removed `tensorflow >= 1.0.0` from `setup.py` so `pkg_resources` won't report error. But anyways it occours this error which has no reason since I checked there isn't a file missing installed.

**Comment by cghawthorne** [comment]
@DefinitlyEvil can you try installing the newly released 0.1.10 version of our pip package and see if you continue to have errors?

**Comment by DefinitlyEvil** [comment]
@cghawthrone hai, thanks. Is the packaged named magenta?

**Comment by cghawthorne** [comment]
Yes, please see our installation instructions here: https://github.com/tensorflow/magenta#python-pip

**Comment by DefinitlyEvil** [comment]
ok, i've read it. I guess the reason it can't find the package is that I am using Python 3.5, and i installed all requirements but still no luck. :'(

**Comment by cghawthorne** [comment]
Magenta currently requires Python 2.7. I'd suggest setting up a 2.7 environment (you can use conda to do this without changing your system python version) and trying the installation again.

**Comment by DefinitlyEvil** [comment]
@cghawthorne ahhh da**, TensorFlow doesn't have a build for Windows with GPU and Python 2.7.
