### ISSUE TITLE
latest pip install version (0.1.9) does not work on TensorFlow 1.0

### ISSUE THREAD

**Issue by icoxfog417** [tensorflow/magenta#554]
Because the location of `BasicLSTMCell` is moved from `tf.nn.rnn_cell.BasicLSTMCell` to `tf.contrib.rnn.BasicLSTMCell`, the script causes error.

`setup.py` [does not specify the upper version of TensorFlow](https://github.com/tensorflow/magenta/blob/v0.1.9/magenta/tools/pip/setup.py#L31), **everyone who installed magenta after TensorFlow 1.0 release will face the error**. 

I know the fix is already done, so the package that based on latest code have to be released soon.

* [magenta 0.1.9](https://github.com/tensorflow/magenta/blob/v0.1.9/magenta/models/shared/events_rnn_graph.py#L24)
  * `base_cell=tf.nn.rnn_cell.BasicLSTMCell`
* [magenta master](https://github.com/tensorflow/magenta/blob/master/magenta/models/shared/events_rnn_graph.py#L24)
  * `base_cell=tf.contrib.rnn.BasicLSTMCell`

I confirmed magenta `0.1.9` works on TensorFlow `0.12`, but on `1.0.1` (may be `1.0` also because `tensorflow/tensorflow/python/ops/rnn_cell.py` is [erased on `1.0` branch on TensorFlow](https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/python/ops/rnn_cell.py))

**Comment by cghawthorne** [comment]
We just released version 0.1.10 of the pip package, which should solve these problems.
