### ISSUE TITLE
no such file or directory when creating training samples

### ISSUE THREAD

**Issue by leonfrank** [tensorflow/magenta#555]
when I tried to generate training samples like the following:

SEQUENCES_TFRECORD=~/TensorFlow/magenta/music/train/notesequences.tfrecord
 
TRAIN_DATA=~/TensorFlow/magenta/music/train/training_melodies.tfrecord
 

EVAL_DATA=~n/TensorFlow/magenta/music/eval_melodies.tfrecord
 
EVAL_RATIO=0.10
 
bazel run //magenta/models/basic_rnn:basic_rnn_create_dataset -- \
--input=$SEQUENCES_TFRECORD \
--train_output=$TRAIN_DATA \
--eval_output=$EVAL_DATA \
--eval_ratio=$EVAL_RATIO

and I got the error above. How to fix that error?

**Comment by cghawthorne** [comment]
It looks like you're using a fairly old version of the code. Can you try syncing to head and trying again?
