### ISSUE TITLE
error running bazel test //magenta/...

### ISSUE THREAD

**Issue by jerryfan4** [tensorflow/magenta#557]
INFO: Elapsed time: 181.155s, Critical Path: 165.89s
//magenta/common:concurrency_test                                        PASSED in 4.8s
//magenta/common:tf_lib_test                                             PASSED in 3.2s
//magenta/interfaces/midi:midi_hub_test                                  PASSED in 21.9s
//magenta/music:chord_symbols_lib_test                                   PASSED in 13.3s
//magenta/music:chords_encoder_decoder_test                              PASSED in 3.9s
//magenta/music:chords_lib_test                                          PASSED in 3.8s
//magenta/music:drums_encoder_decoder_test                               PASSED in 3.2s
//magenta/music:drums_lib_test                                           PASSED in 4.0s
//magenta/music:encoder_decoder_test                                     PASSED in 3.9s
//magenta/music:events_lib_test                                          PASSED in 13.5s
//magenta/music:lead_sheets_lib_test                                     PASSED in 4.0s
//magenta/music:melodies_lib_test                                        PASSED in 4.0s
//magenta/music:melody_encoder_decoder_test                              PASSED in 3.9s
//magenta/music:musicxml_parser_test                                     PASSED in 8.8s
//magenta/music:note_sequence_io_test                                    PASSED in 4.3s
//magenta/music:sequence_generator_test                                  PASSED in 4.3s
//magenta/music:sequences_lib_test                                       PASSED in 3.9s
//magenta/pipelines:dag_pipeline_test                                    PASSED in 4.3s
//magenta/pipelines:drum_pipelines_test                                  PASSED in 4.4s
//magenta/pipelines:lead_sheet_pipelines_test                            PASSED in 4.3s
//magenta/pipelines:melody_pipelines_test                                PASSED in 4.3s
//magenta/pipelines:pipeline_test                                        PASSED in 3.4s
//magenta/pipelines:pipelines_common_test                                PASSED in 4.0s
//magenta/pipelines:statistics_test                                      PASSED in 13.6s
//magenta/scripts:convert_dir_to_note_sequences_test                     PASSED in 4.6s
//magenta/models/drums_rnn:drums_rnn_create_dataset_test                 FAILED in 1 out of 2 in 3.3s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/drums_rnn/drums_rnn_create_dataset_test/test.log
//magenta/models/improv_rnn:improv_rnn_create_dataset_test               FAILED in 1 out of 2 in 3.1s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/improv_rnn/improv_rnn_create_dataset_test/test.log
//magenta/models/melody_rnn:melody_rnn_create_dataset_test               FAILED in 1 out of 2 in 3.3s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/melody_rnn/melody_rnn_create_dataset_test/test.log
//magenta/models/polyphony_rnn:polyphony_encoder_decoder_test            FAILED in 1 out of 2 in 4.0s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_encoder_decoder_test/test.log
//magenta/models/polyphony_rnn:polyphony_lib_test                        FAILED in 1 out of 2 in 3.8s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_lib_test/test.log
//magenta/models/polyphony_rnn:polyphony_rnn_create_dataset_test         FAILED in 1 out of 2 in 3.2s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/polyphony_rnn/polyphony_rnn_create_dataset_test/test.log
//magenta/models/rl_tuner:rl_tuner_test                                  FAILED in 1 out of 2 in 6.9s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/rl_tuner/rl_tuner_test/test.log
//magenta/models/shared:events_rnn_graph_test                            FAILED in 1 out of 2 in 3.3s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/models/shared/events_rnn_graph_test/test.log
//magenta/music:midi_io_test                                             FAILED in 1 out of 2 in 9.7s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/midi_io_test/test.log
//magenta/music:musicnet_io_test                                         FAILED in 1 out of 2 in 4.0s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/music/musicnet_io_test/test.log
//magenta/pipelines:chord_pipelines_test                                 FAILED in 1 out of 2 in 4.1s
  /private/var/tmp/_bazel_fanfan/6e1852581665c223990199fd8033fcc0/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/chord_pipelines_test/test.log

Executed 36 out of 36 tests: 25 tests pass and 11 fail locally.

I checked those test.log files.  
They were all import errors such as this:

    from magenta.models.drums_rnn import drums_rnn_create_dataset
ImportError: cannot import name drums_rnn_create_dataset

Is there an easy fix for this?

**Comment by cghawthorne** [comment]
I think this is the same issue as #529.

**Comment by jerryfan4** [comment]
Thanks for the quick response.  I installed bazel 0.4.5 but I'm still getting 7 failed tests which are   ValueError: Attempted relative import in non-package

I'm using tensorflow 1.0.1, bazel 0.4.5, and python 2.7.13 on Mac OS X.

**Comment by cghawthorne** [comment]
Can you try downloading the latest version of bazel? When you posted, bazel 0.4.5 was only available as a release candidate.

**Comment by airsimonhan** [comment]
after I install conda ,this problem was solved.
