### ISSUE TITLE
Freezing polyphony dataset command

### ISSUE THREAD

**Issue by MarkYHZhang** [tensorflow/magenta#558]
I'm creating a dataset based on 436 MIDIs on a 8 core 16 GB Azure machine, it has been running for a hours... Yet the training_poly_tracks.tfrecord, as well as eval_poly_tracks.tfrecord are both still 0 bytes.

The convert_dir_to_note_sequences executed successfully so that shouldn't be one of the causing factors.

Problem can be avoided if the parameter `--recursive` is removed.

**Comment by cghawthorne** [comment]
Can you include the exact command you're running and the output it produces?
