### ISSUE TITLE
For image stylization  demo, strange result is created.

### ISSUE THREAD

**Issue by xiesiyuan** [tensorflow/magenta#562]
I follow the training process strictly under imagenet dataset, trying to train a model.
But after 40000 iters, very strang result is created by using image_styliation_transform.

![none_1](https://cloud.githubusercontent.com/assets/19420138/24047086/a7023fd2-0b5f-11e7-8424-857e583955d8.png)
![none_3](https://cloud.githubusercontent.com/assets/19420138/24047155/dcd1cd6c-0b5f-11e7-9a8c-1e70e1723fe2.png)

is this problem caused by damaged ImageNet dataset? I am so confused.

**Comment by xiesiyuan** [comment]
P.S. My ImageNet DataSet is created as follows:

https://github.com/tensorflow/models/tree/master/inception#getting-started

**Comment by dovanchan** [comment]
same problem, The result is strange.

**Comment by xiesiyuan** [comment]
The system has bug.... and we all don't know where is it.

**Comment by xiesiyuan** [comment]
I have fixed the bug. Very tricky.

**Comment by dovanchan** [comment]
how you do that?

**Comment by xuguozhi** [comment]
How did you fix that bug?

**Comment by xuguozhi** [comment]
My results are much better than yours, but too slow

**Comment by dovanchan** [comment]
@xiesiyuan  Hi, Can you share how did you fix that bug?

**Comment by justinej** [comment]
Any updates @xiesiyuan ? I'm getting a similar amount of distortion from training and transforming right out of the box.

**Comment by sann5130** [comment]
@xiesiyuan Could you please let us know how you fixed the bug? I am having similar trouble
