### ISSUE TITLE
FR: Allow splitting of GPU memory to prevent eval from failing

### ISSUE THREAD

**Issue by endofzero** [tensorflow/magenta#57]
Feature Request:

Add the ability to set scaling of memory, possibly via command line:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = 0.5)

This is to allow you to run train and eval at the same time. Currently, I have found that eval will often fail with a 2gb 760GTX as it cannot obtain enough resources as train will take all available memory, throwing the cuBLAS error seen when the GPU is out of memory.

A workaround is to consume GPU memory before running train, then release the memory and hope it is enough for eval to start.

cuda tk 8.0 / cudnn 5.0.5

**Comment by cinjon** [comment]
Hi there endofzero. Thanks for posting this. If you wanted to make a PR for this, that would be super helpful. I'm going to close it an issue though.
