### ISSUE TITLE
Can you provide a step-by-step tutorial on how to run magenta?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/magenta#587]
Can you provide a step-by-step tutorial on how to run magenta?

**Comment by smurthy1996** [comment]
Download a pre-made docker instance for magenta.
https://hub.docker.com/r/tensorflow/magenta/

**Comment by cghawthorne** [comment]
Our README contains step-by-step instructions for installation and links to several models, each of which have their own README with instructions: https://github.com/tensorflow/magenta/blob/master/README.md
