### ISSUE TITLE
Magenta development environment

### ISSUE THREAD

**Issue by Alihussain1** [tensorflow/magenta#588]
I'm trying to install development environment but when i use "bazel test //magenta/" command it doesn't start any tests the error is 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
INFO: Found 119 targets and 36 test targets...
ERROR: missing input file '//magenta/models/nsynth/wavenet:utils.py'.
ERROR: /home/ali/GP/magenta/magenta/music/BUILD:189:1: Creating runfiles tree bazel-out/local-opt/bin/magenta/music/encoder_decoder_test.runfiles failed: build-runfiles failed: error executing command /home/ali/.cache/bazel/_bazel_ali/7641c5cc658a2d9d5ea532c08e7667f6/execroot/magenta/_bin/build-runfiles bazel-out/local-opt/bin/magenta/music/encoder_decoder_test.runfiles_manifest ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/ali/GP/magenta/magenta/models/nsynth/wavenet/BUILD:10:1: //magenta/models/nsynth/wavenet:utils: missing input file '//magenta/models/nsynth/wavenet:utils.py'.
ERROR: /home/ali/GP/magenta/magenta/models/nsynth/wavenet/BUILD:10:1 1 input file(s) do not exist.
INFO: Elapsed time: 0.277s, Critical Path: 0.03s
//magenta/common:concurrency_test                                     NO STATUS
//magenta/common:tf_lib_test                                          NO STATUS
//magenta/interfaces/midi:midi_hub_test                               NO STATUS
//magenta/models/drums_rnn:drums_rnn_create_dataset_test              NO STATUS
//magenta/models/improv_rnn:improv_rnn_create_dataset_test            NO STATUS
//magenta/models/melody_rnn:melody_rnn_create_dataset_test            NO STATUS
//magenta/models/polyphony_rnn:polyphony_encoder_decoder_test         NO STATUS
//magenta/models/polyphony_rnn:polyphony_lib_test                     NO STATUS
//magenta/models/polyphony_rnn:polyphony_rnn_create_dataset_test      NO STATUS
//magenta/models/rl_tuner:rl_tuner_test                               NO STATUS
//magenta/models/shared:events_rnn_graph_test                         NO STATUS
//magenta/music:chord_symbols_lib_test                                NO STATUS
//magenta/music:chords_encoder_decoder_test                           NO STATUS
//magenta/music:chords_lib_test                                       NO STATUS
//magenta/music:drums_encoder_decoder_test                            NO STATUS
//magenta/music:drums_lib_test                                        NO STATUS
//magenta/music:encoder_decoder_test                                  NO STATUS
//magenta/music:events_lib_test                                       NO STATUS
//magenta/music:lead_sheets_lib_test                                  NO STATUS
//magenta/music:melodies_lib_test                                     NO STATUS
//magenta/music:melody_encoder_decoder_test                           NO STATUS
//magenta/music:midi_io_test                                          NO STATUS
//magenta/music:musicnet_io_test                                      NO STATUS
//magenta/music:musicxml_parser_test                                  NO STATUS
//magenta/music:note_sequence_io_test                                 NO STATUS
//magenta/music:sequence_generator_test                               NO STATUS
//magenta/music:sequences_lib_test                                    NO STATUS
//magenta/pipelines:chord_pipelines_test                              NO STATUS
//magenta/pipelines:dag_pipeline_test                                 NO STATUS
//magenta/pipelines:drum_pipelines_test                               NO STATUS
//magenta/pipelines:lead_sheet_pipelines_test                         NO STATUS
//magenta/pipelines:melody_pipelines_test                             NO STATUS
//magenta/pipelines:pipeline_test                                     NO STATUS
//magenta/pipelines:pipelines_common_test                             NO STATUS
//magenta/pipelines:statistics_test                                   NO STATUS
//magenta/scripts:convert_dir_to_note_sequences_test                  NO STATUS

Executed 0 out of 36 tests: 36 were skipped.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Can any one help me to figure out where the problem is ?

**Comment by cghawthorne** [comment]
Looks like an issue with the nsynth BUILD file.

**Comment by jesseengel** [comment]
My bad, it was building a target that wasn't there in NSynth. This should be fixed now.
