### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by lasconic** [tensorflow/magenta#589]
It's great to be able to run magenta in Docker. However, it would be even better if we could know in advance what we get in the docker container, like the version of tensorflow, availability of GPU support etc... Is the Dockerfile public? If yes, where? If not, could it be commited to the repository?

**Comment by icoxfog417** [comment]
You can use this repository.

[tensorflow/magenta](https://hub.docker.com/r/tensorflow/magenta/tags/)

Following is my application docker file that uses above magenta container.

[icoxfog417/magenta_session](https://github.com/icoxfog417/magenta_session/blob/master/Dockerfile)

**Comment by lasconic** [comment]
Sure, I know this repository and I used it. But there is no way to know before running the container which version of tensorflow is used and how the container is built.

**Comment by cghawthorne** [comment]
The Dockerfile used to build the container is available here: https://github.com/tensorflow/magenta/tree/master/magenta/tools/docker

**Comment by lasconic** [comment]
Sorry, I missed this file. Perfect !

**Comment by iliTheFallen** [comment]
@cghawthorne Where is tensorflow/magenta-gpu docker installation? Thank you!

**Comment by cghawthorne** [comment]
We don't currently support a Docker GPU container, but it shouldn't be too difficult to set up following the examples here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker

If you get it working, let us know if there are any tricks to get it to work correctly with the host GPU.
