### ISSUE TITLE
RL_tuner biases not found

### ISSUE THREAD

**Issue by Alihussain1** [tensorflow/magenta#590]
when i tried to run the rl_tuner using bazel run command it gives me an error that biases are not found in note_rnn.ckpt i tried downloading it my self but same error
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
NotFoundError (see above for traceback): Tensor name "rnn_model/rnn/multi_rnn_cell/cell_0/lstm_cell/biases" not found in checkpoint files /rl_tuner/note_rnn.ckpt
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by Calvin-Shen** [comment]
have the problem been solved?

**Comment by Alihussain1** [comment]
I trained a model myself and just used the ckpt with editing the parameters of the model to match my trained model and it worked, that was a long time ago I don't know if this is fixed now or not
