### ISSUE TITLE
rl_tuner train

### ISSUE THREAD

**Issue by Alihussain1** [tensorflow/magenta#597]
when i run rl_tuner_train using default checkpoint 

NotFoundError (see above for traceback): Tensor name "rnn_model/fully_connected/bias/Adam_1" not found in checkpoint files /home/ali/.cache/bazel/_bazel_ali/7641c5cc658a2d9d5ea532c08e7667f6/execroot/magenta/bazel-out/local-opt/bin/magenta/models/rl_tuner/rl_tuner_train.runfiles/__main__/note_rnn.ckpt
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_3/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_94_save_1/RestoreV2_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by kaviami** [comment]
I have a problem like this ,too.
It happens on restoring variables from checkpoint, maybe the codes needs the old version to run

**Comment by Alihussain1** [comment]
You're right i trained melody_rnn for 100 iterations and loaded it into rl_tumer to test it and it worked without any problems
