### ISSUE TITLE
Melody RNN README points to invalid blog posts

### ISSUE THREAD

**Issue by jsleep** [tensorflow/magenta#609]
https://github.com/tensorflow/magenta/blob/master/magenta/models/melody_rnn/README.md has links that point to the wrong blog posts for the information on lookback and attention models. 

What they link to currently:
https://magenta.tensorflow.org/2016/07/15/lookback-rnn-attention-rnn/

What they should link to:
https://magenta.tensorflow.org/blog/2016/07/15/lookback-rnn-attention-rnn/

**Comment by cghawthorne** [comment]
Sorry about that, we accidentally moved some old blog posts to a new URL structure. We've pushed a change to fix this, so the original links should work again: https://magenta.tensorflow.org/2016/07/15/lookback-rnn-attention-rnn/
