### ISSUE TITLE
The 'run' command is only supported from within a workspace

### ISSUE THREAD

**Issue by dinamix** [tensorflow/magenta#611]
Hello,

I realize this issue has been addressed in a previous post but I am wondering why I continue to get it even after following those steps. I try to run the following command for wavenet training:

bazel run //magenta/models/nsynth/wavenet/train -- --train_path=/Users/tano13/Download/nsynth-test/ --logdir=/Users/tano13/Documents/

and receive the following error ( in the subject line ) :

The 'run' command is only supported from within a workspace.

I believe this is either a problem I am having with bazel, which I have installed or it is because I need to run from the magenta project root, which I am not exactly sure what this means. For some context, I have used the automated script to install magenta and I have the tensorflow 1.1 version running.

Any help is appreciated.

**Comment by dinamix** [comment]
Upon further inspection it seems like in my magenta models folder from my miniconda directory:

~/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models

There is no nsynth directory. Is the nsynth code only available in the dev version. As mentioned, I used the automated build to make magenta.

**Comment by jsleep** [comment]
I'm assuming that NSynth hasn't been released with the latest pip package
which is probably what was installed when you did the automatic
installation. If you want to use NSynth right now you will probably need to
follow the instructions for setting up the dev environment. I'm sure
they'll be releasing NSynth with the next pip package release once they
have tools to do more than just train and save audio embeddings with NSynth.

**Comment by cghawthorne** [comment]
The comment from @jsleep is correct. At this point, if you want to you nsynth, you'll need to use the dev environment. We hope to make nsynth easier to use in the future.
