### ISSUE TITLE
Enhancement: Functionality to restart a training run from a specific or the last checkpoint.

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/magenta#62]
Best explained at this Google Groups Magenta Discus link

https://groups.google.com/a/tensorflow.org/d/msg/magenta-discuss/naLLtfCCjQM/R_Ho4FJZBQAJ

If your last checkpoint was at 1000 interations and you wanted to continue to 2000 iterations, the following code is Tensorflow style but does not work

```
TRAIN_DATA=/tmp/training_melodies.tfrecord

CHECKPOINT_DATA=basic_rnn.ckpt-1000

./bazel-bin/magenta/models/basic_rnn_train --experiment_run_dir=/tmp/basic_rnn/run1 --sequence_example_file=$TRAIN_DATA --eval=false --hparams='{"rnn_layer_sizes".[50],“model_checkpoint_path”:[$CHECKPOINT_DATA]}' --num_training_steps=2000

```

**Comment by hpssjellis** [comment]
So I have a repository setup at https://github.com/hpssjellis/magenta to address this issue. All I want to get working is for tensorflow to check if a RUN1 folder has already been made. If the folder exists then continue the training from the last checkpoint.

**Comment by danabo** [comment]
I posted in your thread what the change should look like.
https://groups.google.com/a/tensorflow.org/forum/#!topic/magenta-discuss/riVSW-dKJ3k

If you would like to fix it in your fork you are welcome to make a PR. Otherwise I will take care of it.

**Comment by hpssjellis** [comment]
Thanks @danabo 

Not yet perfect, still starting from zero checkpoint. See comment at

https://groups.google.com/a/tensorflow.org/forum/#!topic/magenta-discuss/riVSW-dKJ3k

**Comment by hpssjellis** [comment]
Hey Dan

I posted a partial solution thanks for the starting code.



Jeremy Ellis

twitter @rocksetta
website http://rocksetta.com

**Comment by danabo** [comment]
Here is a fix:
https://github.com/danabo/magenta/blob/basic_rnn_checkpoint_fix/magenta/models/basic_rnn/basic_rnn_train.py

This code worked for me. When training is resumed global step is loaded from the checkpoint. Let me know if this fixes your issue.

**Comment by hpssjellis** [comment]
Well done danabo. I think this enhancement can be closed since I see that it is in operation with the April 15, 2016 changes to magenta.
