### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by yunge** [tensorflow/magenta#63]
Please make it compatible with py3, thanks.

**Comment by cinjon** [comment]
@yunge, thanks for the request. We currently don't have the bandwidth to do this as we're busy working on other features, but we would gladly accept a PR that solves this.

**Comment by PeterChenYijie** [comment]
Hi,I want to know if it can be  compatible with py3. Because my envs is based on py3

**Comment by cghawthorne** [comment]
@PeterChenYijie, yes we do support Python 3. I'll update the README to make that a little more clear.
