### ISSUE TITLE
Nsynth data question: organ_acoustic_003 one velocity?

### ISSUE THREAD

**Issue by JamesOwers** [tensorflow/magenta#646]
Hello,

In the NSynth dataset, the training data instrument organ_acoustic_003 only has one velocity, and it appears to have an unusual value: 127. Is this intentional? e.g.

`.../nsynth/nsynth-train/audio/organ_acoustic_003-053-127.wav`

**Comment by JamesOwers** [comment]
It appears some instruments only have one velocity (127 - the max). I don't think this is explicitly stated in the documentation here (but could be wrong!): https://magenta.tensorflow.org/datasets/nsynth. I was expecting 5 velocities per note where some are duplicates.

**Comment by jesseengel** [comment]
Hi James, 

That's not a mistake, different instruments have different amounts of pitches and velocities available to them. As it says on the dataset page:

"Some instruments are not capable of producing all 88 pitches in this range, resulting in an average of 65.4 pitches per instrument. Furthermore, the commercial sample packs occasionally contain duplicate sounds across multiple velocities, leaving an average of 4.75 unique velocities per pitch."

If a sound had no variation across velocity, we only included the highest velocity, which is 127 as MIDI is 7-bit.

**Comment by JamesOwers** [comment]
Grand, cheers for clarifying.
