### ISSUE TITLE
cannot import sketch_rnn model

### ISSUE THREAD

**Issue by mobeets** [tensorflow/magenta#655]
I installed magenta with the automated installation script:

```
curl https://raw.githubusercontent.com/tensorflow/magenta/master/magenta/tools/magenta-install.sh > /tmp/magenta-install.sh
bash /tmp/magenta-install.sh
```

After `source activate magenta` here's what I get:

```bash
>>> from magenta.models import sketch_rnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name sketch_rnn
```

However, I can import other models, e.g., `from magenta.models import rl_tuner` works just fine.

(Though I have the same problem with importing `nsynth`.)

**Comment by cghawthorne** [comment]
Sorry about that. We hadn't yet updated the pip package to include sketch_rnn. It should be available now if you upgrade to the latest version (pip install -U magenta).
