### ISSUE TITLE
Ableton Plugin Requires 9.7.2

### ISSUE THREAD

**Issue by Miserlou** [tensorflow/magenta#656]
Any chance you could make a build for 9.6? :)

**Comment by jesseengel** [comment]
Sorry you're having trouble with the plugin. I'm not sure why it would require 9.7.2 besides being made with the most recent version of live. I know it's not exactly what you're asking, but if you do have 9.6 you should be able to upgrade to the most recent version of live for free https://www.ableton.com/en/help/article/latest-live-version/.
