### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by michaeljohnson200001** [tensorflow/magenta#662]
Hi, I'm a music producer, your project nsynth got my attention. i wanted try  to use it on my productions. I downloaded everything. And the only thing I got was a bunch of crap on my computer. Really if they want to change the music, develop a program, apk as they want to call it where the user can insert their own sounds and be able to synthesize something new. I tried the plugin for ableton, and it's interesting but its sounds are pure shit. Does not have quality.

**Comment by jesseengel** [comment]
Sorry it doesn't work for what you want. In terms of creating new samples, we should have code to allow for creating your own samples into the repo soon.
