### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ZeroDivisionError'

### ISSUE THREAD

**Issue by 12gjang** [tensorflow/magenta#673]
Hello,

I have just started to use magenta.

I am trying to train my model.

I converted music xml files to sequence,

And then I am trying to convert sequence to sequence examples for training rnn model.

But when I am doing this, it shows error like below.

> Traceback (most recent call last):
>   File "/Users/user/Desktop/magenta2/magenta/models/melody_rnn/melody_rnn_create_dataset.py", line 139, in <module>
>     console_entry_point()
>   File "/Users/user/Desktop/magenta2/magenta/models/melody_rnn/melody_rnn_create_dataset.py", line 135, in console_entry_point
>     tf.app.run(main)
>   File "/anaconda/envs/python27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "/Users/user/Desktop/magenta2/magenta/models/melody_rnn/melody_rnn_create_dataset.py", line 131, in main
>     FLAGS.output_dir)
>   File "/Users/user/Desktop/magenta2/magenta/pipelines/pipeline.py", line 371, in run_pipeline_serial
>     for name, outputs in _guarantee_dict(pipeline.transform(input_),
>   File "/Users/user/Desktop/magenta2/magenta/pipelines/dag_pipeline.py", line 509, in transform
>     stats_accumulator(unit, unit_inputs, stats))
>   File "/Users/user/Desktop/magenta2/magenta/pipelines/dag_pipeline.py", line 489, in stats_accumulator
>     results_ = unit.transform(single_input)
>   File "/Users/user/Desktop/magenta2/magenta/pipelines/melody_pipelines.py", line 57, in transform
>     except events_lib.ZeroDivisionError as detail:
> AttributeError: 'module' object has no attribute 'ZeroDivisionError'

To work with magenta, I temporarily modified the 
`except events_lib.ZeroDivisionError as detail:`
to
`except ZeroDivisionError as detail:`
in the
/piplines/melody_pipelines.py file

How can I fix this error in a proper way?

**Comment by adarob** [comment]
Thanks for pointing this out. I will fix it shortly.

**Comment by adarob** [comment]
Actually it looks like this is a symptom of a bug in the musicxml parser that sometimes leads to having a 0 in the numerator of the time signature. Ultimately we should fix that and remove this catch.

**Comment by cghawthorne** [comment]
The root bug is in #674. For now, we should have a way of detecting this error and skipping the file.

**Comment by adarob** [comment]
#675 should temporarily fix this by skipping the offending files.
