### ISSUE TITLE
MusicXML Time Signature Parsing issues

### ISSUE THREAD

**Issue by cghawthorne** [tensorflow/magenta#674]
We found several issues with the MusicXML parser while trying to parse this file: http://www.choeurlimours.com/private/partitions/P292_79_150421181329.mxl

The result of parsing this file is that there are many more time signatures in the resulting NoteSequence than in the MusicXML file, and many of them have a numerator of 0.

I did a little bit of investigation, and the issue is in `_fix_time_signature`. The two main problems were:
* If there is a measure that contains nothing but `<forward duration='16' />` without any notes, then this is interpreted as a duration of 0.
* For part of this particular score, it has a time signature of 12/8, but in `_fix_time_signature`, that is interpreted using `Fraction`, which turns it in to 3/2. This means that the measure appears to have a new time signature since it's different from what was in the score.

**Comment by cghawthorne** [comment]
@jsawruk would you have time to look into this?

**Comment by jsawruk** [comment]
I'll investigate it in a few days. Thanks for your initial analysis.

**Comment by jsawruk** [comment]
This is an unusual file. Finale and Sibelius imported the `<forward duration='16' />` by simply omitting the measures, giving a fractured score layout. Dorico inserted a whole measure rest in those measures. My plan is to insert a rest when encountering a `<forward>` in some cases. It might be ok to do in all cases; I need to think about this more.

**Comment by cghawthorne** [comment]
The file was created in MuseScore, and when you open the file with that program, it interprets it as an empty measure.

I think adding a rest to what would otherwise be an empty measure is a reasonable solution.

**Comment by jsawruk** [comment]
It definitely makes sense to add a whole measure rest if the `<forward>` is the only element in that measure. I am just wondering if it makes sense to add rest for any `<forward>` element. I don't think it would make sense to generalize, because the model might learn too many rests. I will just insert rests for the whole measure rest case.
