### ISSUE TITLE
It can't convert midi or xml files that contain capital letter extension. 

### ISSUE THREAD

**Issue by 12gjang** [tensorflow/magenta#677]
Hello,
I am training melody_rnn using various music datasets.
In some datasets, they have a midi file that contains capital letter extension like 'music.MID'.
But `convert_dir_to_note_sequence`  can't read them.

>  INFO:tensorflow:Unable to find a converter for file /Users/user/Desktop/magenta2/train_midi/test/example.MID

I suggest modifying comparing method to does not distinguish capital and small letter in file extension at line 84 of `/scripts/convert_dir_to_note_sequences.py` file

**Comment by adarob** [comment]
Thanks. Would you be willing to submit a pull request to correct this?

**Comment by 12gjang** [comment]
Sorry, I didn't know the pull request function. I have done that just now.
