### ISSUE TITLE
Link to Bach Chorales dataset is no longer available

### ISSUE THREAD

**Issue by zhou13** [tensorflow/magenta#687]
In https://github.com/tensorflow/magenta/tree/master/magenta/models/polyphony_rnn, it refers to Bach Chorales dataset http://www.jsbchorales.net/xml.shtml, which is 404 now.

**Comment by cghawthorne** [comment]
Yeah, I'm not sure why the site is down or if it will come back at some point (the error page indicates that it is "temporarily" unavailable). I included the archive.org link, which should work even if the site is down, but perhaps that should be made more prominent.
