### ISSUE TITLE
Curious about where can I find the sketch-RNN demo douglaseck showed in Google I/O Friday afternoon?

### ISSUE THREAD

**Issue by jaimezwalker** [tensorflow/magenta#688]
I've searched across internet but all I find is [quick draw](https://quickdraw.withgoogle.com/) and other [ai experiments](https://aiexperiments.withgoogle.com/) which is drawing and recognize the drawing. Where can I find the demo of machine continue drawing rain drops after I draw a cloud?  Thanks!!!

**Comment by hardmaru** [comment]
We plan to release the JavaScript demo in the near future. Please keep an
eye out for it :-)
