### ISSUE TITLE
No Such File or Directory Error When Trying to Create SequenceExamples

### ISSUE THREAD

**Issue by Voxmanns** [tensorflow/magenta#690]
Here be the code as it runs:
```
(magenta) Nathaniels-MacBook-Pro:~ Nathaniel$ melody_rnn_create_dataset \
> --config=</Users/Nathaniel/Documents/Music/Magenta/RNN/basic_rnn.mag> \
> --input=/Users/Nathaniel/Documents/Music/Magenta/tmp/notesequences.tfrecord \
> --output_dir=/Users/Nathaniel/Documents/Music/Magenta/tmp/melody_rnn/sequence_examples \
> --eval_ratio=0.10
-bash: --input=/Users/Nathaniel/Documents/Music/Magenta/tmp/notesequences.tfrecord: No such file or directory
```

I'm pretty basic when it comes to coding. I really only know how to fumble my way through it and I am trying to learn this system. But I do know for a fact that there is such a file in this directory. I have triple checked everything and directly copied and pasted both the path and file name, made sure it was right again, and still get this error.

The one time I got passed it I had discovered 2 spaces at the end of the notesequence file. I removed them, ran the script, got the same error for the output_dir line. I then ran the very same commands (literally pasted them again and hit enter) and it went back to the input error I bring up now.

Any help would be great! Thank you!

**Comment by cghawthorne** [comment]
Hi @Voxmanns. I think the problem is with this part of your command:

```
--config=</Users/Nathaniel/Documents/Music/Magenta/RNN/basic_rnn.mag>
```

It shouldn't have the angle brackets and it should reference the name of a config, not a bundle file. It should look something like:

```
--config=basic_rnn
```

**Comment by Voxmanns** [comment]
cghawthorne,

Much appreciated! I don't know if that was the core problem or not but after sleeping on it and fiddling with a few characters I got it to work. Thank you!
