### ISSUE TITLE
Create_dataset script is killed

### ISSUE THREAD

**Issue by Elviond** [tensorflow/magenta#696]
When I launch a create_dataset script (no matter if it's from melody_rnn, pianoroll, etc), it's killed after about 14 minutes.

> root@be6671dcf830:/magenta-data# pianoroll_rnn_nade_create_dataset \
> --input=/magenta-data/notesequences.tfrecord \
> --output_dir=/magenta-data/sequence_examples \
> --eval_ratio=0.10
> Killed

I'm running this on docker (Windows 10 Home x64)

**Comment by cghawthorne** [comment]
That could be caused by running out of memory. I'd take a look at what kinds of errors show up if you run the `dmesg` command. You may need to allocate more memory for your container.
