### ISSUE TITLE
improv_rnn_create_dataset  failed  

### ISSUE THREAD

**Issue by b03201003** [tensorflow/magenta#697]
Hi!
I'm trying this:
"improv_rnn_create_dataset --config='basic_improv'   --input=./sequences/notesequences.tfrecord --output_dir=./improv_rnn/sequence_examples --eval_ratio=0.10"
by using the Nottingham Database of folk tunes mentioned in http://deeplearning.net/tutorial/rnnrbm.html.
  
However, I get "INFO:tensorflow:Processed 1037 inputs total. Produced 0 outputs."
The melody_rnn_create_dataset done successfully with the same notesequences.tfrecord.
I'm wondering if there is any restriction on music data when using improv_rnn or polyphonic_rnn.

Here is the all info  in terminal when I executed improv_rnn_create_dataset:
“INFO:tensorflow:Processed 500 inputs so far. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_coincident_chords: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_empty_chord_progressions: 49 1
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_long: 0 679
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_short: 131
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_truncated: 16
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melody_lengths_in_bars:O:tensorflow:DAGPipeline_RandomPartition_training_lead_sheets_
  [10,20): 3
  [20,30): 13201003de-MacBook-Pro:models b03201003$ improv_rnn_create_da  [30,40): 35g='basic_improv'   --input=./sequences/notesequences.tfreco  [40,50): 9dir=./improv_rnn/sequence_examples --ev
  [50,100): 1
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_polyphonic_tracks_discarded: 57
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_coincident_chords: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_empty_chord_progressions: 451
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_short: 66
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_truncated: 102
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melody_lengths_in_bars:
  [7,8): 1
  [8,10): 6
  [10,20): 42
  [20,30): 43
  [30,40): 295
  [40,50): 64
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_polyphonic_tracks_discarded: 470
INFO:tensorflow:DAGPipeline_RandomPartition_eval_lead_sheets_count: 52
INFO:tensorflow:DAGPipeline_RandomPartition_training_lead_sheets_count: 448
INFO:tensorflow:Processed 1000 inputs so far. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_coincident_chords: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_empty_chord_progressions: 86
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_short: 31
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_truncated: 27
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melody_lengths_in_bars:
  [10,20): 3
  [20,30): 1
  [30,40): 66
  [40,50): 15
  [50,100): 1
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_polyphonic_tracks_discarded: 97
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_coincident_chords: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_empty_chord_progressions: 901
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_short: 116
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_truncated: 192
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melody_lengths_in_bars:
  [7,8): 1
  [8,10): 8
  [10,20): 67
  [20,30): 68
  [30,40): 683
  [40,50): 74
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_polyphonic_tracks_discarded: 943
INFO:tensorflow:DAGPipeline_RandomPartition_eval_lead_sheets_count: 90
INFO:tensorflow:DAGPipeline_RandomPartition_training_lead_sheets_count: 910
INFO:tensorflow:

Completed.

INFO:tensorflow:Processed 1037 inputs total. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_coincident_chords: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_empty_chord_progressions: 92
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_discarded_too_short: 31
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melodies_truncated: 29
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_melody_lengths_in_bars:
  [10,20): 4
  [20,30): 2
  [30,40): 68
  [40,50): 17
  [50,100): 1
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_eval_polyphonic_tracks_discarded: 102
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_coincident_chords: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_empty_chord_progressions: 935
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_discarded_too_short: 117
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melodies_truncated: 199
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_melody_lengths_in_bars:
  [7,8): 2
  [8,10): 9
  [10,20): 73
  [20,30): 74
  [30,40): 695
  [40,50): 82
INFO:tensorflow:DAGPipeline_LeadSheetExtractor_training_polyphonic_tracks_discarded: 974
INFO:tensorflow:DAGPipeline_RandomPartition_eval_lead_sheets_count: 95
INFO:tensorflow:DAGPipeline_RandomPartition_training_lead_sheets_count: 942”

Any information would be appreciated:)

**Comment by iansimon** [comment]
The improv RNN model needs to train on "lead sheets" which have both chords and melody.  The dataset you're using contains only MIDI files, which have no chord information.

If your MIDI files contain "chords" as notes and you want to modify the code, you can try calling sequences_lib.infer_chords_for_sequence somewhere in the input pipeline, but it's just going to be guessing the chords and might choke on some inputs.
