### ISSUE TITLE
Latest release of magenta is out of sync with latest sketch_rnn model data (resulting in AttributeError when running sketch_rnn.ipynb)

### ISSUE THREAD

**Issue by colinmorris** [tensorflow/magenta#700]
To repro:

- perform an 'automated install' of Magenta (using install script)
- download and run magenta/magenta/models/sketch_rnn/sketch_rnn.ipynb
- cell 8 (the call to `load_env`) fails with `AttributeError: 'list' object has no attribute 'startswith'` 

In dabe10468e6664cbdfde19e594327bfb5bfbc579 and 8b6151754c6010d9cb1bd48ab765d2b3ffa51f66 the `data_set` parameter was changed from a string to a list. The problem is:

- the latest version of magenta on pip (0.1.12) does not include these changes
- the latest model data at http://download.magenta.tensorflow.org/models/sketch_rnn.zip, which the ipython notebook automatically downloads, *does* use this convention. It includes a `model_config.json` file which has a list value for `data_set` (which overwrites the default string value in the source).

**Comment by cghawthorne** [comment]
@hardmaru if we just release a new pip package, will that fix this?

**Comment by hardmaru** [comment]
Yes, I believe an updated pip package would fix this.

**Comment by gautam1858** [comment]
So how to overcome this ?

**Comment by colinmorris** [comment]
@gautam1858 the simplest workaround is to just manually edit the `model_config.json` file for the model you're using (by default, they'll save under /tmp/sketch_rnn/models). Just replace `"data_set": ["foo.npz"],` with `"data_set": "foo.npz",`.

(You could also install the latest Magenta from source, but that's more work.)

**Comment by cghawthorne** [comment]
Magenta v0.1.13 has been released and should resolve this issue.
