### ISSUE TITLE
freeze graph / optimize for inference / ios - tf-coreml converter

### ISSUE THREAD

**Issue by johndpope** [tensorflow/magenta#715]
I'm having trouble porting the rnn .mag models over to ios.
https://github.com/xmartlabs/Bender/issues/21

I need to run a freeze graph / optimize for inference operation on the checkpoint and graph 
I have gone some odd lengths to extract this from .mag files to no avail.
https://gist.github.com/johndpope/99038722132de7f1e80ad96bd7e7e21f

so far - I have downloaded attention_rnn.mag
 > ran it through some swift code to extract the checkpoint file / graph file
https://gist.github.com/johndpope/442426d8bda7b6cbfee908b329286f87
 > attention_rnn.chkpt.meta /attention_rnn.pbtxt

then attempted to convert the extracted files via this freeze script
https://gist.github.com/johndpope/99038722132de7f1e80ad96bd7e7e21f

there's some numbers and question marks inside the above script that I'd appreciate if anyone can shed light on. 

UPDATE - found the script to dump .mag files 
https://raw.githubusercontent.com/tensorflow/magenta/d8efb2a1984caadddd5e9290853b196dd90eba4a/magenta/scripts/unpack_bundle.py

still in the dark with the nodes / freezing will keep trying.

**Comment by johndpope** [comment]
thus far

import tensorflow as tf
from tensorflow.python.tools import freeze_graph
from PIL import Image
import numpy as np
print "start.."
freeze_graph.freeze_graph('attention_rnn.pb',"",True,
                'attention_rnn.chkpt',
                'mul',
                'save_1/restore_all','save_1/Const:0',
                'attention_rnn_frozen.pb',
                True,"")

print "end..."


start..
Traceback (most recent call last):
  File "gen_freeze_graph.py", line 11, in <module>
    True,"")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 179, in freeze_graph
    variable_names_blacklist)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 87, in freeze_graph_with_def_protos
    _ = importer.import_graph_def(input_graph_def, name="")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
    node, 'Input tensor %r %s' % (input_name, te)))
ValueError: graph_def is invalid at node u'save_1/Assign': Input tensor 'RNN/AttentionCellWrapper/Attention/AttnV:0' Cannot convert a tensor of type float32 to an input of type float32_ref.

**Comment by adarob** [comment]
John, it sounds like we should be doing the freezing when we create the
.mag files.

Do you want to make a PR to add that functionality? We can then re-release
the .mag files pre-frozen.

**Comment by johndpope** [comment]
I'm afraid after running the scripts to dump out the checkpoint file
 bazel run magenta/scripts:unpack_bundle -- \
--bundle_path '/Users/jp/Documents/tensorflowWorkspace/magenta/attention_rnn.mag' --checkpoint_path '/Users/jp/Documents/tensorflowWorkspace/magenta/attention_rnn.mag.chkpt'

spits out -> **attention_rnn.pb**


then building 
bazel build tensorflow/tools/graph_transforms:summarize_graph
and running  
 
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=**attention_rnn.pb**
**No inputs spotted.**
**No variables spotted.**
**No outputs spotted.**
Found 5201907 (5.20M) const parameters, 0 (0) variable parameters, and 14 control_edges
Op types used: 43 Const, 14 Assign, 14 RestoreSlice, 1 NoOp
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=attention_rnn.pb --show_flops --input_layer= --input_layer_type= --input_layer_shape= --output_layer=

**Comment by johndpope** [comment]
conversely - 
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/Users/jp/Downloads/inception5h/**tensorflow_inception_graph.pb**
**Found 1 possible inputs: (name=input, type=float(1), shape=[])**
No variables spotted.
**Found 3 possible outputs: (name=output, op=Identity) (name=output1, op=Identity) (name=output2, op=Identity)**
Found 13462015 (13.46M) const parameters, 0 (0) variable parameters, and 0 control_edges
370 nodes assigned to device '/cpu:0'Op types used: 142 Const, 64 BiasAdd, 61 Relu, 59 Conv2D, 13 MaxPool, 9 Concat, 5 Reshape, 5 MatMul, 3 Softmax, 3 Identity, 3 AvgPool, 2 LRN, 1 Placeholder
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/Users/jp/Downloads/inception5h/tensorflow_inception_graph.pb --show_flops --input_layer=input --input_layer_type=float --input_layer_shape= --output_layer=output,output1,output2

**Comment by johndpope** [comment]
so digging into source code for Summarise_Graph - it seems that the code is simply looking for "Placeholder" ops.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/summarize_graph_main.cc#L129

**Comment by johndpope** [comment]
somebody has created this tensorflow to coreml converter.
https://github.com/tf-coreml/tf-coreml

I don't have time to test this - but it would nice to see magenta working on ios - so going to re-open this.  @adarob - it seems like the converter can accommodate frozen and non -frozen pb files. 
My remaining problem is simply to find the appropriate variable name for the input to match up.


```python

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'my_model.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     output_feature_names = ['softmax:0'])					
When input shapes are not fully specified in the frozen .pb file:

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'my_model.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     output_feature_names = ['softmax:0'],
                     input_name_shape_dict = {'input:0' : [1, 227, 227, 3]}) /// <- this input name is unknown to me
```

**Comment by johndpope** [comment]
TF graph must be cycle free (cycles are generally created due to control flow ops like if, while, map, etc.)


Supported Ops
List of TensorFlow ops that are supported currently (see tfcoreml/_ops_to_layers.py):

Add
ArgMax
AvgPool
BatchNormWithGlobalNormalization
BatchToSpaceND*
BiasAdd
ConcatV2, Concat
Const
Conv2D
Conv2DBackpropInput
DepthwiseConv2dNative
Elu
Exp
ExtractImagePatches
Fill*
FloorMod*
FusedBatchNorm
Gather*
Greater*
GreaterEqual*
Identity
Log
LogicalAnd*
LRN
MatMul
Max*
Maximum
MaxPool
Mean*
Min*
Minimum
MirrorPad
Mul
Neg
OneHot
Pad
Placeholder
Prod*
RandomUniform*
RealDiv
Reciprocal
Relu
Relu6
Reshape*
ResizeNearestNeighbor
Rsqrt
Shape
Sigmoid
Slice
Softmax
SpaceToBatchND*
Square
SquaredDifference
StridedSlice
Sub
Sum*
Tanh
Transpose*

**Comment by johndpope** [comment]
@adarob - did you ever hear of someone freezing the magenta graph? It would be nice to pick this up again some day - but stuck.

**Comment by johndpope** [comment]
digging deeper  from examples - @aseemw looks like he has a way to fix this
```python
Inception V1 Example
In this notebook we will go through the process of converting the Inception V1 model to a Neural Network Classifier CoreML model that directly predicts the class label of the input image. We will highlight the importance of setting the image preprocessing parameters correctly to get the right results. Lets get started!
Lets first download the inception V1 frozen TF graph (the .pb file)
In [ ]:
# Download the model and class label package
import os
import urllib
import tarfile
def download_file_and_unzip(url, dir_path='.'):
    """Download the frozen TensorFlow model and unzip it.
    url - The URL address of the frozen file
    dir_path - local directory
    """
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
    k = url.rfind('/')
    fname = url[k+1:]
    fpath = os.path.join(dir_path, fname)

    if not os.path.exists(fpath):
        urllib.urlretrieve(url, fpath)
    tar = tarfile.open(fpath)
    tar.extractall(dir_path)
    tar.close()

inception_v1_url = 'https://storage.googleapis.com/download.tensorflow.org/models/inception_v1_2016_08_28_frozen.pb.tar.gz'
download_file_and_unzip(inception_v1_url)
For conversion to CoreML, we need to find the input and output tensor names in the TF graph. This will also be required to run the TF graph for numerical accuracy check. Lets load the TF graph def and try to find the names
In [ ]:
# Load the TF graph definition
import tensorflow as tf
tf_model_path = './inception_v1_2016_08_28_frozen.pb'
with open(tf_model_path, 'rb') as f:
    serialized = f.read()
tf.reset_default_graph()
original_gdef = tf.GraphDef()
original_gdef.ParseFromString(serialized)

**# Lets get some details about a few ops in the beginning and the end of the graph**
with tf.Graph().as_default() as g:
    tf.import_graph_def(original_gdef, name='')
    ops = g.get_operations()
    N = len(ops)
    for i in [0,1,2,N-3,N-2,N-1]:
        print('\n\nop id {} : op type: "{}"'.format(str(i), ops[i].type));
        print('input(s):'),
        for x in ops[i].inputs:
            print("name = {}, shape: {}, ".format(x.name, x.get_shape())),
        print('\noutput(s):'),
        for x in ops[i].outputs:
            print("name = {}, shape: {},".format(x.name, x.get_shape())),
The output of the Placeholder op is the input ("input:0") and the output of the Softmax op towards the end of the graph is the output ("InceptionV1/Logits/Predictions/Softmax:0"). Lets convert to mlmodel now.
In [ ]:
import tfcoreml
# Supply a dictionary of input tensors' name and shape (with batch axis)
input_tensor_shapes = {"input:0":[1,224,224,3]} # batch size is 1
#providing the image_input_names argument converts the input into an image for CoreML
image_input_name = ['input:0']
# Output CoreML model path
coreml_model_file = './inception_v1.mlmodel'
# The TF model's ouput tensor name
output_tensor_names = ['InceptionV1/Logits/Predictions/Softmax:0']
# class label file: providing this will make a "Classifier" CoreML model
class_labels = 'imagenet_slim_labels.txt'

# Call the converter. This may take a while
coreml_model = tfcoreml.convert(
        tf_model_path=tf_model_path,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names,
        image_input_names = image_input_name,
        class_labels = class_labels)
Lets load an image for testing. We will get predictions on this image using the TF model and the corresponding mlmodel.
In [ ]:
# Now we're ready to test out the CoreML model with a real image!
# Load an image
import numpy as np
import PIL
import requests
from io import BytesIO
from matplotlib.pyplot import imshow
# This is an image of a golden retriever from Wikipedia
img_url = 'https://upload.wikimedia.org/wikipedia/commons/9/93/Golden_Retriever_Carlos_%2810581910556%29.jpg'
response = requests.get(img_url)
%matplotlib inline
img = PIL.Image.open(BytesIO(response.content))
imshow(np.asarray(img))
In [ ]:
# for getting CoreML predictions we directly pass in the PIL image after resizing
import coremltools
img = img.resize([224,224], PIL.Image.ANTIALIAS)
coreml_inputs = {'input__0': img}
coreml_output = coreml_model.predict(coreml_inputs, useCPUOnly=True)
coreml_pred_dict = coreml_output['InceptionV1__Logits__Predictions__Softmax__0']
coreml_predicted_class_label = coreml_output['classLabel']

#for getting TF prediction we get the numpy array of the image
img_np = np.array(img).astype(np.float32)
print 'image shape:', img_np.shape
print 'first few values: ', img_np.flatten()[0:4], 'max value: ', np.amax(img_np)
img_tf = np.expand_dims(img_np, axis = 0) #now shape is [1,224,224,3] as required by TF

# Evaluate TF and get the highest label 
tf_input_name = 'input:0'
tf_output_name = 'InceptionV1/Logits/Predictions/Softmax:0'
with tf.Session(graph = g) as sess:
    tf_out = sess.run(tf_output_name, 
                      feed_dict={tf_input_name: img_tf})
tf_out = tf_out.flatten()    
idx = np.argmax(tf_out)
label_file = 'imagenet_slim_labels.txt' 
with open(label_file) as f:
    labels = f.readlines()
    
#print predictions   
print('\n')
print("CoreML prediction class = {}, probabiltiy = {}".format(coreml_predicted_class_label,
                                            str(coreml_pred_dict[coreml_predicted_class_label])))  
print("TF prediction class = {}, probability = {}".format(labels[idx],
                                            str(tf_out[idx])))
Both the predictions match, this means that the conversion was correct. However, the class label seems incorrect. What could be the reason? The answer is that we did not preprocess the image correctly before passing it to the neural network!! This is always a crucial step when using neural networks on images.
How do we know what preprocessing to apply? This can be tricky to find sometimes. The approach is to find the source of the pre-trained model and check for the preprocessing that the author of the model used while training and evaluation. In this case, the TF model comes from the SLIM library so we find the preprocessing steps here
We see that the image pixels have to be scaled to lie in the interval [-1,1]. Lets do that and get the TF predictions again!
In [ ]:
img_tf = (2.0/255.0) * img_tf - 1
with tf.Session(graph = g) as sess:
    tf_out = sess.run(tf_output_name, 
                      feed_dict={tf_input_name: img_tf})
tf_out = tf_out.flatten()    
idx = np.argmax(tf_out)
print("TF prediction class = {}, probability = {}".format(labels[idx],
                                            str(tf_out[idx])))
Much better now! The model is predicting a dog as the highest class.
What about CoreML? CoreML automatically handles the image preprocessing, when the input is of type image, so we do not have to change the input that we were passing in earlier. For the mlmodel we converted, lets see what the image biases and scale have been set to
In [ ]:
# Get image pre-processing parameters of a saved CoreML model
from coremltools.proto import FeatureTypes_pb2 as _FeatureTypes_pb2


spec = coremltools.models.utils.load_spec(coreml_model_file)
if spec.WhichOneof('Type') == 'neuralNetworkClassifier':
  nn = spec.neuralNetworkClassifier
if spec.WhichOneof('Type') == 'neuralNetwork':
  nn = spec.neuralNetwork  
if spec.WhichOneof('Type') == 'neuralNetworkRegressor':
  nn = spec.neuralNetworkRegressor

preprocessing = nn.preprocessing[0].scaler
print 'channel scale: ', preprocessing.channelScale
print 'blue bias: ', preprocessing.blueBias
print 'green bias: ', preprocessing.greenBias
print 'red bias: ', preprocessing.redBias

inp = spec.description.input[0]
if inp.type.WhichOneof('Type') == 'imageType':
  colorspace = _FeatureTypes_pb2.ImageFeatureType.ColorSpace.Name(inp.type.imageType.colorSpace)
  print 'colorspace: ', colorspace
As suspected, they are not correct. Lets convert the model again and set them correctly this time. Note that the channel scale is multiplied first and then the bias is added.
In [ ]:
# Call the converter. This may take a while
coreml_model = tfcoreml.convert(
        tf_model_path=tf_model_path,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names,
        image_input_names = image_input_name,
        class_labels = class_labels,
        red_bias = -1,
        green_bias = -1,
        blue_bias = -1,
        image_scale = 2.0/255.0)
In [ ]:
# Call CoreML predict again
coreml_output = coreml_model.predict(coreml_inputs, useCPUOnly=True)
coreml_pred_dict = coreml_output['InceptionV1__Logits__Predictions__Softmax__0']
coreml_predicted_class_label = coreml_output['classLabel']
print("CoreML prediction class = {}, probability = {}".format(coreml_predicted_class_label,
                                            str(coreml_pred_dict[coreml_predicted_class_label])))
Yes, now its matching the TF output and is correct!!
Note that predictions with the default CoreML predict call (when the flag useCPUOnly=True is skipped) may vary slightly since it uses a lower precision optimized path that runs faster.
```

**Comment by wwpww** [comment]
How could I get the GraphDef about the model of onset&frames? And if freezing the model by coreml, is it proper for Android? Thank you very much!!!
