### ISSUE TITLE
sketch_rnn_train - error when running with no arguments

### ISSUE THREAD

**Issue by benxtan** [tensorflow/magenta#732]
When running sketch_rnn_train with no arguments, it tries to download a file that doesn't exist anymore: https://github.com/hardmaru/magenta/raw/master/aaron_sheep.npz

Which then gives the error
IOError: Failed to interpret file <cStringIO.StringI object at 0x7fc81010bb58> as a pickle

**Comment by hardmaru** [comment]
Should be resolved with Issue #734. Let me know if any problems still.
