### ISSUE TITLE
sketch-rnn - HParams update method error

### ISSUE THREAD

**Issue by brendansudol** [tensorflow/magenta#738]
the TF native HParam class does not have an `update` method to override hyperparams (i.e., https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py#L76)

I think switching to `parse_json` solves this; I added a PR with this change -- https://github.com/tensorflow/magenta/pull/737

PS: thanks for this super fun dataset and model :)

**Comment by adarob** [comment]
Thanks!
