### ISSUE TITLE
Errors with protobuf.bzl for Magenta tests

### ISSUE THREAD

**Issue by xrhan** [tensorflow/magenta#747]
I got the error message when trying to run magenta tests. Does anyone know how to resolve it?

ERROR: error loading package 'magenta/magenta/protobuf': Extension file not found. Unable to load package for '@protobuf//:protobuf.bzl': The repository could not be resolved.
ERROR: error loading package 'magenta/magenta/protobuf': Extension file not found. Unable to load package for '@protobuf//:protobuf.bzl': The repository could not be resolved.
INFO: Elapsed time: 0.226s
ERROR: Couldn't start the build. Unable to run tests.

Also, on some other posts it said we need the latest version of bazel and protobuf, I have:

$ bazel version
Build label: 0.5.1-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 12:34:07 2017 (1496752447)
Build timestamp: 1496752447
Build timestamp as int: 1496752447

$ protoc --version
libprotoc 3.3.0

**Comment by cghawthorne** [comment]
Hmm, I'm not seeing that error on my Mac using Bazel 0.5.2-homebrew. You could try updating to that version to see if it makes a difference.

Also make sure that you've synced the magenta repository to the latest commit.

It may also be worth trying the following:
```
bazel clean
bazel shutdown
```

And then retrying the test command.
