### ISSUE TITLE
midi_hub_test timeouts when running bazel test

### ISSUE THREAD

**Issue by yeshg** [tensorflow/magenta#759]
When I run `bazel test //magenta/...` all tests pass except for the midi_hub_test in /magenta/interfaces/midi which times out.

Console output:
`
TIMEOUT: //magenta/interfaces/midi:midi_hub_test (see /home/s/.cache/bazel/_bazel_s/5be385002debe164746de4f288331729/execroot/magenta-dev/bazel-out/local-opt/testlogs/magenta/interfaces/midi/midi_hub_test/test.log).

Executed 40 out of 40 tests: 39 tests pass and 1 fails locally.
`

After checking the test.log file I get this output, which looks like a failed redirection with the exec command. 

`
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
`

As this is the first issue with this test, I'm sure there is some local setup that I'm missing or have wrong. I'm running Ubuntu 16.04 with bazel 0.5.1

**Comment by adarob** [comment]
I have seen this as well but haven't had time to look into it yet. Thanks
for creating the issue.

**Comment by wayne-chen** [comment]
I also see the same issue in my macOS.

After running `bazel test //magenta/... --test_verbose_timeout_warnings`, I get this terminal [dump](https://gist.github.com/wayne-chen/c508cbaa8dbb08f6b48e077c5bd9a1c4#DUMP) with its associated [test.log](https://gist.github.com/wayne-chen/c508cbaa8dbb08f6b48e077c5bd9a1c4#file-test-log) file.

I'm running macOS 10.12.6 with bazel 0.5.2.
