### ISSUE TITLE
Typos in blog post

### ISSUE THREAD

**Issue by jdanford** [tensorflow/magenta#765]
I couldn't find contact info for either author of https://magenta.tensorflow.org/performance-rnn, and I don't see a repository for the blog itself, so this seemed like the best place to note that "one-shot" is misspelled as "one-hot" in the post:

> The neural network operates on a **one-hot** encoding over these 388 different events. A typical 30-second clip might contain ~1200 such **one-hot** vectors.

**Comment by adarob** [comment]
Jordan, "one-hot" (https://en.wikipedia.org/wiki/One-hot) is actually the intended term there.
Thanks for checking though!

**Comment by jdanford** [comment]
Haha my bad, guess I've been misreading that term for a while then!
