### ISSUE TITLE
Killed: 9  convert my midi file to NoteSequences

### ISSUE THREAD

**Issue by soma11soma11** [tensorflow/magenta#777]
When I tried to convert my midi file to NoteSequences according to 
https://github.com/tensorflow/magenta/blob/master/magenta/scripts/README.md

I got an error saying
Killed: 9

Is there any other way I can do this without less memory consumption?

**Comment by cghawthorne** [comment]
Hmm, the default setup for convert_dir_to_note_sequences shouldn't use too much memory (I would expect usage to increase if you used `--num_threads=4`, for example). Does the script produce any other output before getting killed? What happens if you try to convert a smaller number of midis?

**Comment by soma11soma11** [comment]
No it does not.
It just output which file it converted!
`INFO:tensorflow:Converted MIDI file lmd_full/0/00032fb2047d3cdd0394b89349d858b4.mid.`

**Comment by cghawthorne** [comment]
Does converting a fewer number of files help? Can you increase the amount of RAM on the machine you're using?

**Comment by soma11soma11** [comment]
The small number of data works fine!

**Comment by SkyrisBactera** [comment]
I've added a 50gb swap file simply to see if it would solve the issue. I left it on overnight and woke up to see that the program was frozen, but not killed. I also don't think that using less data is the solution

**Comment by mbs6176966** [comment]
I encountered the same problem, with 8g RAM generated 2.9G size of .tfrecord file,instead of using 8G RAM by using 32G RAM generate only 4 G size of .tfrecord file。anyone  could tell me the efficient solution.

**Comment by cghawthorne** [comment]
Tracking a potential solution in #888.
