### ISSUE TITLE
Please add the 'install' target

### ISSUE THREAD

**Issue by yurivict** [tensorflow/magenta#780]
Please add the 'install' target so that 'bazel install //magenta/...' will install it into the user-defined directory, just like configure/make do in GNU tools.

I would like to create a package, and it isn't obvious which files should go there. Project should do it itself.

**Comment by cghawthorne** [comment]
Unfortunately, bazel does not have an install command: https://docs.bazel.build/versions/master/bazel-user-manual.html

The closest thing would probably be to use our [build script](https://github.com/tensorflow/magenta/blob/master/magenta/tools/build.sh).
