### ISSUE TITLE
The code produces a black image instead of stylised image

### ISSUE THREAD

**Issue by akashdexati** [tensorflow/magenta#782]
I have setup magenta environment. Below is the url which has the code to stylize image using '**image_stylization_transform**'
_https://github.com/tensorflow/magenta/tree/master/magenta/models/image_stylization_

**The code runs and produces a black image output. where as the expectation is a stylised image output.**
Below is the terminal code that I used :-

>      (magenta) akash@Aakash-LenovoK:~$ image_stylization_transform \
>       --num_styles=32 \
>       --checkpoint=/home/akash/Desktop/TestPreTrainedModel/models/multistyle-pastiche-generator-varied.ckpt \
>       --input_image=/home/akash/Desktop/TestPreTrainedModel/testImg1.jpg \
>       --which_styles="[6,7]" \
>       --output_dir=/home/akash/Desktop/TestPreTrainedModel/output \
>       --output_basename="all_varied_styles"
(magenta) akash@Aakash-Lenovo-ideapad-300-15ISK:~$

**Comment by korrawat** [comment]
Related issue: #570
