### ISSUE TITLE
Bazel does not work currently with ubuntu 16.04

### ISSUE THREAD

**Issue by sauravskumar99** [tensorflow/magenta#79]
As of now Bazel which a requirement for magenta only works till ubuntu 15.10 ... Can somebody please direct me towards a solution to install magenta on ubuntu 16.04 . Thank you!

**Comment by rpagliarix** [comment]
you should try these two commands:

```
wget https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg 
sudo apt-key add apt-key.pub.gpg
```

and then follow the installation tutorial.

**Comment by cinjon** [comment]
Sauravskumar99, did this work for you?

**Comment by rpagliarix** [comment]
yes, it did

**Comment by cinjon** [comment]
Thanks rpagliarix.

**Comment by sauravskumar99** [comment]
yes it did... thank you
