### ISSUE TITLE
  An error occurred during manual installation(pip install magenta)

### ISSUE THREAD

**Issue by wwhonor123** [tensorflow/magenta#790]
ict-prototypes -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/home/wangwei/miniconda2/envs/magenta/include/python2.7 -c src/RtMidi.cpp -o build/temp.linux-x86_64-2.7/src/RtMidi.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    *# *src/RtMidi.cpp:2448:23: fatal error: jack/jack.h: no file or directory
     #include <jack/jack.h>**
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/wangwei/miniconda2/envs/magenta/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z_bbUS/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WlSMF4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-z_bbUS/python-rtmidi/

**Comment by reido2012** [comment]
Looks like you're missing dependencies for python_rtmidi

Make sure you have the dependencies installed
Linux: ALSA, JACK
OS X: CoreMIDI, JACK
Windows: MultiMedia (MM)

This link has the name of the packages that you can download -
http://python-rtmidi.readthedocs.io/en/latest/installation.html

The commands you'll most likely need to use as stated above are:
sudo apt-get install libasound-dev
sudo apt-get install libjack-dev

**Comment by wwhonor123** [comment]
According to your method has solved the problem,thanks!
