### ISSUE TITLE
Magenta performance-rnn training not using GPU

### ISSUE THREAD

**Issue by santiagobenoit** [tensorflow/magenta#791]
I am trying to train the performance-rnn from scratch on a new dataset, but it is using the cpu only. Is there a way I can specify which gpu to use from the command line? Here is the script I'm running:

```
python performance_rnn_train.py \
--config='performance_with_dynamics' \
--run_dir=/tmp/performance_rnn/logdir/run1 \
--sequence_example_file=/tmp/performance_rnn/sequence_examples/training_performances.tfrecord
```

**Comment by sanz999** [comment]
Update: I didn't touch anything, but it seems to have "decided" to start working... now it's using gpus. However, it would be helpful if I could specify which one(s) to use in the configuration without modifying magenta source or exporting CUDA_VISIBLE_DEVICES. Does anyone know if this is possible?

**Comment by mbs6176966** [comment]
have you install tensorflow-GPU,you can't install tensorflow-CPU，task will take precedence using tensorflow-CPU，so you should uninstall tensorflow-cpu first if you have both version.

**Comment by cghawthorne** [comment]
One other thing that may help with this is using the `magenta-gpu` pip package, which depends on `tensorflow-gpu`. The `magenta` package just depends on `tensorflow`, which is the CPU version.

After installing the GPU-enabled version of tensorflow, the CUDA_VISIBLE_DEVICES variable should work as expected.
