### ISSUE TITLE
Did you encounter this when creating a melody dataset?

### ISSUE THREAD

**Issue by wwhonor123** [tensorflow/magenta#794]
(magenta) wangwei@wangwei-Precision-T1700:~/magenta$ MIDI_DIRECTORY=/home/wangwei/magenta/magenta/music/train 
(magenta) wangwei@wangwei-Precision-T1700:~/magenta$ SEQUENCES_TFRECORD=/tmp/notesequences.tfrecord
(magenta) wangwei@wangwei-Precision-T1700:~/magenta$ 
(magenta) wangwei@wangwei-Precision-T1700:~/magenta$ bazel run //magenta:convert_midi_dir_to_note_sequences -- \
> --midi_dir=$MIDI_DIRECTORY \
> --output_file=$SEQUENCES_TFRECORD \
> --recursive
ERROR: no such target '//magenta:convert_midi_dir_to_note_sequences': target 'convert_midi_dir_to_note_sequences' not declared in package 'magenta' defined by /home/wangwei/magenta/magenta/BUILD.
INFO: Elapsed time: 0.024s
ERROR: Build failed. Not running target.
(magenta) wangwei@wangwei-Precision-T1700:~/magenta$

**Comment by cghawthorne** [comment]
I think you're trying to run the wrong target. Instead of `//magenta:convert_midi_dir_to_note_sequences`, use `//magenta/scripts:convert_dir_to_note_sequences`.
