### ISSUE TITLE
Using Magenta for beat generation based on an existing midi file?

### ISSUE THREAD

**Issue by HandsomeDevilv112** [tensorflow/magenta#800]
So, one of the demos described in the Magenta documentation is an "Interactive Musical Improvisation with Magenta" (https://github.com/tensorflow/magenta-demos/tree/master/ai-jam-ableton /)

If it works the way I think it does, it receives midi input from a keyboard, and then can output a drum beat to match your input. Would/could you be able to generate a midi through use of magenta/models/melody_rnn/,(skipping the keyboard entirely) and then use the ai jam to create a drum track/beat based on that input?

Or can this be done with the drums_rnn model?

My apologies if I missed something in documentation

**Comment by adarob** [comment]
Hi, and apologies for missing your message over on magenta-demos.
It would be great to have something like this in the AI jam demo, but it
currently doesn't support this.

For now, the easiest way to do it would be to use the drums_rnn
command-line generation script.

You can use a command similar to the one found here:
https://github.com/tensorflow/magenta/tree/master/magenta/models/drums_rnn#generate-a-drum-track

You would replace the `--primer_drums` flag with the `--primer_midi` flag,
passing it the path to your MIDI file.

Let us know if you have any more questions!

**Comment by HandsomeDevilv112** [comment]
It's all good! I should have posted to the main directory in the first place, but I was really inspired by the ai jam demo. 
I'll give that a crack and get back to you. 
I'll go ahead and close this for the moment. I'll reopen if I fall completely off the rails. 
Thanks!

**Comment by HandsomeDevilv112** [comment]
Oh, I mention this in my demos post but forgot to do so here, on the ai jam ableton page, the link for the for the simplified js version is pointing to the wrong place. 
I believe it should be 
https://github.com/tensorflow/magenta-demos/tree/master/ai-jam-js 
instead of
https://github.com/tensorflow/magenta-demos/blob/master/demos/ai-jam-js
