### ISSUE TITLE
ImportError: No module named magenta.models.sketch_rnn.sketch_rnn_train

### ISSUE THREAD

**Issue by QianhuiWu** [tensorflow/magenta#804]
I created a python file in ~/magenta/magenta/models/sketch_rnn named test.py, and there was a sentence in test.py:
from magenta.models.sketch_rnn.sketch_rnn_train import *

then I got:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named magenta.models.sketch_rnn.sketch_rnn_train

how to solve this problem?

**Comment by cghawthorne** [comment]
@QianhuiWu, to import sketch_rnn_train, you'll either need to install the magenta pip package and import it as a system library, or you'll need to use our [development environment](https://github.com/tensorflow/magenta#development-environment) and set up a new target for your test.py in the `BUILD` file and build it with [bazel](https://bazel.build/).

**Comment by QianhuiWu** [comment]
Thank you so much! @cghawthorne 
I made it by installing the magenta pip package ~
