### ISSUE TITLE
Mid files not playing

### ISSUE THREAD

**Issue by rpagliarix** [tensorflow/magenta#81]
are .mid files suppose to be playable? I can't get them to work with VLC

**Comment by sauravskumar99** [comment]
yes... they do play with timidity on ubuntu

**Comment by rpagliarix** [comment]
I would suggest to use another file. If that can't be opened with VLC, chances are it is, indeed, malformed.

**Comment by afuhrtrumpet** [comment]
Audacious has a built-in MIDI plugin, so you can try that. All you need to do is add a soundfont file in the settings.
