### ISSUE TITLE
Error training performance_rnn

### ISSUE THREAD

**Issue by SunAnLan** [tensorflow/magenta#817]
installed magenta by pip
TF 1.2.1

while running `python performance_rnn_create_dataset.py --input=/tmp/notesequences.tfrecord --output_dir=/tmp/performance_rnn/sequence_examples --eval_ratio=0.10`
I got an Error 

> AttributeError: 'PerformanceRnnConfig' object has no attribute 'density_bin_ranges'

**Comment by iansimon** [comment]
If you're using the pip package, you should just run the performance_rnn_create_dataset in your bin/ directory.  The source repository has some functionality not yet included in the pip package.
