### ISSUE TITLE
Using python trained magenta with RNNs .pb files for inference with other programming language

### ISSUE THREAD

**Issue by johndpope** [tensorflow/magenta#821]
with tensorflow - it's possible to load a trained model via their sdk into other programming languages. You train with python - you can load with ruby / objc / rust etc.

is it possible with this project? there's obviously very strong python developers here - but for majority of desktop apps that integrate with DAWs (digital audio workstations) this is done with c++ / c / objc etc.  

I get the graph needs to be frozen. 
but the next step, I'm stuck loading the frozen model without knowing the values I need to throw at it.  https://github.com/tensorflow/magenta/issues/715

**Comment by cghawthorne** [comment]
Here's an example of loading a trained Performance RNN model in Javascript: https://magenta.tensorflow.org/performance-rnn-browser
