### ISSUE TITLE
Error while installing magenta

### ISSUE THREAD

**Issue by krishamehta** [tensorflow/magenta#832]
I am getting the following error

`cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/RtMidi.cpp:2448:23: fatal error: jack/jack.h: No such file or directory
     #include <jack/jack.h>
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/krisha/anaconda3/envs/magenta/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u1ny4_/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ssL49X-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-u1ny4_/python-rtmidi/
`

**Comment by qieaaa** [comment]
@CPUFronz thank you!
