### ISSUE TITLE
performance generate error

### ISSUE THREAD

**Issue by InhyukYee** [tensorflow/magenta#833]
When i tried to generate midi files from pre-trained model(performance), it prints as below with nothing generated.
However, it used to work before i reflected updates.

Command
====== 
python performance_rnn_generate.py --config performance --bundle_file ~/git/magenta/pre_trained/performance.mag --output_dir ~/git/magenta/output/performance --num_outputs 10 --num_steps 3000 --primer_melody="[60,62,64,65,67,69,71,72]""
======

Error Logs
======
Traceback (most recent call last):
  File "performance_rnn_generate.py", line 292, in <module>
    console_entry_point()
  File "performance_rnn_generate.py", line 288, in console_entry_point
    tf.app.run(main)
  File "/home/inhyuk/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "performance_rnn_generate.py", line 271, in main
    note_density_conditioning=config.density_bin_ranges is not None,
AttributeError: 'PerformanceRnnConfig' object has no attribute 'density_bin_ranges'
=======

**Comment by cghawthorne** [comment]
I think this is because the previous version of the pip package didn't include the density options for performance rnn. We just released a new package yesterday. Can you try upgrading and see if it works?

**Comment by InhyukYee** [comment]
Thanks! it works!
upgrading magenta works for me
