### ISSUE TITLE
Error while installing magenta on python3

### ISSUE THREAD

**Issue by chestnut3108** [tensorflow/magenta#852]
Warning: Extension name 'rtmidi._rtmidi' does not match fully qualified name '_rtmidi' of 'src/_rtmidi.pyx'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/release.py -> build/lib.linux-x86_64-3.6/rtmidi
  running build_ext
  building 'rtmidi._rtmidi' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/home/chestnut/anaconda3/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/home/chestnut/anaconda3/include/python3.6m -c src/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/RtMidi.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/RtMidi.cpp:1101:28: fatal error: alsa/asoundlib.h: No such file or directory
   #include <alsa/asoundlib.h>
                              ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
Command "/home/chestnut/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bgohnc5e/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dn3_x24g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bgohnc5e/python-rtmidi/

**Comment by cubicova17** [comment]
@chestnut3108 what was the solution? I faced similar error

**Comment by chestnut3108** [comment]
Send me your pip install magenta logs Maybe I can help

**Comment by kylemcdonald** [comment]
I'm on Ubuntu, and I fixed a similar error with: `sudo apt install libjack-dev libasound-dev`. There is a note on the python-rtmidi page [about this requirement](https://python-rtmidi.readthedocs.io/en/latest/installation.html#linux).

**Comment by samuel-js** [comment]
@kylemcdonald Thanks, that fixed it for me too.
