### ISSUE TITLE
problem with building dataset

### ISSUE THREAD

**Issue by mbs6176966** [tensorflow/magenta#855]
when building .tfrecord file, occure problem that "killed"
such as: 
convert_dir_to_note_sequences \
  --input_dir=$INPUT_DIRECTORY \
  --output_file=$SEQUENCES_TFRECORD \
  --recursive
what's the reason for the problem? anyone help!!!
how to solve it?
forgive my terrible english~thx~
my INPUT_DIRECTORY is about 5.9GB

**Comment by mbs6176966** [comment]
it due  to all the memeory is occupied,any advice to solve this problem?thanks

**Comment by cghawthorne** [comment]
Let's track this in #888.
