### ISSUE TITLE
How to draw Rainbowgrams?

### ISSUE THREAD

**Issue by gd-zhang** [tensorflow/magenta#863]
In the website (https://magenta.tensorflow.org/nsynth), you show some examples using Rainbowgrams, but I don't find any code for this part. Could you provide the code to draw Rainbowgrams?

**Comment by jesseengel** [comment]
Thanks for the interest, here's a short gist that I used to make the figures in the paper. https://gist.github.com/jesseengel/e223622e255bd5b8c9130407397a0494
