### ISSUE TITLE
Problem with test magenta

### ISSUE THREAD

**Issue by ghostPath** [tensorflow/magenta#870]
I follow the instructions test magenta. But I got a problem, which is no module named tensorflow. But I do have tensorflow.
<img width="578" alt="wx20170907-151649 2x" src="https://user-images.githubusercontent.com/5909556/30150862-aa3b3b3c-93df-11e7-8c45-dd8008afd954.png">
<img width="569" alt="2017-09-07 3 17 43" src="https://user-images.githubusercontent.com/5909556/30150897-c536a0a2-93df-11e7-82b0-263676aaa4fb.png">
Thanks for help!

**Comment by cghawthorne** [comment]
Try running `bazel shutdown` and trying again. If you ran bazel before switching to the magenta environment, it may have cached the wrong python path.

**Comment by ghostPath** [comment]
@cghawthorne thanks!
