### ISSUE TITLE
Blaze error

### ISSUE THREAD

**Issue by KalyanK** [tensorflow/magenta#873]
Hi I am new to blaze . I am getting following error. can someone help me please?

DremelError: (ExecutionError('generic::unavailable: RPC error: 4 trying to reach (blade:dremel-service): /Dremel.QueryWithStatus to 10.102.199.16:4516 : SERVER_ERROR Insufficient restrictions:\nDestinationPermission #0: Wrong type BABYSAT in permission (we are BORG).. DestinationPermission #1: Wrong user mdbuser/blaze in restriction (we are mdbuser/dremel). DestinationPermission #2: Wrong user mdbuser/blaze in restriction (we are mdbuser/dremel). DestinationPermission #3: Wrong user mdbuser/koan-build-fuse in restriction (we are mdbuser/dremel). DestinationPermission #4: Wrong user mdbuser/buildrabbit in restriction (we are mdbuser/dremel). DestinationPermission #5: Wrong user mdbuser/buildrabbit in restriction (we are mdbuser/dremel). DestinationPermission #6: Wrong user mdbuser/buildrabbit in restriction (we are mdbuser/dremel). DestinationPermission #7: Wrong user mdbuser/build-event-service in restriction (we are mdbuser/dremel). DestinationPermission #8: Wrong user mdbuser/build-output-metadata in restriction (we are mdbuser/dremel). DestinationPermission #9: Wrong user mdbuser/build in restriction (we are mdbuser/dremel). DestinationPermission #10: Wrong user mdbuser/bladeservice-prod in restriction (we are mdbuser/dremel). DestinationPermission #11: Wrong user mdbuser/citc in restriction (we are mdbuser/dremel). DestinationPermission #12: Wrong user mdbuser/codereview in restriction (we are mdbuser/dremel). DestinationPermission #13: Wrong user mdbuser/codereview in restriction (we are mdbuser/dremel). DestinationPermission #14: Wrong user mdbuser/discovery in restriction (we are mdbuser/dremel). DestinationPermission #15: Wrong user mdbuser/ecatcher in restriction (we are mdbuser/dremel). DestinationPermission #16: Wrong user mdbuser/forge-prod in restriction (we are mdbuser/dremel). DestinationPermission #17: Wrong user mdbuser/forge-prod in restriction (we are mdbuser/dremel). DestinationPermission #18: Wrong user mdbuser/forge-hip in restriction (we are mdbuser/dremel). DestinationPermission #19: Wrong user mdbuser/forge-hip in restriction (we are mdbuser/dremel). DestinationPermission #20: Wrong user mdbuser/forge-prod-mac in restriction (we are mdbuser/dremel). DestinationPermission #21: Wrong user mdbuser/forge-prod-mac in restriction (we are mdbuser/dremel). DestinationPermission #22: Wrong user mdbuser/forge-prod-gpu in restriction (we are mdbuser/dremel). DestinationPermission #23: Wrong user mdbuser/forge-prod-gpu in restriction (we are mdbuser/dremel). DestinationPermission #24: Wrong user mdbuser/forge-prod-kvm in restriction (we are mdbuser/dremel). DestinationPermission #25: Wrong user mdbuser/forge-prod-kvm in restriction (we are mdbuser/dremel). DestinationPermission #26: Wrong user mdbuser/forge-prod in restriction (we are mdbuser/dremel). DestinationPermission #27: Wrong user mdbuser/gslb-testbed in restriction (we are mdbuser/dremel). DestinationPermission #28: Wrong user mdbuser/gslb-testbed in restriction (we are mdbuser/dremel). DestinationPermission #29: Wrong user mdbuser/gslb-prod in restriction (we are mdbuser/dremel). DestinationPermission #30: Wrong user mdbuser/gslb-prod in restriction (we are mdbuser/dremel). DestinationPermission #31: Wrong user mdbuser/blade-prod in restriction (we are mdbuser/dremel). DestinationPermission #32: Wrong user mdbuser/code-hygiene in restriction (we are mdbuser/dremel). DestinationPermission #33: Wrong user mdbuser/linter-prod in restriction (we are mdbuser/dremel). DestinationPermission #34: Wrong type BABYSAT in permission (we are BORG).. DestinationPermission #35: Wrong user mdbuser/chubby in restriction (we are mdbuser/dremel). DestinationPermission #36: Wrong user mdbuser/objfs in restriction (we are mdbuser/dremel). DestinationPermission #37: Wrong user mdbuser/objfs in restriction (we are mdbuser/dremel). DestinationPermission #38: Wrong user mdbuser/objfs in restriction (we are mdbuser/dremel). DestinationPermission #39: Wrong type CORP in permission (we are BORG).. DestinationPermission #40: Wrong user mdbuser/piper in restriction (we are mdbuser/dremel). DestinationPermission #41: Wrong user mdbuser/codemetrics in restriction (we are mdbuser/dremel). DestinationPermission #42: Wrong user mdbuser/codemetrics-qa in restriction (we are mdbuser/dremel). DestinationPermission #43: Wrong user mdbuser/srcfs in restriction (we are mdbuser/dremel). DestinationPermission #44: Wrong user mdbuser/srcfs in restriction (we are mdbuser/dremel). DestinationPermission #45: Wrong user mdbuser/piper in restriction (we are mdbuser/dremel). DestinationPermission #46: Wrong user mdbuser/piper in restriction (we are mdbuser/dremel). DestinationPermission #47: Wrong type BABYSAT in permission (we are BORG).. DestinationPermission #48: Wrong user mdbuser/svelte in restriction (we are mdbuser/dremel). DestinationPermission #49: Wrong user mdbuser/tap-qa in restriction (we are mdbuser/dremel). DestinationPermission #50: Wrong user mdbuser/tap-staging in restriction (we are mdbuser/dremel). DestinationPermission #51: Wrong user mdbuser/tap-prod in restriction (we are mdbuser/dremel). DestinationPermission #52: Wrong user mdbuser/tap-qa in restriction (we are mdbuser/dremel). DestinationPermission #53: Wrong user mdbuser/tap-staging in restriction (we are mdbuser/dremel). DestinationPermission #54: Wrong user mdbuser/tap-prod in restriction (we are mdbuser/dremel). DestinationPermission #55: Wrong type CORP in permission (we are BORG).. DestinationPermission #56: Wrong user mdbuser/x20 in restriction (we are mdbuser/dremel). DestinationPermission #57: Wrong user mdbuser/x20 in restriction (we are mdbuser/dremel). \nRestrictions in cert:\ndestination_restriction <\n  destination_permissions <\n    type: BABYSAT\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "cscs-team"\n      >\n    >\n    job: "thinmint_server"\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "cscs-team"\n          rpc_service_name: "ThinMintService"\n        >\n      >\n    >\n    description: "ThinMint Service"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "blaze"\n      >\n    >\n    job: "ecatcher.server"\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "blaze"\n          rpc_service_name: "ECatcherService"\n        >\n      >\n    >\n    description: "blaze ecatcher instance"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "blaze"\n      >\n    >\n    job: "blaze_logging"\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "blaze"\n          rpc_service_name: "BlazeLogger"\n        >\n      >\n    >\n    description: "blaze remote logging service"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "koan-build-fuse"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "koan-build-fuse"\n          rpc_service_name: "AnvilService"\n        >\n      >\n    >\n    description: "Buildrabbit Worker (legacy username)"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "buildrabbit"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "buildrabbit"\n          rpc_service_name: "AnvilService"\n        >\n      >\n    >\n    description: "Buildrabbit Worker"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "buildrabbit"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "buildrabbit"\n          rpc_service_name: "Scheduler"\n        >\n      >\n    >\n    description: "Buildrabbit Scheduler"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "buildrabbit"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "buildrabbit"\n          rpc_service_name: "BuildRabbitLoggingService"\n        >\n      >\n    >\n    description: "Buildrabbit Log Service"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "build-event-service"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "build-event-service"\n          rpc_service_name: "BuildService"\n        >\n      >\n    >\n    description: "Build Event Service"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "build-output-metadata"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "build-output-metadata"\n          rpc_service_name: "BuildService"\n        >\n      >\n    >\n    description: "Output Metadata Service"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "build"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "build"\n          rpc_service_name: "BuildService"\n        >\n      >\n    >\n    description: "Build Queue"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "bladeservice-prod"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "bladeservice-prod"\n          rpc_service_name: "BalancerChannelControl"\n        >\n      >\n    >\n    description: "stubbybalancer DSC - corp traffic can go to either batch or common shard"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "citc"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "citc"\n          rpc_service_name: "CITCService"\n        >\n      >\n    >\n    description: "CITC service"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "codereview"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "codereview"\n          rpc_service_name: "CodereviewSnapshotService"\n        >\n      >\n    >\n    description: "blade:codereview-snapshot - Critique Snapshot API"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "codereview"\n      >\n    >\n    job: "rpc-prod.server"\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "codereview"\n          rpc_service_name: "CodereviewRpcService"\n        >\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "codereview"\n          rpc_service_name: "CodereviewInternalService"\n        >\n      >\n    >\n    description: "blade:codereview-rpc - Critique Stubby API"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "discovery"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [thinmint.ReadOnly] <\n        >\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "discovery"\n          rpc_service_name: "DiscoveryService"\n        >\n      >\n    >\n    application_thinmint_descriptions <\n      path_segment: "gns"\n      restrictions <\n        [27489721] <\n        >\n      >\n    >\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "ecatcher"\n      >\n    >\n    job: "ecatcher.server"\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "ecatcher"\n          rpc_service_name: "ECatcherService"\n        >\n      >\n    >\n    description: "ecatcher (mBNS) - ECatcherService"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod"\n          rpc_service_name: "ExecuteService"\n        >\n      >\n    >\n    description: "ExecuteService - forge-prod"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod"\n          rpc_service_name: "CasService"\n        >\n      >\n    >\n    description: "CasService - forge-prod"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-hip"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-hip"\n          rpc_service_name: "ExecuteService"\n        >\n      >\n    >\n    description: "ExecuteService - forge-hip"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-hip"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-hip"\n          rpc_service_name: "CasService"\n        >\n      >\n    >\n    description: "CasService - forge-hip"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod-mac"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod-mac"\n          rpc_service_name: "ExecuteService"\n        >\n      >\n    >\n    description: "ExecuteService - forge-prod-mac"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod-mac"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod-mac"\n          rpc_service_name: "CasService"\n        >\n      >\n    >\n    description: "CasService - forge-prod-mac"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod-gpu"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod-gpu"\n          rpc_service_name: "ExecuteService"\n        >\n      >\n    >\n    description: "ExecuteService - forge-prod-gpu"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod-gpu"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod-gpu"\n          rpc_service_name: "CasService"\n        >\n      >\n    >\n    description: "CasService - forge-prod-gpu"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod-kvm"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod-kvm"\n          rpc_service_name: "ExecuteService"\n        >\n      >\n    >\n    description: "ExecuteService - forge-prod-kvm"\n  >\n  destination_permissions <\n    type: BORG\n    principal <\n      scope: MDB_USER\n      mdb_user <\n        user_name: "forge-prod-kvm"\n      >\n    >\n    rpc_services_labels <\n      restrictions <\n        [security.RpcLabelAclRestriction] <\n          mdb_owner_name: "forge-prod-kvm"\n          rpc_service_name: ... [dremel.DremelStatus] { code: SERVER_UNREACHABLE cause: UNDETERMINED_CAUSE is_cancellation_placeholder: false }',), 'SELECT opportunity_Id, speed_index/1000 as mSpeed_in_secs from smb_solutions_analytics.gms_2017_mspeed_acq_url.latest')

**Comment by adarob** [comment]
Hi.  Where exactly are you seeing this error?

**Comment by KalyanK** [comment]
Found the solution internally. Thanks.

**Comment by karlpetersson** [comment]
@KalyanK , I'm experiencing this exact issue (on another internal project). What solved it for you?
