### ISSUE TITLE
Performance RNN how to minimize note-on events with no subsequent note-off

### ISSUE THREAD

**Issue by jasondesante** [tensorflow/magenta#883]
Everything I train the performance rnn on results in a slop of notes that are all tied together.  Is this the way it's supposed to work because I thought this was only supposed to happen sometimes but everything I get out of this model is the same.  It's currently at 1600 steps and still making midi files that are only long sloppy chords.  Do I keep training it and it will go away or is this a bug?  Am I training it properly?  I made my own dataset of just Steely Dan songs.

**Comment by iansimon** [comment]
It will never go away entirely, but 1600 steps is almost certainly not enough.  For our pretrained models (on ~1400 classical pieces) we trained for many tens of thousands of steps.

Also, when you synthesize the generated MIDI, you may want to use a synth where notes eventually decay to zero.  This doesn't actually solve the problem, but makes it less unpleasant.
