### ISSUE TITLE
Training models on small datasets

### ISSUE THREAD

**Issue by jasondesante** [tensorflow/magenta#884]
I made a dataset with a few midi files, just smash mouth all star, darude sandstorm, flintstones theme, and a few others.  When trying to make the dataset for the different models they would all show up as 0 bytes when done, except melody_rnn which would make a 1mb file training_melodies.tfrecord file, and 0 bytes evaluation file.

Is there a min requirement for the size of the dataset?  Or do I need to format the midi files a certain way for the other models?  How do I get past this rule and trick it into learning from 5 songs?

I want to properly generate these sequence examples so I can then train the different models on different datasets for different amounts of time.  I need to get past this problem of having training sets of 0 bytes, and sometimes the training set has a size but the evaluation set is 0 bytes.  

Also to Magenta team I apologize for posting my questions here, not sure where else to post them.  Once I learn stuff I will then know and not need to ask though so I appreciate any help. Thanks.

**Comment by mbs6176966** [comment]
first you should read readme.md file seriously,  you should turn this midi file to .tfrecord file. and then generated notesequence from .tfrecord file. the notesequence  is the training set to build your model.

**Comment by mbs6176966** [comment]
all the tutorials are in README.md in each directory

**Comment by jasondesante** [comment]
@mbs6176966 that's exactly what I did what did I write make you assume I was too stupid to do that?

**Comment by cghawthorne** [comment]
Can you include the output of the commands you used to generate the datasets? They should include some debugging information about what was included and why. Exactly how the dataset is generated varies for each model.

**Comment by mbs6176966** [comment]
Forgive me bad English~ :),  i faced your problem before,  the tutorial have writen how to generated trianing set and the evaluation set like that:"melody_rnn_create_dataset \
--config=<one of 'basic_rnn', 'lookback_rnn', or 'attention_rnn'> \
--input=/tmp/notesequences.tfrecord \
--output_dir=/tmp/melody_rnn/sequence_examples \
--eval_ratio=0.10"
focus on the last param  "--eval_ration"  it means training set :  evaluation set = 9 : 1,so you should have 10 midi file in your floder at least.  this is my personal view.

**Comment by timoisik** [comment]
I have encountered the same problem (using it with docker). My `eval_melodies.tfrecord` and `training_melodies.tfrecord` files are empty:

`-rw-r--r-- 1 root root 0 Feb 26 12:10 eval_melodies.tfrecord`
`-rw-r--r-- 1 root root 0 Feb 26 12:10 training_melodies.tfrecord`

I did run the following command to create note sequences first:

```
convert_dir_to_note_sequences \
--input_dir=$INPUT_DIRECTORY \
--output_file=$SEQUENCES_TFRECORD \
--recursive
```

which gives me the following output (I used 40 midi files downloaded from the web):

```
INFO:tensorflow:Converting files in '/midi-files/'.
INFO:tensorflow:0 files converted.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus90_1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bor_ps1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se8_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus22_2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bor_ps2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/appass_1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus10_3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_hammerklavier_1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_hammerklavier_4_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus90_2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_les_adieux_2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/appass_3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_esp6_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_esp1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_esp3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus22_1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/appass_2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus22_3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bor_ps6_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus22_4_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_hammerklavier_3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_les_adieux_1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bach_846_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se5_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus10_2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_opus10_1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_esp5_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bach_847_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bor_ps3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_hammerklavier_2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se4_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_esp4_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se7_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_esp2_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se1_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/beethoven_les_adieux_3_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/alb_se6_format0.mid.
INFO:tensorflow:Converted MIDI file /midi-files/bach_850_format0.mid.
```

The generated `notesequences.tfrecord` file is not empty: 

`-rw-r--r-- 1 root root 3706900 Feb 26 12:09 notesequences.tfrecord`

Than I did run the command to create the sequence examples:

```
melody_rnn_create_dataset \
--config=lookback_rnn \
--input=/tmp/notesequences.tfrecord \
--output_dir=/tmp/melody_rnn/sequence_examples \
--eval_ratio=0.10
```

Which gives me the following output:

```
INFO:tensorflow:

Completed.

INFO:tensorflow:Processed 40 inputs total. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_melodies_discarded_too_short: 180
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_melodies_truncated: 0
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_melody_lengths_in_bars:

INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_polyphonic_tracks_discarded: 297
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_melodies_discarded_too_few_pitches: 0
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_melodies_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_melodies_discarded_too_short: 10638
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_melodies_truncated: 0
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_melody_lengths_in_bars:

INFO:tensorflow:DAGPipeline_MelodyExtractor_training_polyphonic_tracks_discarded: 18665
INFO:tensorflow:DAGPipeline_RandomPartition_eval_melodies_count: 1
INFO:tensorflow:DAGPipeline_RandomPartition_training_melodies_count: 39
```

I see, that it produced 0 outputs. But what is the problem here? Are 40 midi files not enough? Or did i miss something else? 

Thanks for your help.

**Comment by cghawthorne** [comment]
@timoisik the problem is that all of the sequences were discarded for various reasons. The output has some diagnostic info about that. Here are the relevant lines:

```
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_melodies_discarded_too_short: 180
INFO:tensorflow:DAGPipeline_MelodyExtractor_eval_polyphonic_tracks_discarded: 297
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_melodies_discarded_too_short: 10638
INFO:tensorflow:DAGPipeline_MelodyExtractor_training_polyphonic_tracks_discarded: 18665
```

For training the melody model, I don't think the tracks you're using will work. They look like polyphonic piano words. You'll want something that has tracks with monophonic lines.
