### ISSUE TITLE
Convert directory serially to save memory

### ISSUE THREAD

**Issue by MichaelMa2014** [tensorflow/magenta#888]
Different threads in Python share the same CPU core, so using ThreadPool (almost) doesn't speed up the conversion but takes a lot of memory because the resources are not released until all the threads exit. Converting 50000 files, in my experience, takes more than 50GB memory, which makes dealing with big data sets difficult. I will submit a serialized version as a PR in a minute.

**Comment by mbs6176966** [comment]
any efficient solution for this proble? i have increased my RAM from 8G to 32G,but still haven't solve the problem of training big .tfrecord file.
