### ISSUE TITLE
ERROR: java.io.IOException: Could not read the crosstool configuration file

### ISSUE THREAD

**Issue by EvilMudkip** [tensorflow/magenta#890]
Hi guys,

so I've been installing Magenta and Bazel and when I type:
`bazel test //magenta/...`
I get an ERROR message:

`ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file C:/users/fei/appdata/local/temp/_bazel_fei/uyk23a1f/external/local_config_cc/CROSSTOOL', because of a parser error (289:987: Expected identifier. Found '%').`

and then followed by:

`ERROR: Couldn't start the build. Unable to run tests.`

Can anyone help? :'(

**Comment by cghawthorne** [comment]
I haven't see that error before, but it looks like an issue with bazel on windows. I'd suggest reporting it on the Bazel project issue tracker: https://github.com/bazelbuild/bazel/issues

**Comment by EvilMudkip** [comment]
Okay thanks
