### ISSUE TITLE
Generate melody with basic_rnn

### ISSUE THREAD

**Issue by EvilMudkip** [tensorflow/magenta#894]
Hi,

I'm trying to generate a basic melody using the code shown in the tutorial, and I've got 2 questions. Note I'm a beginner, hence my questions may be really simple.

1) When I type in Python:
`BUNDLE_PATH=<E:\Storage\Documents\FEI_AI\magenta\BUNDLES>`
It returns Syntax Error,pointing at '<'

So I used:
`BUNDLE_PATH='E:\Storage\Documents\FEI_AI\magenta\BUNDLES'`
It proceeds without error. But is it correct? Same goes with the next line involving CONFIG.

2) After typing:
`melody_rnn_generate \`
I typed:
`--config=${CONFIG}`
It returns Invalid Syntax, and points at '$'.

Need advice, thank you!

**Comment by mbs6176966** [comment]
you should type --config='basic_rnn'

**Comment by EvilMudkip** [comment]
@mbs6176966 It returns syntax error.
![capture](https://user-images.githubusercontent.com/31815007/30795198-fdd40eb8-a1fe-11e7-99b8-763741091795.PNG)

**Comment by EvilMudkip** [comment]
@mbs6176966 
I tried typing the whole thing out, but I still get an error...
![capture](https://user-images.githubusercontent.com/31815007/30795321-89e6b144-a1ff-11e7-820d-4d9d73d09801.PNG)

**Comment by mbs6176966** [comment]
you should type all command in one line,don't copy and paste,try this way!!! not using "\"

**Comment by EvilMudkip** [comment]
Hi, I tried typing them all in one line, but the same error still shows up...

![capture](https://user-images.githubusercontent.com/31815007/30798134-ff8d8e08-a20a-11e7-827d-9c9d4c74bb70.PNG)

**Comment by mbs6176966** [comment]
have you been in magenta environment? run the command like:"source activate magenta"  in your terminal. you should not run the python.

**Comment by mbs6176966** [comment]
<img width="962" alt="2017-09-25 4 14 25" src="https://user-images.githubusercontent.com/23095057/30798559-ac35ba94-a20c-11e7-9ab6-78e58c02ad0b.png">

**Comment by EvilMudkip** [comment]
@mbs6176966 Thanks for the guidance, but a new error comes up:

`'melody_rnn_generate' is not recognized as an internal or external command,
operable program or batch file.`

![capture](https://user-images.githubusercontent.com/31815007/30798824-7e49b850-a20d-11e7-9e74-794981bd6e68.PNG)

**Comment by mbs6176966** [comment]
ok~,have nerver encountered this problem! but  run the python file may file.     just like "python /Users/calvin/Desktop/magenta-master/magenta/models/melody_rnn/melody_rnn_sequence_generator.py -config='basic_rnn' --bundle_file=/Users/calvin/Desktop/mag/basic_rnn.mag  --output_dir=/Users/calvin/Desktop/  --num_outputs=1 --num_steps=128 --primer_melody="[60]" "

**Comment by mbs6176966** [comment]
run the python file melody_rnn_generate.py  in melody_rnn attached the args  "--config ....."

**Comment by EvilMudkip** [comment]
@mbs6176966 Hi, I've tried your suggestion, but now an error comes up:

![untitled](https://user-images.githubusercontent.com/31815007/30811990-4ce09f48-a23c-11e7-9518-c8b5fcb49807.png)

And the error code is:

`Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.`

**Comment by cghawthorne** [comment]
That appears to be an issue with the MKL library on Windows. I'm not familiar with exactly what the issue is, but you could try uninstalling MKL with the instructions here: https://docs.anaconda.com/mkl-optimizations/

**Comment by EvilMudkip** [comment]
@cghawthorne Hi, I'm not able to remove mkl on Windows, since nomkl is not available on Windows. If I remove mkl completely, the error will ask for numpy to be installed. if I type `conda install numpy` mkl will be installed along with numpy.

**Comment by EvilMudkip** [comment]
@mbs6176966 @cghawthorne Right now when I type in:
`python E:\Storage\Documents\FEI_AI\magenta\magenta\models\melody_rnn\melody_rnn_generate.py --config='attention_rnn' --bundle_file='E:\Storage\Documents\FEI_AI\magenta\BUNDLES\attention_rnn.mag' --output_dir='E:\Storage\Documents\FEI_AI\magenta\Generated' --num_outputs=10 --num_steps=128 --primer_melody="[60]"`

I get the following error:
`Traceback (most recent call last):
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Storage\Documents\FEI_AI\magenta\magenta\models\melody_rnn\melody_rnn_generate.py", line 22, in <module>
    import tensorflow as tf
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "E:\Storage\Documents\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified procedure could not be found.`

**Comment by cghawthorne** [comment]
Hmm, I'm not really sure. You could try using a non-Ananconda Python build or maybe ask on the Anaconda issue tracker.
