### ISSUE TITLE
Output purely Black image when using image_stylization_transform

### ISSUE THREAD

**Issue by sann5130** [tensorflow/magenta#896]
Output is a purely black image when I used these commands:

$image_stylization_transform \       --num_styles=10 \      --checkpoint=~/Desktop/multistyle-pastiche-generator-monet.ckpt \      --input_image=~/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/evaluation_images/picabo_lava.jpg \      --which_styles="[8]" \      --output_dir=~/Desktop/image_stylization/output  \     --output_basename="stylized"

**Comment by jmkhael** [comment]
how was this resolved? I am experiencing the same behavior

**Comment by jmkhael** [comment]
ok, more info here: https://github.com/tensorflow/magenta/issues/570
