### ISSUE TITLE
how to change the generated midi sounds from paino to guitar by run melody_rnn_generate.py script??

### ISSUE THREAD

**Issue by Calvin-Shen** [tensorflow/magenta#912]
by running melody_rnn_generate order, we always get paino midi,and now I want to get guitar midi through the same order,how to change the source code?

**Comment by Calvin-Shen** [comment]
@cghawthorne @markmcd

**Comment by cghawthorne** [comment]
You can add a program argument to the to_sequence call here: https://github.com/tensorflow/magenta/blob/master/magenta/models/melody_rnn/melody_rnn_sequence_generator.py#L128

However, I'd recommend just loading the midi into a DAW (e.g., GarageBand) and modifying it that way.

**Comment by Calvin-Shen** [comment]
thanks for your answer~  i have solved this problem~ :)
