### ISSUE TITLE
how to train a model that can generate midi file which can generate complex tone or harmony?

### ISSUE THREAD

**Issue by Calvin-Shen** [tensorflow/magenta#917]
After I  used melody_rnn_generate commands to generate midi files.  I played the generated midi files, finding that the music sounds so machiney that without any harmony, complex tone, or etc.
The generated music is always monophonic. This always annoys me so much. 
I want to ask how to adjust the model or any necessary step i need to take,if I'd like the model can generate melodious music!
Thanks for any help~~~

**Comment by Calvin-Shen** [comment]
@cghawthorne @markmcd @astromme @notjosh @proppy

**Comment by cghawthorne** [comment]
I'd suggest taking a look at [Performance RNN](https://github.com/tensorflow/magenta/tree/master/magenta/models/performance_rnn). It can generate polyphonic music with expressive timing and dynamics. You might also be interested in our [web demo](https://magenta.tensorflow.org/performance-rnn-browser) of that model.

**Comment by Calvin-Shen** [comment]
Thank you for your suggestion~ I will have a try~

**Comment by Calvin-Shen** [comment]
Thank you for your suggestion~ I will have a try~ @cghawthorne
