### ISSUE TITLE
nsynth wavenet multi-gpu

### ISSUE THREAD

**Issue by lsq357** [tensorflow/magenta#934]
Thank you for you source code!
In the Nsynth's readme.md, There is not show us that how to  train in `multi-gpu mode`
In addition, how to set the [`master` `task worker_replicas` `ps_task` `total_batch_size`](https://github.com/tensorflow/magenta/blob/4112def219c8bfe090010df0f4db2cc094fd0613/magenta/models/nsynth/wavenet/train.py#L32) param?

**Comment by jesseengel** [comment]
Sorry, but multi-gpu training is not currently supported externally. See #625
