### ISSUE TITLE
Bazel test failed on Ubuntu 16.04 LTS, Bazel 0.30

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/magenta#95]
When I am following instructions on the README,  when running

`bazel test //magenta:all`

it shows  errors

```
WARNING: /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/external/protobuf/WORKSPACE:1: Workspace name in /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 5 targets and 6 test targets...
FAIL: //magenta:note_sequence_io_test (see /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/note_sequence_io_test/test.log).
FAIL: //magenta:sequence_to_melodies_test (see /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/sequence_to_melodies_test/test.log).
FAIL: //magenta:convert_midi_dir_to_note_sequences_test (see /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/convert_midi_dir_to_note_sequences_test/test.log).
FAIL: //magenta:melodies_lib_test (see /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/melodies_lib_test/test.log).
FAIL: //magenta:basic_one_hot_encoder_test (see /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/basic_one_hot_encoder_test/test.log).
FAIL: //magenta:midi_io_test (see /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/midi_io_test/test.log).
INFO: Elapsed time: 0.576s, Critical Path: 0.40s
//magenta:basic_one_hot_encoder_test                                     FAILED in 0.1s
  /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/basic_one_hot_encoder_test/test.log
//magenta:convert_midi_dir_to_note_sequences_test                        FAILED in 0.1s
  /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/convert_midi_dir_to_note_sequences_test/test.log
//magenta:melodies_lib_test                                              FAILED in 0.1s
  /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/melodies_lib_test/test.log
//magenta:midi_io_test                                                   FAILED in 0.4s
  /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/midi_io_test/test.log
//magenta:note_sequence_io_test                                          FAILED in 0.1s
  /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/note_sequence_io_test/test.log
//magenta:sequence_to_melodies_test                                      FAILED in 0.1s
  /home/private/.cache/bazel/_bazel_private/c45d77cbbbf828100c725e9c54fd2fa6/execroot/magenta/bazel-out/local-opt/testlogs/magenta/sequence_to_melodies_test/test.log


Executed 6 out of 6 tests: 6 fail locally.
```

I have installed 

`sudo apt-get install openjdk-8-jdk` 

and Bazel  0.30,  TensorFlow 0.9 (Anaconda-based) under Ubuntu 16.04 LTS

**Comment by cinjon** [comment]
Hi Xingdong, I noticed that you referenced https://github.com/bazelbuild/bazel/issues/1456, which suggests purging openjdk-9. Did that work for you?

**Comment by zuoxingdong** [comment]
@cinjon  Hi, it helped for the bazel installation, since it was failed to install bazel. And now it generate this new problem when `bazel test //magenta:all`

**Comment by cinjon** [comment]
Ah ok. Do you mind posting those logs please? I don't have a 16.04 distribution handy so it's hard for me to reproduce this.

**Comment by zuoxingdong** [comment]
@cinjon  For each log, there is only one error

`ImportError: No module named tensorflow`

The TensorFlow 0.9 is installed via Anaconda approach mentioned on TF official website, and created a conda virtual environment called tensorflow, it is a bit strange because I've already has run `source activate tensorflow` before `bazel test //magenta:all`. 

By the way, is it related to the reason that import tensorflow only works on `> python` and `> jupyter notebook` but not `> ipython` since it cannot be imported within terminal version of ipython.

**Comment by cinjon** [comment]
When you go into a python shell, can you import tensorflow?

**Comment by zuoxingdong** [comment]
@cinjon  Yes, it works there.

**Comment by denisfitz57** [comment]
I "fixed" what may be the same problem by changing the symbolic link in /usr/bin to point to my Anaconda version:
$ which python
/home/denis/anaconda2/bin/python
sudo ln -s ./usr/bin/python /home/denis/anaconda2/bin/python

"fixed" is in quotes because messing with the system python link seems bad, but tensorflow is all I'm using it for right now, so it's a risk I can take.
I'm guessing something in bazel needs to not point directly to /usr/bin/python?

**Comment by DenisSergeevitch** [comment]
Same here on OSX 10.11.3 with Python3, bazel-0.2.3: 
`INFO: From Linking external/protobuf/libprotobuf.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/io/gzip_stream.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/util/internal/error_listener.o has no symbols
FAIL: //magenta/lib:note_sequence_io_test (see /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log).
FAIL: //magenta/lib:melodies_lib_test (see /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/melodies_lib_test/test.log).
FAIL: //magenta/scripts:convert_midi_dir_to_note_sequences_test (see /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log).
FAIL: //magenta/lib:sequence_to_melodies_test (see /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/sequence_to_melodies_test/test.log).
FAIL: //magenta/lib:midi_io_test (see /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/midi_io_test/test.log).
INFO: Elapsed time: 236.603s, Critical Path: 151.26s
//magenta/lib:melodies_lib_test                                          FAILED in 0.1s
  /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/melodies_lib_test/test.log
//magenta/lib:midi_io_test                                               FAILED in 0.7s
  /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/midi_io_test/test.log
//magenta/lib:note_sequence_io_test                                      FAILED in 0.3s
  /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log
//magenta/lib:sequence_to_melodies_test                                  FAILED in 0.2s
  /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/lib/sequence_to_melodies_test/test.log
//magenta/scripts:convert_midi_dir_to_note_sequences_test                FAILED in 0.1s
  /private/var/tmp/_bazel_pro16/527da629019d0e0e5af6b2949120dbb7/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log

Executed 5 out of 5 tests: 5 fail locally.`

**Comment by bgenchel** [comment]
same on OSX El Capitan

`WARNING: /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 30 targets and 5 test targets...
FAIL: //magenta/lib:sequence_to_melodies_test (see /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/sequence_to_melodies_test/test.log).
FAIL: //magenta/lib:note_sequence_io_test (see /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log).
FAIL: //magenta/lib:melodies_lib_test (see /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/melodies_lib_test/test.log).
FAIL: //magenta/scripts:convert_midi_dir_to_note_sequences_test (see /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log).
FAIL: //magenta/lib:midi_io_test (see /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/midi_io_test/test.log).
INFO: Elapsed time: 5.088s, Critical Path: 1.41s
//magenta/lib:melodies_lib_test                                          FAILED in 0.7s
  /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/melodies_lib_test/test.log
//magenta/lib:midi_io_test                                               FAILED in 0.9s
  /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/midi_io_test/test.log
//magenta/lib:note_sequence_io_test                                      FAILED in 0.7s
  /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log
//magenta/lib:sequence_to_melodies_test                                  FAILED in 0.7s
  /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/sequence_to_melodies_test/test.log
//magenta/scripts:convert_midi_dir_to_note_sequences_test                FAILED in 0.9s
  /private/var/tmp/_bazel_benjamingenchel/1c269da31038396025e7f6c0675c28b2/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log`

**Comment by cghawthorne** [comment]
@zuoxingdong can you try installing bazel 0.2.3? I've also had some problems where bazel test with 0.3.0 overwrites the environment variable pointing to my virtualenv.

Another thing to try would be running the tests directly out of bazel-bin/ and see if that works.

**Comment by zuoxingdong** [comment]
@cghawthorne  I've tried with Bazel 0.2.3, now it is working fine. Thanks for the advice, and this issue might be ok to close.
