### ISSUE TITLE
More than just piano?

### ISSUE THREAD

**Issue by SkyrisBactera** [tensorflow/magenta#956]
Is it possible using any of the models (except for the NSynth model, because it doesn't use MIDI), to generate MIDI files with more than 1 MIDI instrument?

**Comment by Calvin-Shen** [comment]
if you want to generate midi files with more instruments,maybe you should edit the code by yourself,becaulse  I traced the code "melody_rnn_generate" and know that beforing generating midi file,you should refer a certain instrument. and so as other model in my opinion.

**Comment by SkyrisBactera** [comment]
I understand that I can change piano to another instrument, but I'm asking if the music models could use multiple instruments at once.

**Comment by iansimon** [comment]
I was playing around with a variant on Performance RNN that handles multiple instruments.  Code is [here](https://github.com/iansimon/magenta/tree/midi_rnn) but not sure it's in a great state; that said, it should be fairly straightforward to modify the Performance RNN representation to handle instrument change events.

Of course, stuffing all instruments into a single stream might very well not be the best way to handle multiple instrument generation...

**Comment by SkyrisBactera** [comment]
Thanks! I'll try that out!

**Comment by nodiz** [comment]
Any related news? @iansimon @Programmerino

**Comment by adarob** [comment]
There is also MusicVAE which supports Trio models with multiple instruments as well as the Multi-Track model.
