### ISSUE TITLE
ImportError: cannot import name 'music_pb2'

### ISSUE THREAD

**Issue by Saran-nns** [tensorflow/magenta#983]
I am trying to train wavenet using my own .wav files. magenta-master is in sys path.

Error : 
magenta-master/magenta/music/abc_parser.py", line 33, in <module>
from magenta.protobuf import music_pb2
ImportError: cannot import name 'music_pb2', 

The parser failed. Module 'music_pb2' found missing .

**Comment by cghawthorne** [comment]
Because of the way our protobuf files are generated, you cannot run the python files directly from the repo. You'll need to either install our pip package or set up the Magenta dev environment as documented here: https://github.com/tensorflow/magenta#development-environment
