### ISSUE TITLE
Residual and Skip connections are not padded, not causal?

### ISSUE THREAD

**Issue by rafaelvalle** [tensorflow/magenta#992]
Hi magenta! Thanks for making this public! I was looking over the code below and realized that the 1x1 residual and skip connections have no padding! Shouldn't these connections be padded by kernel size - 1 such that they are causal ? The link to the code is below
https://github.com/tensorflow/magenta/blob/master/magenta/models/nsynth/wavenet/h512_bo16.py#L282

**Comment by jesseengel** [comment]
The padding happens inside the convolution function: https://github.com/tensorflow/magenta/blob/master/magenta/models/nsynth/wavenet/masked.py#L148
