### ISSUE TITLE
Docker image - nsynth_generate: command not found

### ISSUE THREAD

**Issue by metatronscube** [tensorflow/magenta#993]
Hello there. Followed the instructions for getting the Docker image up and running. Tested the melody_rnn_generate example, which worked. Moved on to trying nsynth (the model I am most interested in) but keep getting error messages. Could anyone help me with this? I am on Windows 10 and using PowerShell. Output below.

>
>PS C:\> docker run -it -p 6006:6006 -v C:/magenta:/magenta-data tensorflow/magenta
root@335bb725e33d:/magenta-data# melody_rnn_generate \
   --config=lookback_rnn \
   --bundle_file=/magenta-models/lookback_rnn.mag \
   --output_dir=/magenta-data/lookback_rnn/generated \
   --num_outputs=10 \
   --num_steps=128 \
   --primer_melody="[60]"
INFO:tensorflow:Restoring parameters from /tmp/tmpe3ONvV/model.ckpt
INFO:tensorflow:Beam search yields sequence with log-likelihood: -137.151591
INFO:tensorflow:Beam search yields sequence with log-likelihood: -181.961511
INFO:tensorflow:Beam search yields sequence with log-likelihood: -116.759142
INFO:tensorflow:Beam search yields sequence with log-likelihood: -44.253376
INFO:tensorflow:Beam search yields sequence with log-likelihood: -40.106969
INFO:tensorflow:Beam search yields sequence with log-likelihood: -25.030310
INFO:tensorflow:Beam search yields sequence with log-likelihood: -83.305207
INFO:tensorflow:Beam search yields sequence with log-likelihood: -59.129613
INFO:tensorflow:Beam search yields sequence with log-likelihood: -101.104565
INFO:tensorflow:Beam search yields sequence with log-likelihood: -69.837903
INFO:tensorflow:Wrote 10 MIDI files to /magenta-data/lookback_rnn/generated
root@335bb725e33d:/magenta-data# nsynth_generate \
   --checkpoint_path=/magenta-data/checkpoint/wavenet-ckpt/model.ckpt-200000 \
   --source_path=/magenta-data/source \
   --save_path=/magenta-data/save \
   --batch_size=4
**bash: nsynth_generate: command not found**
root@335bb725e33d:/magenta-data# nsynth_generate --checkpoint_path=/magenta-data/checkpoint/wavenet-ckpt --source_path=/magenta-data/source --save_path=/magenta-data/save --batch_size=4
**bash: nsynth_generate: command not found**

**Comment by sandnuggah** [comment]
The image on docker hub is 8 months old and does not seem to contain the `nsynth_generate` script. Perhaps you can build your own image based on the latest source with the Dockerfile provided in this repo instead?

`docker build -t magenta https://raw.githubusercontent.com/tensorflow/magenta/master/magenta/tools/docker/Dockerfile`

**Comment by cghawthorne** [comment]
Sorry for letting the image get so stale. I've just updated it to our latest release. Hopefully that resolves your problems!
