### ISSUE TITLE
bazel test //magenta  error

### ISSUE THREAD

**Issue by dreammax2010** [tensorflow/magenta#995]
**Have I written custom code : No
OS Platform and Distribution : Windows10 64bit
TensorFlow installed from (source or binary): Source
TensorFlow version (use command below): r1.4
Python version: 2.7.12
Bazel version (if compiling from source): 0.45 
GCC/Compiler version (if compiling from source): 4.6.3

I am getting the following errors / warnings using the bazel test, whilst trying to build the magenta.

**Source code / logs**
C:\bazel\0.45>bazel.exe test //magenta
ERROR: C:/bazel/0.45/magenta/BUILD:21:1: error loading package 'magenta/protobuf': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': error loading package 'external': The repository named 'protobuf' could not be resolved and referenced by '//magenta:magenta'.
ERROR: Analysis of target '//magenta:magenta' failed; build aborted.
INFO: Elapsed time: 0.558s
ERROR: Couldn't start the build. Unable to run tests.

Any help? Thank you!

**Comment by cghawthorne** [comment]
I'm not sure why you would be getting that error. Can you trying installing the latest version of Bazel and see if that works?

**Comment by dreammax2010** [comment]
Have I written custom code : No
OS Platform and Distribution : Windows10 64bit
TensorFlow installed from (source or binary): Source
TensorFlow version (use command below): r1.4
Python version: 2.7.12
Bazel version (if compiling from source): 0.90
GCC/Compiler version (if compiling from source): 4.6.3

Here"s my WORKSPACE:
#######################################################
new_http_archive(
    name = "pretty_midi",
    build_file = "pretty_midi.BUILD",
    sha256 = "8326c9c87d5efc91670a5881581eb192b095a1c93afd5fddc91b2232af8e9b9b",
    strip_prefix = "pretty-midi-0.2.6/pretty_midi",
    url = "https://github.com/craffel/pretty-midi/archive/0.2.6.tar.gz",
)

http_archive(
    name = "protobuf",
    sha256 = "3f833c1c367f53803f5f849181af4a4edb20f8dd1fbdced19b5a2d52ee43ed54",
    strip_prefix = "protobuf-3.2.0",
    url = "https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-python-3.2.0.tar.gz",
)
new_http_archive(
    name = "six_archive",
    build_file = "six.BUILD",
    sha256 = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a",
    strip_prefix = "six-1.10.0",
    url = "https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55",
)

bind(
    name = "six",
    actual = "@six_archive//:six",
)

bind(
    name = "python_headers",
    actual = "//util/python:python_headers",
)

new_http_archive(
    name = "mido",
    build_file = "mido.BUILD",
    sha256 = "7844ff77ab12469504c46e9aa035722a2829e7c72b8b6241c78d356895e88114",
    strip_prefix = "mido-1.1.17/mido",
    url = "https://github.com/olemb/mido/archive/1.1.17.tar.gz",
)
#######################################################
Here's the error messages:
c:\bazel\0.90>bazel.exe test //magenta:all
ERROR: C:/bazel/0.90/magenta/BUILD:21:1: error loading package 'magenta/protobuf': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading [https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-python-3.2.0.tar.gz] to C:/users/gof/appdata/local/temp/_bazel_gof/m5nvlktk/external/protobuf/protobuf-python-3.2.0.tar.gz: Checksum was c574e2b2178ffe66599274e8cfa11ecf83799a7992be30f0b68fb33ea0a0f1af but wanted 3f833c1c367f53803f5f849181af4a4edb20f8dd1fbdced19b5a2d52ee43ed54 and referenced by '//magenta:magenta'
ERROR: Analysis of target '//magenta:magenta' failed; build aborted: error loading package 'magenta/protobuf': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading [https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-python-3.2.0.tar.gz] to C:/users/gof/appdata/local/temp/_bazel_gof/m5nvlktk/external/protobuf/protobuf-python-3.2.0.tar.gz: Checksum was c574e2b2178ffe66599274e8cfa11ecf83799a7992be30f0b68fb33ea0a0f1af but wanted 3f833c1c367f53803f5f849181af4a4edb20f8dd1fbdced19b5a2d52ee43ed54
INFO: Elapsed time: 312.693s
FAILED: Build did NOT complete successfully (7 packages loaded)
    currently loading: magenta/protobuf
ERROR: Couldn't start the build. Unable to run tests

@cghawthorne  Thank you!

**Comment by cghawthorne** [comment]
OK, it looks like the the protobuf library you're downloading has a checksum that's different than expected. I can't reproduce this problem on either my mac or linux environments. I don't have a Windows environment handy to test, but that shouldn't affect the checksum of the downloaded file. I suspect that there's maybe a problem with the download, like a proxy that's giving you a different file or an error page. I'd try downloading that URL (https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-python-3.2.0.tar.gz) using `wget`, `curl`, or a similar tool on the commandline and see what result you get, or just take a look at `C:/users/gof/appdata/local/temp/_bazel_gof/m5nvlktk/external/protobuf/protobuf-python-3.2.0.tar.gz` and see if the file looks like an error message.

**Comment by dreammax2010** [comment]
Whatever i use the vpn or not , i got the same error checksum
![image](https://user-images.githubusercontent.com/34936990/34595155-9a4ebfa2-f210-11e7-8818-9f07afadf24c.png)

**Comment by cghawthorne** [comment]
Oh, one thing I just noticed is that you're not using an up to date copy of the Magenta repo. Our most recent version uses `protobuf-python-3.4.0.tar.gz`. Can you try syncing your repo and trying again?

**Comment by dreammax2010** [comment]
protobuf-python-3.2.0.tar.gz => protobuf-python-3.4.0.tar.gz
bazel test //magenta:all  successful  !
Then I  tried to convert midi file to NoteSequences according to magenta/scripts/README.md

(tensorflow_theano_20180103) c:\bazel\0.90>ls magenta/my_train_dir
1.mid

(tensorflow_theano_20180103) c:\bazel\0.90>bazel run //magenta/scripts:convert_dir_to_note_sequences -- --input_dir=C:/bazel/0.90/magenta/my_train_dir --output_file=C:/bazel/0.90/magenta/my_train_dir/notesequences.tfrecord --recursive
INFO: Analysed target //magenta/scripts:convert_dir_to_note_sequences (0 packages loaded).
INFO: Found 1 target...
Target //magenta/scripts:convert_dir_to_note_sequences up-to-date:
  C:/users/gof/appdata/local/temp/_bazel_gof/m5nvlktk/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/magenta/scripts/convert_dir_to_note_sequences.exe
  C:/users/gof/appdata/local/temp/_bazel_gof/m5nvlktk/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/magenta/scripts/convert_dir_to_note_sequences.zip
INFO: Elapsed time: 1.369s, Critical Path: 0.03s
INFO: Build completed successfully, 1 total action

INFO: Running command line: C:/users/gof/appdata/local/temp/_bazel_gof/m5nvlktk/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/magenta/scripts/convert_dir_to_note_sequences.exe '--input_dir=C:/bazel/0.90/magenta/my_train_dir' '--output_file=C:/bazel/0.90/magenta/my_train_dir/notesequences.tfrecord' --recursive
Traceback (most recent call last):
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\__main__\magenta\scripts\convert_dir_to_note_sequences.py", line 34, in <module>
    from magenta.music import midi_io
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\__main__\magenta\music\midi_io.py", line 29, in <module>
    import pretty_midi
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\pretty_midi\__init__.py", line 138, in <module>
    from .pretty_midi import *
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\pretty_midi\pretty_midi.py", line 13, in <module>
    from .instrument import Instrument
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\pretty_midi\instrument.py", line 13, in <module>
    from .containers import PitchBend
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\pretty_midi\containers.py", line 5, in <module>
    from .utilities import key_number_to_key_name
  File "\\?\C:\Users\GOF\AppData\Local\Temp\Bazel.runfiles_yau5u79k\runfiles\pretty_midi\utilities.py", line 84
    ur'^(?P<key>[ABCDEFGabcdefg])'
                                 ^
SyntaxError: invalid syntax
ERROR: Non-zero return code '1' from command: Process exited with status 1

@cghawthorne  Thanks!

**Comment by dreammax2010** [comment]
TensorFlow version 1.4.0
Python version: Python 3.5.4 |Continuum Analytics
Bazel version (if compiling from source): 0.90

Is it OK to run “convert_dir_to_note_sequences”?
I tried to run “python 2to3” and i got the same error message
@cghawthorne  Thanks!

**Comment by cghawthorne** [comment]
Ah, that was a bug in pretty_midi that has since been fixed. I'll need to update our pretty_midi version.

**Comment by cghawthorne** [comment]
Oh, we should already be on pretty_midi 0.2.8, which has the fix. Have you synced your whole git repo?

**Comment by dreammax2010** [comment]
it works! Thanks！
@cghawthorne
