### ISSUE TITLE
Does Music_vae_train support python3 windows sever2012?

### ISSUE THREAD

**Issue by MarkWuNLP** [tensorflow/magenta#997]
Hi, 
    When I run music_vae_train.py, I encountered the following issue. It seems that music_vae_train does not support python3 right now? Any solution?

> 
> "C:\Program Files\Anaconda3\python.exe" C:/Users/RinnaMSRA/PycharmProjects/musicgeneration/magenta-master/magenta-master/magenta/models/music_vae/music_vae_train.py --config=cat-trio_16bar_big --run_dir=D:\data\music\log_vae --mode=train --examples_path=D:\data\music\nottingham_xml.tfrecord
> 2017-12-30 11:58:03.812382: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> 2017-12-30 11:58:04.583557: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties: 
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: ff8e:00:00.0
> totalMemory: 11.15GiB freeMemory: 10.97GiB
> 2017-12-30 11:58:04.583942: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: ff8e:00:00.0, compute capability: 3.7)
> 2017-12-30 11:58:33.431348: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\session.cc:69] Not found: No session factory registered for the given session options: {target: "local" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
> Traceback (most recent call last):
>   File "C:/Users/RinnaMSRA/PycharmProjects/musicgeneration/magenta-master/magenta-master/magenta/models/music_vae/music_vae_train.py", line 294, in <module>
>     console_entry_point()
>   File "C:/Users/RinnaMSRA/PycharmProjects/musicgeneration/magenta-master/magenta-master/magenta/models/music_vae/music_vae_train.py", line 290, in console_entry_point
>     tf.app.run(main)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "C:/Users/RinnaMSRA/PycharmProjects/musicgeneration/magenta-master/magenta-master/magenta/models/music_vae/music_vae_train.py", line 286, in main
>     run(configs.config_map)
>   File "C:/Users/RinnaMSRA/PycharmProjects/musicgeneration/magenta-master/magenta-master/magenta/models/music_vae/music_vae_train.py", line 282, in run
>     task=FLAGS.task)
>   File "C:/Users/RinnaMSRA/PycharmProjects/musicgeneration/magenta-master/magenta-master/magenta/models/music_vae/music_vae_train.py", line 176, in train
>     is_chief=is_chief)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\training\python\training\training.py", line 535, in train
>     config=config) as session:
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 368, in MonitoredTrainingSession
>     stop_grace_period_secs=stop_grace_period_secs)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 673, in __init__
>     stop_grace_period_secs=stop_grace_period_secs)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 493, in __init__
>     self._sess = _RecoverableSession(self._coordinated_creator)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 851, in __init__
>     _WrappedSession.__init__(self, self._create_session())
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 856, in _create_session
>     return self._sess_creator.create_session()
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 554, in create_session
>     self.tf_sess = self._session_creator.create_session()
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 428, in create_session
>     init_fn=self._scaffold.init_fn)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\session_manager.py", line 273, in prepare_session
>     config=config)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\session_manager.py", line 178, in _restore_checkpoint
>     sess = session.Session(self._target, graph=self._graph, config=config)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1482, in __init__
>     super(Session, self).__init__(target, graph, config=config)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 622, in __init__
>     self._session = tf_session.TF_NewDeprecatedSession(opts, status)
>   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: No session factory registered for the given session options: {target: "local" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.

**Comment by adarob** [comment]
Hi. I'm not sure why you are getting this error message. Are you running
with bazel? Have you tried using the pip package?

**Comment by MarkWuNLP** [comment]
Thank you for your reply. I fixed the bug by setting master=""  instead of local/master

**Comment by tomduncalf** [comment]
Hi @MarkWuNLP, could you elaborate on your solution please? I've got the same issue (https://github.com/tensorflow/magenta/issues/1110) but am not sure what your solution means :)

Thanks!

**Comment by tomduncalf** [comment]
Never mind, I found the solution (it was to add `--master=""` to the training command). Thanks!

**Comment by adarob** [comment]
Thanks. I will correct this in the code.
